\set ON_ERROR_STOP on

UPDATE "ContentItem" SET title = 'Anh không cần hoàn hảo.Chỉ cần hôm nay ít hơn hôm qua là đủ.', body = 'Anh không cần hoàn hảo.Chỉ cần hôm nay ít hơn hôm qua là đủ.' WHERE id = 'cmorcgwsf0006eefvnscb68wc';
UPDATE "ContentItem" SET title = 'Tin động viên', body = '1.

“Anh không cần hoàn hảo.
Chỉ cần hôm nay ít hơn hôm qua là đủ.”

2.

“5 điếu ít đi không nhỏ đâu.
Đó là 5 lần anh thắng chính mình.”

3.

“Cơ thể không nói ngay.
Nhưng nó đang cảm ơn anh mỗi ngày.”

4.

“Cơn thèm qua rồi – anh vẫn ổn.
Điều đó quan trọng hơn số điếu.”

5.

“Anh không bỏ thuốc.
Anh đang học cách không cần nó.”

6.

“Giảm chậm nhưng chắc
luôn mạnh hơn cố rồi bỏ.”

7.

“Hôm nay không tốt? Không sao.
Ngày mai mình đi tiếp.”

8.

“Anh đã đi xa hơn rất nhiều người
chưa từng bắt đầu.”

9.

“Đây không phải hành trình bỏ thuốc
mà là hành trình sống nhẹ hơn.”

10.

“Một ngày nữa trôi qua
và anh vẫn đang làm chủ.”' WHERE id = 'cmorci9j40009eefv6bu2hck8';
UPDATE "ContentItem" SET title = 'Day 3 Nhận Thức — Sol thấy gì ở {pronoun} hôm qua.', body = 'Sol bắt đầu thấy pattern. Mỗi điếu {pronoun} ghi có một trigger — stress, sau cơm, rảnh, tụ tập. Hôm nay khi châm điếu, mở chip "Lúc đó:" và chọn trigger. Sol cần dữ liệu để học thay {pronoun}.' WHERE id = 'cmotefgvl000210c6gi5aq96a';
UPDATE "ContentItem" SET title = 'Day 23: Ai đó rủ?', body = 'Nói ngắn: "Mình đã bỏ rồi." Không cần giải thích, không cần xin lỗi. Người tốt sẽ tôn trọng. Người không tốt — {pronoun} không cần.' WHERE id = 'cmoqonhps000mm0j6hbtem6bx';
UPDATE "ContentItem" SET title = 'Lally 2010 — 21 ngày = thói quen?', body = 'Lally 2010 thực ra trung bình 66 ngày để thói quen tự động. 21 ngày là điểm khởi đầu — não đã coi không-hút là default, nhưng vẫn cần phòng vệ.' WHERE id = 'cmoqonhtp001em0j6k2xg4n0j';
UPDATE "ContentItem" SET title = 'Đo nhịp tim nghỉ.', body = 'Ngồi yên 5 phút. Đo nhịp tim 1 phút. So với khi {pronoun} còn hút (~75-85). Số bây giờ = chiến tích.' WHERE id = 'cmoqonhxp0028m0j658ipwquh';
UPDATE "ContentItem" SET title = 'Đêm Day 3 — bức tường đã qua.', body = 'Ngày khó nhất mà nhiều người không vượt được — {pronoun} vượt rồi. Tỷ lệ thành công tăng 3x từ giờ. Ngủ ngon — đáng lắm.' WHERE id = 'cmoqoni0f002rm0j69vuahgwe';
UPDATE "ContentItem" SET title = 'Day 30: 30 NGÀY — TÁI SINH.', body = '{greet}. Day 30. Phổi sửa được ~30%, tim đập chậm, tuần hoàn về bình thường, vị giác về 80%. Doll & Hill BMJ 2004: cai 30+ tuổi giảm 90% nguy cơ ung thư phổi. {pronoun} đã viết lại cuộc đời. — Khang Sol' WHERE id = 'cmoqonhqt000tm0j6vinp3aqv';
UPDATE "ContentItem" SET title = 'Day 4 Nhận Thức — thèm thuốc không phải kẻ thù.', body = 'Cơn thèm là tín hiệu sinh học bình thường — não đã quen có nicotin, giờ thiếu thì gọi {pronoun}. Đây không phải dấu hiệu yếu đuối. Sol mong {pronoun} đừng tự trách khi thấy thèm — chỉ cần ghi nhận.' WHERE id = 'cmotefgvr000310c6vri51vsb';
UPDATE "ContentItem" SET title = 'Day 5 Nhận Thức — trigger là tín hiệu, không phải lệnh.', body = 'Trigger {pronoun} hay gặp nhất là gì? (stress, sau cơm, rảnh…). Trigger chỉ là "lúc não nghĩ đến thuốc" — không phải lệnh phải hút. Hôm nay {pronoun} thử: khi trigger lên, đếm 10 hơi thở chậm trước khi quyết định.' WHERE id = 'cmotefgvy000410c6uvrt21la';
UPDATE "ContentItem" SET title = 'Day 6 Nhận Thức — {pronoun} đã có 5 ngày dữ liệu.', body = 'Sol đã thấy nhịp của {pronoun}. Pattern có thể lộ rõ: peak hour, top trigger, mood theo ngày. Vào tab "Phân tích" → 🌱 Nhận Thức để xem heatmap. Đây là {pronoun} thật — Sol không che.' WHERE id = 'cmotefgw5000510c6y40wnqlx';
UPDATE "ContentItem" SET title = 'Day 7 Nhận Thức — tuần sau bắt đầu Hành Động.', body = 'Mình là Khang. Tuần Nhận Thức của {pronoun} sắp xong. Tuần sau Sol sẽ gợi {pronoun} delay craving, swap habit. Đừng vội — mình đã đi chính con đường này. Hôm nay đọc lại pattern của {pronoun}, ngày mai bắt đầu phá nhẹ. — Khang Sol' WHERE id = 'cmotefgwb000610c6gb10fymr';
UPDATE "ContentItem" SET title = 'Day 8 Hành Động — không cần dữ dội.', body = 'Mình là Khang. Tuần Nhận Thức xong, giờ Hành Động — nhưng đừng "cắt máu". Hôm nay chỉ làm 1 việc: chọn 1 điếu thường hút (vd điếu cà phê sáng), thử delay 10 phút. Chỉ 10 phút thôi. Não cần học rằng "thèm" và "hút" có thể tách. — Khang Sol' WHERE id = 'cmotefgwi000710c6lw81yfc1';
UPDATE "ContentItem" SET title = 'Day 9 Hành Động — delay 10 phút phá vòng lặp.', body = 'Phần lớn cơn thèm tự tắt sau 8 phút (Hughes 2007). Nếu hôm qua delay 10 phút thành công 1 lần, hôm nay thử 2 lần. Khi bỏ qua được, bấm "Bỏ qua được" trong logger. Mỗi lần bỏ qua = 1 chiến thắng nhỏ Sol đếm cho {pronoun}.' WHERE id = 'cmotefgwo000810c6df305agy';
UPDATE "ContentItem" SET title = 'Day 10 Hành Động — Plan B cho trigger mạnh nhất.', body = 'Top trigger của {pronoun} đến giờ là gì? Sol đã đo. Hôm nay Sol gợi Plan B cụ thể (xem trong Tổng quan). Stress → cốc nước lạnh + đi bộ 5''. Sau cơm → đánh răng. Tụ tập → gọi nước trước. Plan B sẵn = não có lựa chọn.' WHERE id = 'cmotefgwu000910c6diunl8w1';
UPDATE "ContentItem" SET title = 'Day 2 Nhận Thức — quan sát mà không phán xét.', body = 'Hôm qua {pronoun} đã ghi mấy điếu? Bao nhiêu cũng đúng — đây là số thật, không phải số "đẹp". Hôm nay khi định châm điếu, thử quan sát: lúc đó {pronoun} đang cảm gì? đang ở đâu?' WHERE id = 'cmotefgve000110c6j1aljd3i';
UPDATE "ContentItem" SET title = 'Sao bỏ thuốc lại tăng cân?', body = '3 lý do: vi sinh ruột phục hồi, nụ vị giác trở lại (ăn ngon hơn), thay thuốc bằng đồ ngọt. Đây không phải mỡ xấu — là sửa chữa.' WHERE id = 'cmoqonht20019m0j6lq8gb0wz';
UPDATE "ContentItem" SET title = 'Người 50+ cai — tuổi thọ.', body = 'Doll & Hill BMJ 2004: cai trước 60 tuổi → đảo ngược 60% nguy cơ tử vong sớm do hút. Cai trước 50 → 90%. {pronoun} đang đua thời gian thắng.' WHERE id = 'cmoqonhun001lm0j6vq00kzo1';
UPDATE "ContentItem" SET title = 'Cuối tuần đầu — bẫy lớn.', body = 'Cuối tuần là khi guard hạ + thời gian rảnh nhiều. Khoảng 40% relapse xảy ra cuối tuần đầu (Hughes). Tối nay tránh nhậu, tránh tụ tập có người hút.' WHERE id = 'cmoqri79g0000hlltkt9l6jih';
UPDATE "ContentItem" SET title = 'Nhậu cuối tuần — risky.', body = 'Rượu hạ guard + drop dopamine → cơn thèm mạnh trở lại. Nếu phải đi: gọi nước trước, ngồi xa người hút, cớ về sớm. Hoặc skip — không ai giận đâu.' WHERE id = 'cmoqri79v0001hlltnkrnvube';
UPDATE "ContentItem" SET title = 'Buồn không lý do?', body = 'Ngày này nhiều người báo "tự nhiên buồn" — não đang reset baseline cảm xúc. 3-5 ngày sẽ qua. Đi bộ ngoài trời, gọi 1 người thân, viết 3 dòng.' WHERE id = 'cmoqri7a10002hlltyzdwj587';
UPDATE "ContentItem" SET title = 'Sắp 30 — đừng buông.', body = 'Cảnh báo cuối: nhiều người relapse Day 28-32 vì "đã xong rồi, ăn mừng 1 điếu". 1 điếu = quay lại Day 1. Day 30 không phải đích — là khởi đầu.' WHERE id = 'cmoqri7a80003hlltmrxr7ddj';
UPDATE "ContentItem" SET title = 'Uống nước lạnh chậm.', body = 'Khi cáu lên: 1 cốc nước lạnh, uống chậm từng ngụm. Nước lạnh kích thích dây vagus → hạ cortisol nhanh. Khoa học, không vớ vẩn.' WHERE id = 'cmoqonhwh001zm0j6wjlv1yw3';
UPDATE "ContentItem" SET title = 'Đêm Day 1 — viên đá đầu.', body = '24 giờ sạch nicotin. Cơ thể bắt đầu thải. Đêm nay {pronoun} ngủ với 1 quyết định lớn nhất 25 năm. Mai dễ hơn 1 chút.' WHERE id = 'cmoqoni05002pm0j6byxn8z7t';
UPDATE "ContentItem" SET title = 'Đêm Day 14 — bước ngoặt.', body = 'Receptor não giảm 40%. Não bắt đầu coi không-hút là bình thường. Mặt trận tâm lý từ giờ — mạnh đã có. Đêm nay tự hào nhỏ — đáng.' WHERE id = 'cmoqoni210032m0j6i8374v58';
UPDATE "ContentItem" SET title = 'Day 29: Mai là 30.', body = 'Mình muốn nói thật với {pronoun}: 30 ngày KHÔNG phải đích. Là cột mốc. Sau Day 30 là tiếp tục — nhưng dễ hơn nhiều. Mình đã đi đường đó. — Khang Sol' WHERE id = 'cmoqonhqo000sm0j6g0ktw4v3';
UPDATE "ContentItem" SET title = 'Nhóm “giữ người lại', body = '🧠 Nhóm “giữ người lại”
“Không cần bỏ ngay. Chỉ cần hôm nay nhẹ hơn một chút.”
“Không sao nếu hôm nay khó. Mình vẫn đang đi.”
“Anh không cần mạnh hơn. Chỉ cần không dừng lại.”
“Mệt thì đi chậm. Đừng quay lại.”
“Không ai làm tốt ngay từ đầu.”' WHERE id = 'cmorf6lao000aeefvwxe5b0bf';
UPDATE "ContentItem" SET title = 'Day 13 Hành Động — sau cơm thử đánh răng.', body = '"Sau cơm 1 điếu" là một trong những trigger khó phá nhất — vì đó là pattern dopamine 20+ năm. Hack đơn giản: đánh răng ngay sau khi ăn. Vị bạc hà + miệng sạch sẽ làm cơn thèm giảm 70%. Thử hôm nay.' WHERE id = 'cmotefgxd000c10c6a7r7ylrn';
UPDATE "ContentItem" SET title = 'Day 14 Hành Động — 1 tuần Hành Động, Sol thấy gì.', body = 'Mình là Khang. Một tuần Hành Động xong. Hôm nay {pronoun} mở Phân tích → Hành Động xem trung bình tuần vs baseline. Giảm cũng tốt, ngang cũng tốt — quan trọng là {pronoun} đã LÀM, không chỉ NGHĨ. Mình tự hào. — Khang Sol' WHERE id = 'cmotefgxl000d10c6rjbpopom';
UPDATE "ContentItem" SET title = 'Day 15 Hành Động — identity prep.', body = 'Câu hỏi cho hôm nay: {pronoun} là ai khi không hút? Không phải "người đang cố bỏ" — mà "người không hút". Allen Carr nói: identity shift là chuyển dịch lớn nhất. Tối nay viết 1 câu trả lời — Sol sẽ dùng làm anchor.' WHERE id = 'cmotefgxr000e10c6dtjx4t6z';
UPDATE "ContentItem" SET title = 'Day 16 Hành Động — cảnh báo Day 16-21.', body = 'Tuần 3 Hành Động thường khó nhất tâm lý — não bắt đầu phản đối "hệ thống mới". Có cảm giác "thử 1 điếu xem sao" là bình thường. Sol đứng cạnh {pronoun}. Khi cảm giác đó lên, mở chat hỏi Sol — đừng tự đối phó.' WHERE id = 'cmotefgxy000f10c6dl59r9j9';
UPDATE "ContentItem" SET title = 'Day 17 Hành Động — {pronoun} không cô đơn.', body = 'Hôm nay {pronoun} có Đội Sol — những người cùng tháng đặt Q-Day. Mở Tổng quan xem họ đang ở phase nào. Không cần nói chuyện — chỉ biết có người đi cùng đã đủ. Sol cũng đang đi.' WHERE id = 'cmotefgy4000g10c6uirj6ddy';
UPDATE "ContentItem" SET title = 'Day 18 Hành Động — cravings 21h tối.', body = 'Cơn thèm đêm thường mạnh hơn ban ngày — cortisol giảm, dopamine baseline thấp, não tìm "cú hích" nhanh. Hack: 21h tắt điện thoại 30 phút, ngâm chân nước ấm 10 phút, lên giường sớm. Cơ thể sẽ thưởng giấc ngủ sâu.' WHERE id = 'cmotefgy9000h10c6bdv2y314';
UPDATE "ContentItem" SET title = 'Day 12 Hành Động — stress không cần thuốc lá.', body = 'Khi stress, não tìm dopamine nhanh — nicotin là đường tắt. Nhưng dopamine có thể đến từ: 5 phút đi bộ, gọi 1 cuộc với người tin tưởng, ngâm chân nước ấm. Hôm nay khi stress lên, thử 1 trong 3 trước khi châm điếu.' WHERE id = 'cmotefgx6000b10c6wbode088';
UPDATE "ContentItem" SET title = '48 giờ — nicotin sạch máu.', body = 'Nicotin có half-life 2 giờ — sau 48 giờ ~99% đã thải qua nước tiểu (NHS). Cái còn lại hôm nay là TÂM LÝ, không phải sinh học.' WHERE id = 'cmoqonhr3000vm0j6lucy7a59';
UPDATE "ContentItem" SET title = 'Áp lực xã hội — chuẩn bị.', body = 'Người rủ thường không ác ý — họ tự bảo vệ thói quen. Câu ngắn "Mình bỏ rồi" hiệu quả hơn giải thích dài. Càng ngắn càng tự nhiên.' WHERE id = 'cmoqonhtz001gm0j6aw0v8h92';
UPDATE "ContentItem" SET title = 'Plan Day 30 — bình thường.', body = 'Day 30 KHÔNG ăn mừng nhậu. Plan: bữa cơm gia đình, đi bộ buổi sáng, gọi 1 người thân. Bình thường = chiến thắng.' WHERE id = 'cmoqonhzh002lm0j6oqo27zgz';
UPDATE "ContentItem" SET title = 'Nhóm “giảm áp lực”', body = '🔁 Nhóm “giảm áp lực”
“Không cần cố. Chỉ cần hiểu.”
“Không phải lúc nào mình cũng cần thuốc.”
“Có những điếu… thật ra không cần.”
“Anh không yếu. Chỉ là chưa quen.”
“Không phải anh không làm được. Chỉ là chưa đúng cách.”' WHERE id = 'cmorf76xu000beefvkedv0tve';
UPDATE "ContentItem" SET title = 'Nhóm “đi tiếp”', body = 'Nhóm “đi tiếp”
“Đi chậm vẫn là đang đi.”
“Một chút mỗi ngày… là đủ.”
“Không cần xa. Chỉ cần khác hôm qua.”
“Chúng ta không quay lại điểm cũ.”
“Anh đang làm tốt hơn anh nghĩ.”' WHERE id = 'cmorf7ppf000ceefvtmoebttf';
UPDATE "ContentItem" SET title = 'Nhóm “chuyển đổi”', body = 'Nhóm “chuyển đổi”
“Anh không còn như trước nữa.”
“Cơ thể anh đang quen với việc ít thuốc hơn.”
“Anh đã dừng lại được rồi – chỉ là chưa tin thôi.”
“Mỗi lần không hút… là một lần thắng.”
“Anh không cần thuốc như anh từng nghĩ.”' WHERE id = 'cmorf8cbr000deefvu2llfrw2';
UPDATE "ContentItem" SET title = 'Day 21 Hành Động — chuẩn bị Q-Day.', body = 'Mình là Khang. Còn 1 tuần là Q-Day. Hôm nay viết ra giấy 3 lý do {pronoun} muốn bỏ — cụ thể, không generic. "Vì con tôi" tốt hơn "vì sức khoẻ". Tối Q-Day {pronoun} sẽ đọc lại. Mình đã viết của mình tối trước Q-Day 2018 — vẫn còn giữ. — Khang Sol' WHERE id = 'cmotefgyq000k10c64hoxeagx';
UPDATE "ContentItem" SET title = 'Day 22 Hành Động — hỏi vợ/người thân.', body = 'Hôm nay làm 1 việc: hỏi 1 người thân (vợ, con, anh chị) câu này: "Tôi sắp Q-Day cuối tuần này — anh/chị mong tôi cam kết gì?". Câu trả lời của họ sẽ là anchor mạnh hơn lý do tự nghĩ. Cam kết với người thật, không với app.' WHERE id = 'cmotefgyv000l10c6xk5ym8je';
UPDATE "ContentItem" SET title = 'Day 23 Hành Động — identity Day 23.', body = 'So với 23 ngày trước, {pronoun} đã thay đổi gì? Có thể khó thấy ngay — nhưng người thân thấy. Hôm nay hỏi 1 người: "Anh/chị thấy tôi tuần này khác gì?" Câu trả lời sẽ làm {pronoun} ngạc nhiên.' WHERE id = 'cmotefgz0000m10c6sob5zcti';
UPDATE "ContentItem" SET title = 'Day 24 Hành Động — 5 ngày nữa Q-Day.', body = 'Còn 5 ngày là Q-Day. Hôm nay quan sát mình kỹ hơn: lúc nào dễ vấp nhất? lúc nào vững nhất? Không cần làm gì — chỉ ghi lại. Tuần sau những lúc khó đó Sol sẽ chuẩn bị Plan B sẵn cho {pronoun}.' WHERE id = 'cmotefgz5000n10c6lf7tdu1j';
UPDATE "ContentItem" SET title = 'Day 25 Hành Động — 3 ngày nữa, chuẩn bị nhà.', body = '3 ngày trước Q-Day — chuẩn bị môi trường. Cuối tuần này: vứt bao thuốc còn lại, gạt tàn, bật lửa. Giặt áo khoác. Báo người trong nhà "thứ 2 tới tôi Q-Day, cần các anh/chị giúp." Môi trường sạch = não dễ chuyển.' WHERE id = 'cmotefgza000o10c6ydhgfs7y';
UPDATE "ContentItem" SET title = 'Day 26 Hành Động — Q-Day T-2.', body = '🎯 Còn 2 ngày là Q-Day. Hôm nay mở Tổng quan — sẽ thấy banner Q-Day countdown. Tối nay đọc lại 3 lý do đã viết Day 21. Mai T-1 — Sol sẽ gửi thư cuối từ Khang. Sẵn sàng chưa?' WHERE id = 'cmotefgzg000p10c6lbi1kv61';
UPDATE "ContentItem" SET title = 'Day 27 Hành Động — đêm trước Q-Day.', body = 'Mình là Khang. Đêm cuối Phase Hành Động. Tối nay ngồi yên 10 phút. Đọc lại 3 lý do. Viết 1 lá thư ngắn cho {pronoun} của ngày mai — "Khi {pronoun} đọc thư này, {pronoun} đã không hút 24 giờ." Mai bấm "Tôi cam kết" — đồng hồ tự do của {pronoun} bắt đầu chạy. Mình sẽ ở đó. — Khang Sol' WHERE id = 'cmotefgzl000q10c6r6jiq84x';
UPDATE "ContentItem" SET title = 'Day 28 — Hôm nay là Q-Day.', body = 'Mình là Khang. Hôm nay là Q-Day của {pronoun}. Mở Tổng quan — bấm "Tôi cam kết — bật đồng hồ tự do". Sau khi bấm, đồng hồ của {pronoun} bắt đầu đếm. Đội Sol sẽ thấy: "Một đồng đội vừa Q-Day". 24 giờ tới là 24 giờ khó nhất sinh học — mình đã đi chính con đường này. Sol bên {pronoun}. — Khang Sol' WHERE id = 'cmotefgzq000r10c6gugto504';
UPDATE "ContentItem" SET title = 'Day 59 Tái Thiết — 30 ngày không hút.', body = 'Mình là Khang. {pronoun} vừa qua 30 ngày từ Q-Day. Đây không phải "30 ngày course" — đây là 30 ngày {pronoun} đã sống thật khác. Body đã hồi đáng kể: phổi 10% chức năng (NHS), receptor giảm 60%. Bắt đầu Phase 4 — Sol giảm dần, {pronoun} bắt đầu tự chủ. — Khang Sol' WHERE id = 'cmotefgzv000s10c6suldmrh2';
UPDATE "ContentItem" SET title = 'Day 20 Hành Động — 1 điếu lúc nhậu.', body = 'Tối nay nhậu? Quy tắc 1 điếu: nếu lỡ hút, KHÔNG có "hôm nay vỡ rồi, mai bắt đầu lại". Ghi vào Sol ngay tối đó. Đừng để 1 điếu thành 1 bao. Bấm "Đã hút" trong logger — Sol không phán xét, Sol giúp {pronoun} thấy pattern.' WHERE id = 'cmotefgyk000j10c6ni1awd9e';
UPDATE "ContentItem" SET title = 'Day 2, {pronoun}: Đỉnh thèm hôm nay.', body = 'Hôm nay nicotin đã rời máu, nhưng não chưa thích nghi. Cơn thèm là dấu hiệu não đang HỌC. Mỗi sóng vượt = não bớt phụ thuộc. Mình đã đi qua chính ngày này. — Khang Sol' WHERE id = 'cmoqonhmh0001m0j6b3ah110e';
UPDATE "ContentItem" SET title = 'Day 74 Tái Thiết — body 80% (CDC).', body = 'Theo CDC, sau 60+ ngày không hút, phổi đã hồi 80% chức năng cho người dưới 50, 60% cho người trên 50. Nguy cơ đột quỵ giảm về mức người chưa bao giờ hút. Khứu giác, vị giác sắc hơn nhiều so với 2 tháng trước — {pronoun} có cảm thấy không?' WHERE id = 'cmotefh0p000x10c6rt2bxspa';
UPDATE "ContentItem" SET title = 'Day 77 Tái Thiết — 1 năm sau {pronoun} là ai?', body = 'Mình là Khang. Câu hỏi không nhỏ: 1 năm sau, {pronoun} muốn là người thế nào? Không hút thuốc là 1 phần — còn gì nữa? Tập thể dục? Chạy 5km? Học tiếng Anh? Q-Day mở cửa cho những thay đổi khác. Tối nay viết 1 mục tiêu mới — Sol sẽ track cùng. — Khang Sol' WHERE id = 'cmotefh0u000y10c6sxaeldli';
UPDATE "ContentItem" SET title = 'Day 80 Tái Thiết — vì điều gì {pronoun} không hút?', body = 'Mình là Khang. Day 21 {pronoun} viết 3 lý do. Hôm nay đọc lại — cảm giác sao? Lý do tốt nhất thường là "vì người khác" — vợ, con, ba mẹ. Não cá nhân ích kỷ, nhưng não vì người khác mạnh hơn. Mình bỏ vì cu Tí. Vẫn còn lý do đó. — Khang Sol' WHERE id = 'cmotefh11000z10c6m1h5r0q8';
UPDATE "ContentItem" SET title = 'Day 83 Tái Thiết — Sol giảm dần.', body = 'Sol bắt đầu giảm tần suất nhắc — autonomy mode. Từ giờ {pronoun} sẽ thấy ít message hơn. Đó không phải Sol bỏ {pronoun} — đó là tin tưởng. Khi cần, mở chat hỏi Sol như bạn cũ. Sol vẫn ở đây.' WHERE id = 'cmotefh16001010c6a90t9ofi';
UPDATE "ContentItem" SET title = 'Day 86 Tái Thiết — còn 2 ngày tốt nghiệp.', body = 'Mình là Khang. Còn 2 ngày là Day 88 — tốt nghiệp Phase 4. {pronoun} thành Đại Sứ Sol. Ngày 88 Sol sẽ gửi 1 hồ sơ PDF tổng kết hành trình của {pronoun} — giữ làm kỷ niệm. {pronoun} đã đi rất xa. Mình tự hào. Hẹn {pronoun} ở Phase 5. — Khang Sol' WHERE id = 'cmotefh1c001110c6nbtkd1as';
UPDATE "ContentItem" SET title = 'Tiền tiết kiệm: tại sao quan trọng não.', body = 'Não không tự nhiên thấy "không hút" là phần thưởng — vì không có dopamine spike. Tiền tiết kiệm thành mục tiêu cụ thể (cốc kính mới, bữa tối với vợ) = não LẠI thấy phần thưởng → loop dopamine mới hình thành. Đây là lý do gamification work cho 45+ Việt.' WHERE id = 'cmotfsuyk000i6usy54w4kvll';
UPDATE "ContentItem" SET title = 'Đêm 18 — 21h thèm.', body = 'Đây chính là giờ Sol cảnh báo sáng — craving 21h. Nếu lúc này {pronoun} thấy thèm: tắt điện thoại, ngâm chân nước ấm, lên giường. 30 phút nữa cơn sẽ qua. Sol biết — Sol đo nhịp này nhiều người.' WHERE id = 'cmotg5j8a000h8qmdryvopoy7';
UPDATE "ContentItem" SET title = 'Đêm 19 — tiền dồn lại.', body = 'Tiền {pronoun} không hút hôm nay đang dồn vào tiết kiệm. Tối nay tưởng tượng: dùng nó cho ai? Một bữa tối cuối tuần với vợ? Một thứ cho con? Hình ảnh cụ thể giúp não giữ vững.' WHERE id = 'cmotg5j8f000i8qmd497nc7x2';
UPDATE "ContentItem" SET title = 'Day 62 Tái Thiết — identity, {pronoun} là gì bây giờ?', body = 'Mình là Khang. Allen Carr nói: ngày {pronoun} dừng nói "tôi đang cố bỏ" và bắt đầu nói "tôi không hút" — đó là ngày identity đổi xong. {pronoun} đã ở đâu trong câu chuyện đó? Tối nay viết 1 câu mô tả {pronoun} bây giờ — không có "đã từng hút" trong đó. — Khang Sol' WHERE id = 'cmotefh01000t10c6su7tnu7m';
UPDATE "ContentItem" SET title = 'Day 65 Tái Thiết — khi thấy ai khác hút.', body = 'Hôm nay {pronoun} có thấy ai đang hút (đồng nghiệp, hàng xóm, bạn bè)? Phản ứng của {pronoun} là gì? Nếu thấy "thèm" — bình thường. Nếu thấy "không liên quan đến tôi" — identity đã chuyển. Sol mong {pronoun} đến cảm giác thứ 2.' WHERE id = 'cmotefh06000u10c6ysylus1b';
UPDATE "ContentItem" SET title = 'Day 68 Tái Thiết — Day 75 trap.', body = 'Mình là Khang. Cảnh báo trước: tuần tới (Day 70-75) một số người vấp lại — vì cảm giác "an toàn rồi". Đây là trap. Não muốn thử "1 điếu xem có còn nghiện không" — và phát hiện CÒN. Đừng thử. {pronoun} đã đi rất xa. Mình đã thấy người vấp ở Day 73 — và họ kéo lại được, nhưng đau. — Khang Sol' WHERE id = 'cmotefh0c000v10c6ar4y215f';
UPDATE "ContentItem" SET title = 'Day 71 Tái Thiết — Đại Sứ Sol.', body = '{pronoun} sắp thành Đại Sứ Sol (Day 89+). Đại Sứ không phải badge — đó là người chia sẻ với newbie. Sol gợi: tuần này thử nói 1 câu với 1 người đang muốn cai. Không cần lý thuyết — chỉ kể {pronoun} đã đi sao. Cách giữ vững nhất là giúp người khác bắt đầu.' WHERE id = 'cmotefh0j000w10c6o34k7ped';
UPDATE "ContentItem" SET title = 'Đêm 20 — nếu lỡ nhậu.', body = 'Tối nay {pronoun} có nhậu không? Nếu lỡ hút 1-2 điếu — không sao. Quy tắc: ghi vào logger ngay. Đừng để 1 điếu thành "đêm vỡ". Đêm nay vẫn ngủ. Mai thức dậy là ngày mới.' WHERE id = 'cmotg5j8k000j8qmd1hjj13ht';
UPDATE "ContentItem" SET title = 'Day 11 Hành Động — giảm 1 điếu = Sol đo được.', body = 'So với baseline tuần Nhận Thức, hôm qua {pronoun} hút ít hơn mấy điếu? Nếu chưa giảm — không sao, mai khác. Nếu giảm 1-2 điếu — Sol mừng. Đường đi giảm dần là đường zigzag, không phải đường thẳng.' WHERE id = 'cmotefgx0000a10c6ciegl3wk';
UPDATE "ContentItem" SET title = 'Day 19 Hành Động — tiền tiết kiệm dùng gì?', body = 'Mở Tổng quan → Tiết kiệm. Số tiền {pronoun} đang giữ lại. Hôm nay nghĩ: dùng nó cho gì? Một bữa tối với vợ? Một cây kính mới? Một đồ chơi cho con? Đặt mục tiêu cụ thể — não sẽ thấy phần thưởng, không chỉ "không hút".' WHERE id = 'cmotefgyf000i10c6crw4cqwo';
UPDATE "ContentItem" SET title = 'Vì sao não cần nicotin sau 20 năm hút?', body = 'Mỗi điếu thuốc kích hoạt receptor nicotinic acetylcholine (nAChR) trong não → thải dopamine. Sau hàng nghìn lần, não tăng số receptor để "bù trừ" → thiếu nicotin = thiếu dopamine = cảm giác bứt rứt. Đây là sinh lý, không phải ý chí yếu. Hiểu được = hết tự trách (Brody 2006).' WHERE id = 'cmotfsuw700006usypkhjtwks';
UPDATE "ContentItem" SET title = 'Trigger là gì — về mặt thần kinh?', body = 'Trigger là "bộ kích hoạt" pattern hút thuốc đã ghi vào basal ganglia — vùng não điều khiển thói quen tự động. Vd thấy bao thuốc → tay tự châm. Quan sát trigger = đưa pattern từ vô thức lên ý thức. Khi {pronoun} ý thức được, não có thể "ngắt mạch" (Graybiel 2008).' WHERE id = 'cmotfsuwd00016usytjb970bp';
UPDATE "ContentItem" SET title = 'Dopamine không phải "chất hạnh phúc".', body = 'Hiểu lầm phổ biến: dopamine = hạnh phúc. Sai. Dopamine là "chất ham muốn" — não dùng để học "việc nào đáng làm lại". Nicotin hack hệ thống này → não nghĩ thuốc đáng hơn các nguồn dopamine khác (gia đình, đi bộ, ăn ngon). Khi cai, não phải "học lại" giá trị thật.' WHERE id = 'cmotfsuwi00026usyqd82dbai';
UPDATE "ContentItem" SET title = 'Cơn thèm kéo dài bao lâu?', body = 'Một cơn thèm cấp thường đỉnh trong 90-180 giây, rồi giảm dần. Sau 8-10 phút, 80% cơn thèm đã tự tắt nếu không hút (Hughes 2007). Đây là lý do "delay 10 phút" hoạt động — không phải vì ý chí, vì sinh học. Cứ đếm hơi thở 10 phút.' WHERE id = 'cmotfsuwm00036usy4gu18k5z';
UPDATE "ContentItem" SET title = '5 nhóm trigger chính của người Việt 45+.', body = 'Theo dữ liệu Sol thu thập + WHO Vietnam 2019: STRESS (38%), EATING sau cơm (27%), SOCIAL nhậu (18%), IDLE rảnh (12%), OTHER (5%). {pronoun} thuộc nhóm nào? Mở /analytics → 🌱 Nhận Thức xem trigger phổ biến của mình.' WHERE id = 'cmotfsuwr00046usy3z6qdi4e';
UPDATE "ContentItem" SET title = 'Cortisol sáng & cơn thèm điếu đầu.', body = 'Sáng dậy, cortisol cao đỉnh trong 30-45 phút (cortisol awakening response). Não tìm dopamine để "đối phó" — điếu đầu sáng là phản xạ. Hack: trước điếu đầu, uống 1 cốc nước lạnh + đi bộ 5 phút. Cortisol sẽ rút bằng cách khác.' WHERE id = 'cmotfsuwx00056usy111djfil';
UPDATE "ContentItem" SET title = 'Baseline 7 ngày — Sol đã đo gì.', body = 'Tuần này Sol đã ghi nhận: số điếu/ngày trung bình ({pronoun} mở /analytics xem), peak hour, top trigger. Đây là baseline khoa học để Sol biết Phase 2 nên giảm bao nhiêu, Plan B nào ưu tiên. Không có baseline = bay mù.' WHERE id = 'cmotfsux200066usyu4y7ei3f';
UPDATE "ContentItem" SET title = 'Vì sao "delay 10 phút" hiệu quả?', body = 'Não có 2 hệ: limbic (impulsive, "tôi muốn ngay") và prefrontal cortex (planning, "tôi nghĩ kỹ"). Khi craving lên, limbic thắng. Đếm 10 hơi thở chậm → kích hoạt prefrontal → "ngắt mạch" tự động. 10 phút sau, limbic hạ → quyết định ý thức.' WHERE id = 'cmotfsux600076usyqrj4d30l';
UPDATE "ContentItem" SET title = 'Habit loop: Cue → Routine → Reward.', body = 'Mỗi thói quen có 3 phần (Duhigg 2012). Cue = trigger. Routine = hành động (hút thuốc). Reward = dopamine spike. Để phá loop, không thể bỏ Cue (vẫn có stress) — phải đổi Routine. Plan B = routine mới cho cùng cue. Phần thưởng đến chậm hơn nhưng thật hơn.' WHERE id = 'cmotfsuxa00086usyyxa8kpk0';
UPDATE "ContentItem" SET title = 'Stress → cortisol → nicotin: vòng nguy hiểm.', body = 'Stress tăng cortisol → não tìm dopamine nhanh → nicotin là đường tắt. Sau hút, dopamine tăng nhưng cortisol cũng tăng (gấp 1.4x bình thường). Kết quả: stress càng nhiều, hút càng nhiều, stress càng nặng. Cách phá: 5 phút thiền/đi bộ → cortisol giảm 26%, không cần nicotin (Pascoe 2017).' WHERE id = 'cmotfsuxe00096usyh1r8sqii';
UPDATE "ContentItem" SET title = 'Giảm 1 điếu/ngày = ý nghĩa gì?', body = 'Không phải con số đơn lẻ — là dấu hiệu não đã "tách" được 1 trigger. Mỗi lần delay/skip thành công, kết nối neural mới được hình thành. Sau ~21 lần lặp lại, kết nối đó vững (Lally 2010). Vd Day 11 giảm 1 điếu = đã có ~3-5 lần delay thành công tuần qua.' WHERE id = 'cmotfsuxi000a6usyiekdaech';
UPDATE "ContentItem" SET title = 'Đi bộ 5 phút thay nicotin: cơ chế.', body = 'Đi bộ kích thích endorphin (hệ opioid nội sinh) + tăng oxy lên não → tâm trạng cải thiện 12-15% trong 5 phút (Berger 2016). Nicotin chỉ làm "nâng" tạm thời rồi crash. Đi bộ là dopamine bền vững. Thử trước khi tin.' WHERE id = 'cmotfsuxm000b6usydl4tqdc0';
UPDATE "ContentItem" SET title = 'Đánh răng sau cơm: hack neural.', body = 'Vị bạc hà kích hoạt receptor TRPM8 (cảm giác lạnh) → não nhận tín hiệu "miệng đã sạch, không cần thêm". Cộng với bact mãn từ kem đánh răng → flavor profile của thuốc lá tệ hẳn. Nhiều người 45+ nói "không thể hút sau khi đánh răng" — đây là lý do.' WHERE id = 'cmotfsuxr000c6usy49yaypc3';
UPDATE "ContentItem" SET title = 'Day 4: Đêm qua khó ngủ?', body = 'Bình thường — não đang điều chỉnh dopamine. Hôm nay tránh cà phê sau 14h, đi bộ 20 phút trước 18h. Cơ thể sẽ thưởng giấc ngủ sâu đêm nay.' WHERE id = 'cmoqonhmv0003m0j64g3y5mde';
UPDATE "ContentItem" SET title = 'Day 5: Cáu hơn? Bình thường.', body = 'Não nicotin-đói cảm xúc thô hơn 30-40% (Cosgrove). Báo trước người thân. Khi cáu lên — uống nước lạnh, đếm 10 hơi thở chậm. Sóng sẽ rút.' WHERE id = 'cmoqonhn10004m0j601bkm9be';
UPDATE "ContentItem" SET title = 'Day 6: Cuối tuần đầu.', body = 'Cơn thèm tuần đầu chủ yếu là sinh học. Sang tuần 2 là tâm lý. Hôm nay nghỉ — không lên kế hoạch lớn, chỉ qua từng giờ.' WHERE id = 'cmoqonhn80005m0j63dkkksh0';
UPDATE "ContentItem" SET title = 'Day 7: 168 giờ.', body = 'Tuần đầu xong rồi {pronoun}. Hôm nay thưởng cho mình một việc nhỏ — đi bộ 15 phút, uống cà phê chậm, gì cũng được. {pronoun} xứng đáng.' WHERE id = 'cmoqonhnf0006m0j63fxs94jo';
UPDATE "ContentItem" SET title = 'Day 8: Tuần 2 — đầu khác.', body = 'Sinh học đã ổn 80%. Trận chính từ giờ là tâm lý: thói quen ngày, tình huống quen, người quen rủ. Nhận diện 1 tình huống khó hôm nay, prep trước.' WHERE id = 'cmoqonhnl0007m0j6jwap9a6k';
UPDATE "ContentItem" SET title = 'Day 9: Vẫn còn cơn thèm?', body = 'Bình thường — receptor đang giảm. Cơn thèm Day 9 yếu hơn Day 3 ~50%. Mỗi lần qua = não yếu thêm. Đếm số cơn hôm nay, tối kiểm.' WHERE id = 'cmoqonhnr0008m0j63rie9bla';
UPDATE "ContentItem" SET title = 'Day 10: 1/3 chặng.', body = 'Phổi đã sạch lông mao, ho ra đờm nâu là dấu hiệu tốt — phổi tự dọn. Khứu giác hôm nay sắc hơn — thử ngửi cà phê sáng.' WHERE id = 'cmoqonhnw0009m0j6fdnhcsgq';
UPDATE "ContentItem" SET title = 'Day 11: Tim đập chậm hơn.', body = 'Nhịp tim nghỉ giảm ~5-10 bpm so với khi hút (Mayo Clinic). Tim làm việc đỡ hơn. Hôm nay leo cầu thang chậm rãi — cảm nhận sự khác.' WHERE id = 'cmoqonho1000am0j6lx2bqnl5';
UPDATE "ContentItem" SET title = 'Day 12: Tuần hoàn cải thiện.', body = 'Ngón tay, ngón chân ấm hơn. Da bớt xỉn. {pronoun} đã trả lại oxy cho tế bào. Hôm nay ngắm tay mình lúc rảnh.' WHERE id = 'cmoqonho6000bm0j63kazewsm';
UPDATE "ContentItem" SET title = 'Day 13: Mai là Day 14.', body = 'Day 14 là cột mốc receptor giảm 40%. Não bắt đầu coi không-hút là default. Hôm nay sống bình thường — đừng overprepare. Bình thản là thành tựu lớn nhất.' WHERE id = 'cmoqonhoc000cm0j64vuithr0';
UPDATE "ContentItem" SET title = 'Day 15: Nửa chặng.', body = '15 ngày sạch — đa số người không tin được làm được. Nhưng đây cũng là điểm risky: tự tin có thể dẫn tới "thử 1 điếu xem". Đừng. Não chưa hoàn toàn reset.' WHERE id = 'cmoqonhom000em0j6398mwmtd';
UPDATE "ContentItem" SET title = 'Day 16: Tăng cân?', body = 'Bình thường — vi sinh đường ruột phục hồi, hấp thụ tốt hơn. Trung bình tăng 2-4kg trong 30 ngày (NHS). Đừng diet ngay — cơ thể đang sửa chữa.' WHERE id = 'cmoqonhor000fm0j6rdty54qb';
UPDATE "ContentItem" SET title = 'Day 17: Nhậu cuối tuần?', body = 'Rượu hạ guard, dopamine drop sâu — cơn thèm trở lại mạnh. Nếu phải đi: gọi nước trước, ngồi xa người hút, có cớ về sớm.' WHERE id = 'cmoqonhow000gm0j6ae6n54u6';
UPDATE "ContentItem" SET title = 'Day 18: Mơ hút thuốc?', body = 'Bình thường — não REM đang xử lý ký ức. Mơ KHÔNG phải dấu hiệu thèm thật. Nhiều người mơ rõ tới Day 30+. Tỉnh dậy là bình thường lại.' WHERE id = 'cmoqonhp1000hm0j6krq6fyhf';
UPDATE "ContentItem" SET title = 'Day 19: Ho dai dẳng?', body = 'Lông mao phổi đang mọc lại — đẩy đờm tích tụ ra. Ho nhiều 1-3 tuần là tốt. Nếu ho ra máu hoặc khó thở dữ dội — đi khám.' WHERE id = 'cmoqonhp6000im0j6gw5mwwqf';
UPDATE "ContentItem" SET title = 'Day 20: Lo lắng vô cớ?', body = 'Não đang reset baseline cảm xúc. 3-5 ngày sẽ qua. Đi bộ ngoài trời 20 phút giúp. Không cần điều trị — đây là quá trình.' WHERE id = 'cmoqonhpb000jm0j68iqjix4d';
UPDATE "ContentItem" SET title = 'Day 21: 3 TUẦN — thói quen mới.', body = '21 ngày là khung Lally 2010 cho thói quen mới hình thành. Não đã viết xong "không hút" thành default. Từ giờ là duy trì, không phải nỗ lực.' WHERE id = 'cmoqonhph000km0j67batauve';
UPDATE "ContentItem" SET title = 'Day 22: {pronoun} không hút thuốc.', body = 'Câu này. {pronoun} không nói "đang cai" hay "đang cố" — {pronoun} không hút thuốc. Identity shift. Nói ra miệng 1 lần hôm nay.' WHERE id = 'cmoqonhpm000lm0j6nljg0ht2';
UPDATE "ContentItem" SET title = 'Day 1, {pronoun}: Hôm nay không hút.', body = 'Lý do {pronoun} bắt đầu: {topReason}. Lúc khó nhất, nhớ câu này. 24 giờ đầu là 24 giờ khó nhất sinh học. Mình đi với {pronoun}. — Khang Sol' WHERE id = 'cmoqonhm00000m0j6h4axdlp7';
UPDATE "ContentItem" SET title = 'Day 14: 2 TUẦN — receptor giảm 40%.', body = '{greet}. Hôm nay receptor nicotine não giảm 40%. {topReason} — 14 ngày rồi {pronoun} vẫn giữ. Cơn thèm tâm lý là mặt trận chính từ giờ. Mình gửi {pronoun} voice Day 14.' WHERE id = 'cmoqonhoh000dm0j6dg3n07kb';
UPDATE "ContentItem" SET title = 'Day 3 — bức tường.', body = 'Triệu chứng đỉnh điểm: cáu, mất ngủ, đói. Đây là "bức tường" Hughes 2007. Vượt được Day 3, tỷ lệ thành công 30 ngày tăng 3x. Hôm nay {pronoun} có Plan B chưa?' WHERE id = 'cmoqonhmo0002m0j6hkga5dca';
UPDATE "ContentItem" SET title = 'Day 27: Sắp 30 ngày.', body = '3 ngày nữa tới cột mốc. Đừng overprepare. Hôm nay sống bình thường — vì bình thường BÂY GIỜ là không hút. Đó là chiến thắng.' WHERE id = 'cmoqonhqe000qm0j6wr1gz34d';
UPDATE "ContentItem" SET title = 'Day 28: Sắp xong.', body = 'Điều khó nhất không phải bỏ — mà giữ. {pronoun} đã giữ 28 ngày. Tự hào nhỏ thôi, không phô trương. Phòng vệ vẫn cần — đời còn dài.' WHERE id = 'cmoqonhqk000rm0j6vp790g12';
UPDATE "ContentItem" SET title = '8 giờ — CO máu giảm 50%.', body = 'Sau 8 giờ không hút, carbon monoxide trong máu giảm một nửa (CDC). Hồng cầu chở oxy hiệu quả hơn rồi {pronoun}.' WHERE id = 'cmoqonhqy000um0j6x7ippcix';
UPDATE "ContentItem" SET title = '72 giờ — phổi bắt đầu mở.', body = 'Ống phế quản giãn ra sau 72 giờ. Hô hấp dễ hơn. Đây cũng là lúc cơn thèm sinh học đỉnh điểm — vì receptor não chưa kịp giảm (Hughes 2007).' WHERE id = 'cmoqonhr9000wm0j6erhoxuq0';
UPDATE "ContentItem" SET title = 'Mất ngủ — tại sao?', body = 'Nicotin là chất kích thích. Bỏ rồi, não phải tự sản xuất dopamine — quá trình mất 1-2 tuần. Đêm là lúc não điều chỉnh nhiều nhất → mất ngủ.' WHERE id = 'cmoqonhrf000xm0j6k9nrelag';
UPDATE "ContentItem" SET title = 'Cáu kỉnh — có thật.', body = 'Não nicotin-đói cảm xúc thô hơn 30-40% (Cosgrove 2009). Đây không phải tính cách {pronoun} — là sinh học tạm thời. 1-2 tuần sẽ về.' WHERE id = 'cmoqonhrk000ym0j6wu6f53rt';
UPDATE "ContentItem" SET title = 'Khứu giác phục hồi.', body = 'Mũi đã sạch hắc ín. Nụ khứu giác bắt đầu mọc lại. Hôm nay {pronoun} có thể ngửi rõ hơn — thử ngửi tách cà phê chậm.' WHERE id = 'cmoqonhrp000zm0j6yoyvrdhm';
UPDATE "ContentItem" SET title = '1 tuần — tỷ lệ thành công.', body = 'Người vượt được tuần đầu, tỷ lệ giữ 30 ngày là 60% (Hughes 2007). {pronoun} đã ở top này rồi.' WHERE id = 'cmoqonhru0010m0j68r7ed1wd';
UPDATE "ContentItem" SET title = 'Receptor — sao não đói?', body = 'Nicotin chiếm receptor acetylcholine não. Bỏ → receptor "đòi". Mỗi lần không cấp, não giảm receptor dần. 14 ngày giảm 40% (Brody 2006).' WHERE id = 'cmoqonhry0011m0j6cszolel3';
UPDATE "ContentItem" SET title = 'Ho ra đờm nâu — tốt.', body = 'Lông mao phổi đang mọc lại, đẩy đờm tích tụ 25 năm ra. Có thể kéo dài 1-3 tuần. Đây là dọn nhà, không phải bệnh.' WHERE id = 'cmoqonhs30012m0j6epdxynks';
UPDATE "ContentItem" SET title = 'Tuần hoàn cải thiện.', body = 'Sau 2-12 tuần, lưu lượng máu tăng đáng kể (Mayo Clinic). Ngón tay ấm hơn, sẹo lành nhanh hơn, da đỡ xỉn. Đó là máu trở lại.' WHERE id = 'cmoqonhs80013m0j6vg7o1xlm';
UPDATE "ContentItem" SET title = 'Tim đập chậm hơn.', body = 'Nhịp tim nghỉ giảm 5-10 bpm so với khi hút (Mayo Clinic). Tim đỡ làm việc, kéo dài tuổi thọ ~3-5 năm với người cai 50+.' WHERE id = 'cmoqonhsd0014m0j6pirzh298';
UPDATE "ContentItem" SET title = 'Vi sinh ruột — và tăng cân.', body = 'Nicotin ức chế vi sinh đường ruột. Bỏ → ruột phục hồi, hấp thụ tốt → tăng cân tự nhiên 2-4kg (NHS). Đừng diet — ăn uống lành mạnh là đủ.' WHERE id = 'cmoqonhsi0015m0j6izkufxn6';
UPDATE "ContentItem" SET title = 'Dopamine baseline.', body = 'Não đang sửa lại "thước đo vui". Trong 2-3 tuần, cảm giác vui có thể nhạt — gọi là anhedonia. Bình thường, có sẽ qua.' WHERE id = 'cmoqonhsn0016m0j6ztwa6hor';
UPDATE "ContentItem" SET title = '2 tuần — receptor giảm 40%.', body = 'Brody 2006 PET scan: sau 14 ngày, receptor nicotinic não giảm ~40%. Não không còn coi nicotin là default. Đỉnh sinh học đã xa.' WHERE id = 'cmoqonhss0017m0j673070p8g';
UPDATE "ContentItem" SET title = 'Nửa chặng — thống kê.', body = 'Người vượt 14 ngày giữ được 30 ngày: ~75% (Hughes 2007). {pronoun} đang ở đoạn dễ hơn. Nguy cơ giờ là tự tin quá mức.' WHERE id = 'cmoqonhsx0018m0j6l588no2u';
UPDATE "ContentItem" SET title = 'Rượu + cai thuốc.', body = 'Rượu giảm GABA → hạ guard. Đồng thời drop dopamine sâu hơn → cơn thèm thuốc trở lại mạnh. 1 ly cũng nguy hiểm trong 30 ngày đầu.' WHERE id = 'cmoqonht7001am0j61ijo172h';
UPDATE "ContentItem" SET title = 'Mơ hút thuốc — tại sao?', body = 'REM xử lý ký ức 25 năm hút. Não dọn dẹp, không phải đòi. Mơ rõ tới Day 30-60. Tỉnh dậy bình thường — không phải dấu hiệu thất bại.' WHERE id = 'cmoqonhtb001bm0j60cw94yk8';
UPDATE "ContentItem" SET title = 'Ho dai 3 tuần — bình thường.', body = 'Lông mao phổi mọc lại, đẩy hắc ín ra. Quá trình kéo 2-12 tuần (NHS). Ho có đờm = tốt. Ho ra máu hoặc khó thở = đi khám ngay.' WHERE id = 'cmoqonhtg001cm0j6t1ptvsvi';
UPDATE "ContentItem" SET title = 'Lo âu nhẹ — não đang sửa.', body = 'Stress system não đang reset baseline. 3-5 ngày sẽ qua. Ánh nắng + đi bộ 20 phút giúp regulate cortisol. Không cần thuốc.' WHERE id = 'cmoqonhtl001dm0j6tf0ogm37';
UPDATE "ContentItem" SET title = 'Day 24: Tiền đã tiết kiệm.', body = 'Trung bình ~24 ngày × 25.000đ/gói = 600.000đ. Hôm nay làm gì với số đó? Một bữa ngon, sách hay, gọi xe đỡ vợ. Chuyển dopamine sang chỗ tốt.' WHERE id = 'cmoqonhpz000nm0j64mnm5gv3';
UPDATE "ContentItem" SET title = 'Day 25: Hơi thở dài hơn.', body = 'Phổi đã hồi phục ~10% chức năng. Leo cầu thang đỡ thở dốc. Hôm nay thử hít sâu 5 giây — giữ 2 — thở 7. Phổi mới hơn 25 ngày trước.' WHERE id = 'cmoqonhq4000om0j6v1oabybf';
UPDATE "ContentItem" SET title = 'Day 26: Vị giác sắc hơn.', body = 'Nụ vị giác phục hồi ~80%. Bữa cơm thường ngày tự nhiên ngon hơn. Hôm nay ăn chậm 1 bữa — nếm thật sự.' WHERE id = 'cmoqonhq9000pm0j67a5squj6';
UPDATE "ContentItem" SET title = '25 ngày — phổi 10% hồi phục.', body = 'Theo NHS, sau 1 tháng phổi hồi 10% chức năng. Đến 9 tháng đạt 90%. Cuộc đua dài, từng ngày là 1 bước.' WHERE id = 'cmoqonhu8001im0j6no18w8pg';
UPDATE "ContentItem" SET title = 'Vị giác phục hồi 80%.', body = 'Sau 26 ngày, ~80% nụ vị giác đã sống lại. Bữa cơm vợ nấu ngon hơn 25 năm trước. Đó là phần thưởng sinh học.' WHERE id = 'cmoqonhue001jm0j6rzez2emh';
UPDATE "ContentItem" SET title = 'Cuối tháng — ngủ sâu hơn.', body = 'Não REM cycle ổn định lại. Trung bình ngủ sâu thêm 30-45 phút/đêm so với khi hút (NHS). Sáng dậy đỡ mệt — đó là não nghỉ thật sự.' WHERE id = 'cmoqonhui001km0j6hng6b44g';
UPDATE "ContentItem" SET title = 'Mai là 30 — sao quan trọng?', body = '30 ngày là cột mốc não bộ ổn định cấu trúc mới. Sau Day 30, "không hút" là default — không cần ý chí mỗi ngày nữa. Đó là khác biệt.' WHERE id = 'cmoqonhus001mm0j6yihpam5i';
UPDATE "ContentItem" SET title = 'Sau 30 ngày — life change.', body = 'Theo Doll & Hill BMJ 2004, cai 30+ tuổi giảm 90% nguy cơ ung thư phổi. 30 ngày này là khởi đầu của phần đời mới — không phải đích đến.' WHERE id = 'cmoqonhuw001nm0j6ftxp0m5v';
UPDATE "ContentItem" SET title = 'Cảnh báo: 21h tối nay khó.', body = 'Hầu hết người Việt 45+ có cơn thèm mạnh nhất 19-22h (sau cơm + thư giãn). Tối nay có Plan B chưa? Chuẩn bị: nước lạnh, kẹo bạc hà, đi bộ 5 phút.' WHERE id = 'cmoqonhv1001om0j6ivsjhyt9';
UPDATE "ContentItem" SET title = 'Đêm nay có thể khó ngủ.', body = 'Day 3 não đỉnh điều chỉnh dopamine → khó vào giấc. Tránh cà phê sau 14h. Đọc sách giấy 30 phút trước ngủ. Thở 4-7-8 nếu trằn trọc.' WHERE id = 'cmoqonhva001qm0j6paaglsgx';
UPDATE "ContentItem" SET title = 'Tự tin giả từ hôm nay.', body = '2 tuần sạch — não bắt đầu nói "thử 1 điếu xem". Cảnh báo trước: 1 điếu = relapse 80% trong 7 ngày tới (Cosgrove). Đừng đùa với receptor.' WHERE id = 'cmoqonhvp001tm0j6gl7g2e0g';
UPDATE "ContentItem" SET title = 'Viết 3 lý do.', body = 'Mở Exercise Card. Viết 3 lý do {pronoun} bỏ thuốc — câu ngắn, từ trái tim. Đây sẽ là Plan B của {pronoun} 30 ngày tới.' WHERE id = 'cmoqonhvy001vm0j607j6x1hg';
UPDATE "ContentItem" SET title = 'Thở 4-7-8.', body = 'Khi thèm: hít 4 giây, giữ 7 giây, thở 8 giây. Lặp 4 lần. Cơn thèm trung bình kéo 3-5 phút — bài này chiếm 4 phút.' WHERE id = 'cmoqonhw2001wm0j684jx8a88';
UPDATE "ContentItem" SET title = 'Liệt kê 5 trigger.', body = 'Tình huống nào hay rủ {pronoun} hút? Sau cơm? Cà phê? Nhậu? Stress? Liệt kê 5 cái lớn nhất. Biết rõ = phòng vệ được.' WHERE id = 'cmoqonhw7001xm0j63560rw1v';
UPDATE "ContentItem" SET title = 'Đi bộ 10 phút.', body = 'Ngoài trời. Không điện thoại. Chỉ thở + nhìn. Đi bộ giảm cortisol 25-30% (Stanford). Đêm nay sẽ ngủ ngon hơn.' WHERE id = 'cmoqonhwc001ym0j6fjnf20xf';
UPDATE "ContentItem" SET title = 'Note 1 thứ tốt.', body = 'Hôm nay {pronoun} thấy 1 điều tốt nhất trong người là gì? Hơi thở dài hơn? Da đỡ xám? Note 1 câu — không cần dài.' WHERE id = 'cmoqonhwo0020m0j6j1dq6843';
UPDATE "ContentItem" SET title = 'Tự thưởng nhỏ.', body = '1 tuần xong. Tự mua/làm gì thưởng cho mình? Không phải bữa nhậu — gì khác. Sách, áo, hoa, gọi xe đỡ vợ. Note xuống.' WHERE id = 'cmoqonhws0021m0j6ogmv9h7x';
UPDATE "ContentItem" SET title = 'Mạng người hỗ trợ.', body = 'Ai trong cuộc sống biết {pronoun} đang bỏ? Liệt kê 3 người. Họ là phòng tuyến — ngày khó nhất gọi 1 người.' WHERE id = 'cmoqonhwx0022m0j6lz6uhndu';
UPDATE "ContentItem" SET title = 'Đếm cơn thèm.', body = 'Hôm nay đếm bao nhiêu cơn thèm. Nhiều/ít không quan trọng — đếm là thấy não đang yếu đi. Note số ở đâu đó.' WHERE id = 'cmoqonhx20023m0j680urivz9';
UPDATE "ContentItem" SET title = 'Hít thật sâu — cảm phổi.', body = 'Đứng thẳng. Hít vào 5 giây, đầy bụng. Giữ 2. Thở ra 7 giây. Lặp 5 lần. Phổi 25 năm cũ giờ đang sửa.' WHERE id = 'cmoqonhx60024m0j6yjoymol0';
UPDATE "ContentItem" SET title = 'Leo cầu thang chậm.', body = '1 tầng đi lên — đếm số nhịp tim cuối. Sau 11 ngày tim chậm hơn. Mai làm lại — sẽ có số khác.' WHERE id = 'cmoqonhxb0025m0j66ospgw4t';
UPDATE "ContentItem" SET title = 'Ngắm tay mình.', body = 'Đặt 2 tay trên bàn. Quan sát 1 phút — màu, ấm, tĩnh mạch. {pronoun} đã trả lại oxy cho bàn tay. Cảm nhận sự sống lại.' WHERE id = 'cmoqonhxg0026m0j6i2hv8u83';
UPDATE "ContentItem" SET title = 'Thư cho mình Day 14.', body = 'Viết 3-5 câu cho {pronoun} hôm nay. Mai đọc lại. Đây là chứng cứ {pronoun} đã ở đây.' WHERE id = 'cmoqonhxl0027m0j694a7pbf6';
UPDATE "ContentItem" SET title = 'Identity > willpower.', body = 'Người nói "tôi đang bỏ" relapse cao hơn người nói "tôi không hút thuốc" 2x (James Clear). Định nghĩa lại bản thân → não follow.' WHERE id = 'cmoqonhtu001fm0j6g08pjk9f';
UPDATE "ContentItem" SET title = 'Tiền tiết kiệm — và dopamine.', body = 'Mỗi tuần ~175.000đ. Chuyển sang chi tiêu mang lại dopamine lành mạnh: cuốn sách, bữa ngon, quà cho người thân. Não learn pattern mới.' WHERE id = 'cmoqonhu4001hm0j68vvwxr1m';
UPDATE "ContentItem" SET title = 'Note giấc mơ.', body = 'Đêm qua mơ hút? Note 1 dòng. Mơ là não đang dọn ký ức 25 năm. Tỉnh dậy bình thường = thắng.' WHERE id = 'cmoqonhya002cm0j6cn0rwrbj';
UPDATE "ContentItem" SET title = 'Dọn 1 ngăn tủ.', body = 'Tìm bao thuốc cũ, bật lửa, gạt tàn — bỏ hết. Hành động vật lý giúp não accept "không hút" thật. 5 phút.' WHERE id = 'cmoqonhye002dm0j6d2ish2wa';
UPDATE "ContentItem" SET title = 'Đi bộ 20 phút ngoài trời.', body = 'Ánh nắng + vận động giảm cortisol, tăng serotonin. Lo âu vô cớ Day 20 sẽ giảm rõ rệt sau 20 phút.' WHERE id = 'cmoqonhyj002em0j6zqlbvs2v';
UPDATE "ContentItem" SET title = 'Ăn mừng 21 ngày — nhỏ.', body = 'Tự thưởng món ăn mình thích — KHÔNG phải đi nhậu. Bữa cơm chậm rãi, nếm thật sự. Vị giác đã 80% rồi.' WHERE id = 'cmoqonhyo002fm0j68c67kezp';
UPDATE "ContentItem" SET title = 'Nói: "Tôi không hút thuốc".', body = 'Nói ra miệng 1 lần. Trước gương, hoặc với người thân. Định nghĩa lại bản thân — não follow.' WHERE id = 'cmoqonhyt002gm0j6bsfjkrhh';
UPDATE "ContentItem" SET title = 'Practice từ chối.', body = 'Nếu ai rủ — câu ngắn nào {pronoun} sẽ dùng? "Mình bỏ rồi." Tập nói trong đầu 3 lần. Lúc thật sẽ tự nhiên.' WHERE id = 'cmoqonhyy002hm0j6ti6iu1gt';
UPDATE "ContentItem" SET title = 'Tính tiền tiết kiệm.', body = '24 ngày × giá 1 gói {pronoun} hay hút = ? Note xuống. Tuần sau dùng số đó cho 1 việc lành mạnh — sách, bữa ngon, quà.' WHERE id = 'cmoqonhz3002im0j6lms6vbku';
UPDATE "ContentItem" SET title = 'Hơi thở dài.', body = 'Hít sâu 5 — giữ 2 — thở 7. Lặp 5 lần. Cảm nhận phổi mới. 25 ngày trước không thấy được như hôm nay.' WHERE id = 'cmoqonhz7002jm0j670wy7p7r';
UPDATE "ContentItem" SET title = 'Bữa ăn chậm.', body = '1 bữa hôm nay — ăn chậm. Nhai kỹ. Nếm thật. Nụ vị giác 80% rồi — bữa cơm thường giờ ngon hơn.' WHERE id = 'cmoqonhzc002km0j6vom6mfr8';
UPDATE "ContentItem" SET title = 'Liệt kê 5 thay đổi.', body = 'Note 5 thay đổi {pronoun} thấy trong người 28 ngày qua. Da, hơi thở, ngủ, vị giác, năng lượng. Đây là chứng cứ.' WHERE id = 'cmoqonhzm002mm0j66foeeqr6';
UPDATE "ContentItem" SET title = 'Đọc lại thư Day 13.', body = '{pronoun} viết thư cho mình Day 13. Hôm nay đọc lại. So với hiện tại — khoảng cách đó là 16 ngày kiên trì.' WHERE id = 'cmoqonhzt002nm0j6zmrns2xi';
UPDATE "ContentItem" SET title = 'Viết Day 60 plan.', body = '30 ngày KHÔNG phải đích — là cột mốc. Viết 3 dòng cho {pronoun} của Day 60: muốn giữ thói quen nào? Tránh tình huống nào?' WHERE id = 'cmoqoni00002om0j62goyg4t9';
UPDATE "ContentItem" SET title = 'Đêm Day 2 — đỉnh đang qua.', body = 'Hôm nay là đỉnh sinh học. {pronoun} đã không hút trong cơn thèm nặng nhất. Đó là chiến thắng não — không chỉ ý chí.' WHERE id = 'cmoqoni0a002qm0j66fp1dmwm';
UPDATE "ContentItem" SET title = 'Đêm Day 4.', body = 'Nếu hôm nay khó ngủ — đó là não đang điều chỉnh. Không phải bệnh. Mai vẫn dậy, vẫn không hút. Đó là cái thắng.' WHERE id = 'cmoqoni0l002sm0j6uehid2c1';
UPDATE "ContentItem" SET title = 'Đêm Day 5 — gần xong tuần đầu.', body = 'Cuối tuần đầu là cuối đường khó nhất. Mai là Day 6. Nicotin sạch. Não đang relearn. {pronoun} đang viết lại 25 năm.' WHERE id = 'cmoqoni0q002tm0j6av7ikd1j';
UPDATE "ContentItem" SET title = 'Đêm Day 6.', body = 'Mai là 1 tuần. Hôm nay không cần làm gì đặc biệt — chỉ qua đêm. Đó là phần lớn việc.' WHERE id = 'cmoqoni0w002um0j6v434r4pf';
UPDATE "ContentItem" SET title = 'Đêm Day 7 — 1 tuần kỳ tích.', body = '168 giờ sạch. {pronoun} đã làm điều 9/10 người không. {topReason} — 1 tuần rồi vẫn còn đó. Ngủ ngon — mai sang chương mới.' WHERE id = 'cmoqoni12002vm0j6l99m3fu8';
UPDATE "ContentItem" SET title = 'Đêm Day 8 — tuần 2 bắt đầu.', body = 'Cơ chế khác hẳn tuần 1. Bây giờ là tâm lý, không phải sinh lý. Mạnh đã có, dùng đầu tiếp.' WHERE id = 'cmoqoni17002wm0j67imjui6h';
UPDATE "ContentItem" SET title = 'Đêm Day 9 — bình thản.', body = 'Đêm nay tim đập chậm. Hơi thở sâu. Đó là cơ thể không hút — và nó cảm ơn {pronoun}.' WHERE id = 'cmoqoni1c002xm0j6ksl5d7ji';
UPDATE "ContentItem" SET title = 'Đêm Day 10 — 1/3 chặng.', body = 'Phổi đang dọn 25 năm. Khứu giác đang sống lại. Mỗi đêm ngủ là cơ thể tự sửa. Ngủ ngon nhé.' WHERE id = 'cmoqoni1h002ym0j6vpjo7frm';
UPDATE "ContentItem" SET title = 'Đêm Day 11.', body = 'Tim đập chậm hơn. Tuần hoàn ấm hơn. Những thay đổi nhỏ này gộp lại = thêm 5-10 năm tuổi thọ (Doll & Hill).' WHERE id = 'cmoqoni1m002zm0j60tf5kwvt';
UPDATE "ContentItem" SET title = 'Đêm Day 12.', body = 'Mai gần Day 14. Hôm nay không quan trọng — vẫn không hút. Sự bình thường này là chiến thắng lớn nhất.' WHERE id = 'cmoqoni1q0030m0j6b7anta0j';
UPDATE "ContentItem" SET title = 'Đêm Day 13 — mai là 14.', body = 'Mai là cột mốc receptor giảm 40%. Không cần thức dậy chuẩn bị — chỉ ngủ ngon, mai não sẽ làm việc của nó.' WHERE id = 'cmoqoni1w0031m0j6jempr6ny';
UPDATE "ContentItem" SET title = 'Đêm Day 15 — nửa chặng.', body = 'Đẹp. Nhưng đừng ngủ với "đã xong rồi". Mai vẫn đầy ngày. Phòng vệ giữ — não chưa hoàn toàn reset.' WHERE id = 'cmoqoni260033m0j6urc909l0';
UPDATE "ContentItem" SET title = 'Plan tuần sau.', body = 'Liệt kê 1-2 tình huống risky tuần tới (đám cưới? nhậu công ty?). Plan B trước. Đừng để bị surprise.' WHERE id = 'cmoqonhxv0029m0j6m5m3egrz';
UPDATE "ContentItem" SET title = 'Cân nhanh.', body = 'Cân hôm nay. Note. Trung bình tăng 2-4kg trong 30 ngày là bình thường. Đừng diet — chỉ ăn rau nhiều hơn 1 chút.' WHERE id = 'cmoqonhxz002am0j66fa9vpco';
UPDATE "ContentItem" SET title = 'Plan đi tiệc.', body = 'Sắp có tiệc/nhậu? Plan: 1 chai nước trước, ngồi xa người hút, cớ về sớm. Hoặc skip — không ai để ý đâu.' WHERE id = 'cmoqonhy4002bm0j6hndo95p5';
UPDATE "ContentItem" SET title = 'Đêm Day 22 — identity mới.', body = '"Tôi không hút thuốc" — câu này đêm nay đã đúng. Không "đang cai" — KHÔNG hút. Thời gian quá khứ. Ngủ với điều đó.' WHERE id = 'cmoqoni35003am0j6oflwhfj8';
UPDATE "ContentItem" SET title = 'Đêm Day 23.', body = 'Hôm nay nếu có ai rủ và {pronoun} nói "không" — đêm nay ngủ với chiến thắng nhỏ. Mỗi lần "không" là 1 lớp não yếu thêm.' WHERE id = 'cmoqoni39003bm0j6tw36zhl2';
UPDATE "ContentItem" SET title = 'Đêm Day 24.', body = '~600.000đ tiết kiệm. Sức khoẻ cơ thể không đo được bằng tiền. Cộng cả 2 — {pronoun} đã thắng lớn 24 ngày.' WHERE id = 'cmoqoni3e003cm0j6zg3zz1wr';
UPDATE "ContentItem" SET title = 'Đêm Day 25.', body = 'Phổi đã hồi 10% chức năng. Cơ thể đang đua thời gian. Mỗi đêm ngủ = 1 vòng đua thắng.' WHERE id = 'cmoqoni3j003dm0j6r2jzumns';
UPDATE "ContentItem" SET title = 'Đêm Day 26.', body = 'Bữa cơm tối nay — vị giác có ngon hơn đầu tháng không? Đó là hồi phục thật. Ngủ ngon.' WHERE id = 'cmoqoni3n003em0j6uohiwyqn';
UPDATE "ContentItem" SET title = 'Đêm Day 27 — sắp 30.', body = '3 đêm nữa. Đừng overthink. Đêm nay sống bình thường — vì bình thường giờ là không hút. Đó là tất cả.' WHERE id = 'cmoqoni3s003fm0j62ty41nsu';
UPDATE "ContentItem" SET title = 'Đêm Day 28.', body = '2 đêm nữa. Cảnh báo: đừng nhậu mừng. 1 điếu mừng = quay Day 1. {pronoun} đã đi xa quá để quay đầu vì 1 phút bốc đồng.' WHERE id = 'cmoqoni3x003gm0j64095gxpo';
UPDATE "ContentItem" SET title = 'Đêm Day 29 — đêm cuối trước cột mốc.', body = 'Mình muốn nói thật: 30 ngày đầu tiên là dữ dội nhất. Sau Day 30 là tự nhiên — không phải nỗ lực. {pronoun} đã đi qua phần khó. — Khang Sol' WHERE id = 'cmoqoni42003hm0j6zgn3ihfb';
UPDATE "ContentItem" SET title = 'Đêm 30 NGÀY — tái sinh.', body = '{pronoun} đã hoàn thành. Phổi 30%, tim chậm hơn, não tái cấu trúc. {topReason} — lý do {pronoun} bắt đầu, hôm nay vẫn còn nguyên. Đêm nay ngủ với một con người mới. — Khang Sol' WHERE id = 'cmoqoni46003im0j6nglr73ej';
UPDATE "ContentItem" SET title = 'Day 1 Nhận Thức — bắt đầu, không cần hoàn hảo.', body = 'Hôm nay {pronoun} chưa cần bỏ điếu nào. Chỉ cần một việc: bấm "+ Ghi điếu" mỗi khi hút. Mỗi điếu được ghi = một dữ liệu mình học cùng {pronoun}. Sol không phán xét — Sol chỉ quan sát.' WHERE id = 'cmotefgux000010c68vhri1xy';
UPDATE "ContentItem" SET title = '1 tuần Hành Động — receptor đã đáp ứng.', body = 'Mình là Khang. Sau 7-14 ngày giảm nicotin, số receptor nAChR bắt đầu giảm về mức bình thường. Não bắt đầu "quên" sự phụ thuộc. Nhưng đây cũng là lúc dễ vấp — vì cảm giác "đã ổn", thử 1 điếu = receptor sẵn sàng kích hoạt lại. Tuần sau khó hơn 1 chút. — Khang Sol' WHERE id = 'cmotfsuxv000d6usyyvmtt5uv';
UPDATE "ContentItem" SET title = 'Day 16-21: Tại sao não phản đối?', body = '2-3 tuần sau bắt đầu giảm/cai, não phát hiện "đường tắt dopamine cũ" mất ổn định. Phản ứng tự nhiên: tạo cảm giác "thử lại để chắc chắn" — gọi là extinction burst (Skinner 1953). Cảm giác này KHÔNG phải dấu hiệu thất bại — là dấu hiệu não đang chuyển. Vượt qua = não chấp nhận.' WHERE id = 'cmotfsuy5000f6usy9v6r3q72';
UPDATE "ContentItem" SET title = 'Đêm Day 16.', body = 'Tăng cân chút? Bình thường — cơ thể đang sửa. Đừng trừng phạt mình. Cân lên là cơ chế phục hồi, không phải mỡ xấu.' WHERE id = 'cmoqoni2c0034m0j6g8pvmeqh';
UPDATE "ContentItem" SET title = 'Đêm Day 17 — sạch sau cuối tuần.', body = 'Vượt được tối nay (nhậu/tiệc) — tuần 3 dễ hơn. Mỗi cuối tuần qua = não bớt liên kết "vui = thuốc".' WHERE id = 'cmoqoni2h0035m0j636mqk63h';
UPDATE "ContentItem" SET title = 'Đêm Day 18.', body = 'Có thể đêm nay mơ hút — bình thường. Não đang dọn ký ức. Mơ KHÔNG phải dấu hiệu thèm thật. Ngủ tiếp.' WHERE id = 'cmoqoni2l0036m0j6h8kpyg3y';
UPDATE "ContentItem" SET title = 'Đêm Day 19.', body = 'Ho có đờm cuối ngày? Tốt — phổi đang dọn. Ngủ nghiêng, đỡ hơn. Cơ thể đang làm việc khi {pronoun} ngủ.' WHERE id = 'cmoqoni2r0037m0j6jbktbrc6';
UPDATE "ContentItem" SET title = 'Đêm Day 20.', body = 'Nếu hôm nay buồn vô cớ — bình thường, sẽ qua. Đêm nay ngủ sâu, mai serotonin về. Cơ thể đang sửa baseline.' WHERE id = 'cmoqoni2w0038m0j6o1lovq5k';
UPDATE "ContentItem" SET title = 'Đêm 3 tuần.', body = 'Mạch thần kinh mới đang hình thành khi {pronoun} ngủ. 21 ngày rồi — {topReason} vẫn ở đó, {pronoun} vẫn ở đây. {pronoun} đang viết lại chính mình.' WHERE id = 'cmoqoni300039m0j6ch2b8zyw';
UPDATE "ContentItem" SET title = 'Đội Sol: vì sao đồng đội mạnh hơn ý chí.', body = 'Não người 45+ Việt đặc biệt nhạy với social bonding (oxytocin). Biết có 5-10 người cùng đi cùng giai đoạn = oxytocin ổn định = cortisol giảm 18% (Heinrichs 2003). Đó là lý do {pronoun} thấy nhẹ hơn khi vào tab Đội Sol — không phải tâm lý, là sinh hoá.' WHERE id = 'cmotfsuya000g6usy48bck6dj';
UPDATE "ContentItem" SET title = '21h tối: vì sao craving mạnh nhất.', body = '21-23h, cortisol tự nhiên giảm về thấp nhất ngày → não tìm dopamine. Cùng lúc, melatonin chưa đủ cao → khó ngủ → não càng tìm "thú vui". Đây là window dễ vấp nhất. Hack: 21h tắt thiết bị, ngâm chân ấm 10'' → melatonin lên nhanh, craving hạ.' WHERE id = 'cmotfsuyf000h6usyakuwuob7';
UPDATE "ContentItem" SET title = 'Q-Day: tại sao 1 ngày cụ thể quan trọng.', body = 'Mình là Khang. Não cần "decision point" rõ — không phải "dần dần". Q-Day là ritual: trước = chuẩn bị, sau = thực hiện. Ritual kích hoạt vùng não liên quan đến commitment (anterior cingulate cortex). Ngày đó {pronoun} cam kết với chính mình = não ghi nhớ thật. Mình đã trải. — Khang Sol' WHERE id = 'cmotfsuyw000k6usyeljkdvkd';
UPDATE "ContentItem" SET title = 'Hỏi vợ/người thân: anchor xã hội.', body = 'Khi {pronoun} cam kết với 1 người cụ thể (vợ, con), oxytocin + accountability tăng cùng lúc. Nghiên cứu Stanford 2018: cam kết công khai tăng tỷ lệ thành công 65% so với cam kết "trong đầu". Người thân không cần làm gì — chỉ cần biết.' WHERE id = 'cmotfsuz2000l6usy7nel8fdu';
UPDATE "ContentItem" SET title = 'Day 23: thay đổi người khác thấy được.', body = 'Sau 3 tuần ít nicotin, da tăng oxy 15% → người khác thấy {pronoun} "tươi hơn" trước khi {pronoun} cảm thấy. Khứu giác họ cũng nhận: ít mùi thuốc trên áo, hơi thở. Vợ/con thường nhận ra trước user. Hỏi họ là confirmation.' WHERE id = 'cmotfsuz7000m6usyaqhgqwzu';
UPDATE "ContentItem" SET title = '5 ngày trước Q-Day: chuẩn bị tâm lý.', body = 'Não cần ~5 ngày để "chấp nhận" thay đổi lớn — tương tự visualization trước thi đấu thể thao. Mỗi ngày tưởng tượng Q-Day cụ thể: dậy 7h, không châm điếu sáng, mở Sol, bấm "Tôi cam kết". Visualization tăng tỷ lệ thành công 22% (Cooper 2014).' WHERE id = 'cmotfsuzd000n6usymamxjve4';
UPDATE "ContentItem" SET title = 'Môi trường = 50% thành công.', body = 'Nghiên cứu Wood 2007 trên 1000 người cai thuốc: môi trường (vứt bao thuốc, gạt tàn, áo khoác sạch) chiếm 50% kết quả Day 30. Não dùng visual cue tự động — không có cue = ít trigger. Cuối tuần này dọn nhà = giảm 50% rủi ro.' WHERE id = 'cmotfsuzi000o6usymn7p4q4u';
UPDATE "ContentItem" SET title = 'T-2: cortisol đỉnh sáng giảm dần.', body = 'Sau 25-26 ngày giảm dần, cortisol awakening response giảm 18% so với baseline. Sáng dậy bớt "thèm" hơn lúc đầu. {pronoun} có cảm thấy không? Nếu chưa — bình thường, mỗi người khác. Cortisol là chỉ số khách quan, không phụ thuộc nhật trí.' WHERE id = 'cmotfsuzn000p6usy7yowms8b';
UPDATE "ContentItem" SET title = 'Đêm trước Q-Day: ngủ là vũ khí.', body = 'Giấc ngủ sâu (slow-wave sleep) là lúc não consolidate decisions. Đêm trước Q-Day, ngủ 7-8 tiếng = quyết tâm "in vào" memory. Thiếu ngủ = quyết định mai dễ lung lay. Tránh cà phê sau 14h, tắt thiết bị 21h.' WHERE id = 'cmotfsuzs000q6usyneha2s00';
UPDATE "ContentItem" SET title = 'Q-Day Day 28: 24 giờ đầu sinh học.', body = 'Mình là Khang. Khoa học: 24 giờ đầu, nicotin về 0 trong máu (half-life 2h, 12 lần half-life = sạch). Receptor bắt đầu downregulate. Trong 24h này, 70% cơn thèm là sinh học thật — không phải tâm lý. Mỗi giờ sống qua = receptor giảm 1 chút. {pronoun} không yếu — não đang chuyển. — Khang Sol' WHERE id = 'cmotfsuzx000r6usycf6dmn3z';
UPDATE "ContentItem" SET title = 'Day 59: phổi đã sửa gì sau 30 ngày?', body = 'Theo NHS: cilia (lông phổi) phục hồi đẩy đờm + bụi ra; chức năng phổi tăng 10%; nguy cơ đau tim giảm 50% so với người vẫn hút. Đối với người 45+ Việt, lá phổi đã chịu 20-30 năm khói — nhưng phổi có khả năng tái sinh đáng kinh ngạc nếu không tiếp tục hút.' WHERE id = 'cmotfsv02000s6usygb4ugrut';
UPDATE "ContentItem" SET title = 'Identity neuroplasticity: 60 ngày đủ chưa?', body = 'Mình là Khang. Nghiên cứu Lally 2010: trung bình 66 ngày để habit mới trở thành tự động. {pronoun} đang gần đó. Nhưng identity shift cần lâu hơn — khoảng 6 tháng để "tôi không hút" trở thành câu nói tự nhiên. Day 62 là khởi đầu, không phải đích. Cứ kiên nhẫn. — Khang Sol' WHERE id = 'cmotfsv08000t6usyyx2nuubb';
UPDATE "ContentItem" SET title = 'Khi thấy người khác hút: mirror neuron.', body = 'Mirror neuron trong premotor cortex bắt chước hành động người khác → thấy họ hút, não tự "diễn lại". Nếu {pronoun} thấy thèm khi đứng cạnh người hút — bình thường. Hack: nhìn đi nơi khác trong 3-5 giây, mirror neuron giảm 70% (Rizzolatti 2008).' WHERE id = 'cmotfsv0d000u6usyu27wxax9';
UPDATE "ContentItem" SET title = 'Day 75 trap: science của relapse.', body = 'Mình là Khang. Nghiên cứu Hughes 2004 trên 5000 người cai: relapse risk có 2 đỉnh — Day 3-7 (sinh học) và Day 70-90 (tâm lý). Đỉnh thứ 2 đến từ overconfidence — não quên "đau". Đây là cơ chế bảo vệ tự nhiên, không phải failure. Biết trước = đề phòng. — Khang Sol' WHERE id = 'cmotfsv0i000v6usyliaopmtr';
UPDATE "ContentItem" SET title = 'Mentor effect: dạy = học.', body = 'Nghiên cứu Mayo Clinic 2019: người chia sẻ kinh nghiệm cai thuốc với 1 người mới có tỷ lệ duy trì 30% cao hơn. Lý do: dạy lại = củng cố neural pathway. Mỗi lần kể lại, identity "người không hút" mạnh thêm. Đây là vì sao Phase 4 có Đại Sứ Mode.' WHERE id = 'cmotfsv0n000w6usy2yzr84pv';
UPDATE "ContentItem" SET title = 'Day 74: body 80% — chỉ số cụ thể.', body = 'Sau 60+ ngày: nguy cơ đột quỵ về mức người chưa hút (CDC); chức năng phổi 80% trong người dưới 50, 60% người trên 50 (NHS); khứu giác/vị giác 90% recovery (Cain 2007); tuần hoàn cải thiện 30% — tay/chân ấm hơn rõ. {pronoun} có cảm thấy không?' WHERE id = 'cmotfsv0s000x6usy02r5w3ni';
UPDATE "ContentItem" SET title = '1 năm sau: rủi ro giảm 50%.', body = 'Mình là Khang. Doll & Hill BMJ 2004 (50 năm theo dõi 34000 bác sĩ Anh): 1 năm sau cai, rủi ro đau tim giảm 50%; 5 năm — rủi ro ung thư miệng/vòm họng giảm 50%; 10 năm — rủi ro ung thư phổi giảm 50%; 15 năm — về mức người chưa bao giờ hút. {pronoun} đang đi trên timeline đó. — Khang Sol' WHERE id = 'cmotfsv10000y6usyqvxiwht7';
UPDATE "ContentItem" SET title = 'Vì người khác: oxytocin + dopamine.', body = 'Mình là Khang. Não người Việt 45+ đặc biệt mạnh ở "vì người khác" — mạch oxytocin (gắn kết) + dopamine (mục tiêu) cùng kích hoạt khi nghĩ tới gia đình. Đây là lý do "vì cu Tí" mạnh hơn "vì sức khoẻ" — sinh hoá xác nhận điều mình thấy năm 2018. — Khang Sol' WHERE id = 'cmotfsv17000z6usy1fxolbbz';
UPDATE "ContentItem" SET title = 'Autonomy: vì sao Sol giảm dần.', body = 'Self-Determination Theory (Deci & Ryan 2000): autonomy = nhu cầu cơ bản của não. Quá phụ thuộc app → motivation rớt khi ngưng. Sol cố ý giảm tần suất từ Day 80 để {pronoun} nhận: "Tôi tự làm được". Đây là cách thiết kế bền vững, không phải bỏ rơi.' WHERE id = 'cmotfsv1c00106usy602yscek';
UPDATE "ContentItem" SET title = 'Day 88 graduation: 88 ngày = 12+ tuần.', body = 'Mình là Khang. 88 ngày = 12.5 tuần. Theo Brody 2006, sau 11 tuần receptor nAChR gần về baseline người chưa hút. Sau Day 88, sinh học của {pronoun} không khác người chưa bao giờ hút. {pronoun} không "đang cố cai" nữa — {pronoun} là người không hút. Hành trình tới đây là đoạn cứng nhất. Phía trước nhẹ. — Khang Sol' WHERE id = 'cmotfsv1h00116usyttqhxxnw';
UPDATE "ContentItem" SET title = 'Identity — não thay đổi qua narrative.', body = 'Câu chuyện {pronoun} kể về mình đến não qua medial prefrontal cortex — vùng quy về "self". Khi {pronoun} nói "tôi đang cố bỏ thuốc" — não vẫn coi mình là người hút. Khi nói "tôi không hút" — não cập nhật self-concept. Câu chữ thay đổi neural pathways thật (Allen Carr 1985, neuroscience xác nhận 2010s).' WHERE id = 'cmotfsuy0000e6usyfy920l29';
UPDATE "ContentItem" SET title = '1 điếu lúc nhậu: hiệu ứng nicotin tái khởi động.', body = '1 điếu = nicotin về máu peak trong 10 phút, kích hoạt nAChR receptor đang "ngủ". Receptor được kích lại → não nhớ "đường tắt cũ". Trong 72 giờ, craving quay về mức trước cai. Đây là hiệu ứng "1 điếu thôi" — rủi ro cao gấp 8-10x bình thường (Shiffman 2006).' WHERE id = 'cmotfsuyq000j6usy642s20qq';
UPDATE "ContentItem" SET title = 'Đêm 1 — Sol đã thấy {pronoun} hôm nay.', body = 'Hôm nay {pronoun} đã ghi điếu đầu tiên. Sol thấy — không phán xét. Đêm nay {pronoun} không cần làm gì. Chỉ cần ngủ. Mai Sol còn ở đây. Chúc {pronoun} ngủ ngon.' WHERE id = 'cmotg5j5k00008qmdvd2bdrir';
UPDATE "ContentItem" SET title = 'Đêm 2 — quan sát rồi để xuống.', body = 'Hôm nay {pronoun} có quan sát được lúc nào dễ châm điếu nhất chưa? Không sao nếu chưa rõ — Sol đang học cùng {pronoun}. Trước khi ngủ, để mọi cố gắng xuống. Mai sáng dậy, ngày mới.' WHERE id = 'cmotg5j5q00018qmdndzh6a2s';
UPDATE "ContentItem" SET title = 'Đêm 3 — pattern bắt đầu lộ.', body = 'Sol đã thấy: {pronoun} có lúc châm vì stress, có lúc vì rảnh, có lúc vì sau cơm. Mỗi lúc một lý do khác. Đó là chân dung sống của {pronoun} — không có gì sai. Đêm nay nghỉ — Sol đang ghi.' WHERE id = 'cmotg5j5w00028qmd0wr1bi4z';
UPDATE "ContentItem" SET title = 'Đêm 4 — thèm hôm nay đã qua chưa?', body = 'Mỗi cơn thèm hôm nay đã đến rồi đi. {pronoun} đã sống qua tất cả — dù hút hay không. Đó là chiến thắng nhỏ Sol đếm. Đêm nay ngủ kỹ — não đang sửa.' WHERE id = 'cmotg5j6100038qmdlxgapitx';
UPDATE "ContentItem" SET title = 'Đêm 5 — gần nửa tuần Nhận Thức.', body = '5 ngày qua {pronoun} đã ghi nhận. Đó là dữ liệu thật — không có ai khác trên đời này biết {pronoun} hơn lúc này. Chính {pronoun} đang biết mình. Đêm yên.' WHERE id = 'cmotg5j6700048qmd99edce52';
UPDATE "ContentItem" SET title = 'Đêm 6 — gần xong tuần Nhận Thức.', body = 'Mai là ngày 7. Mai Sol sẽ tổng kết tuần với {pronoun}. Đêm nay không cần kết luận gì — chỉ ngủ. Ngày 7 sáng mai sẽ rõ.' WHERE id = 'cmotg5j6c00058qmd5afhjcm5';
UPDATE "ContentItem" SET title = 'Đêm 7 — chuyển trang.', body = 'Mình là Khang. Tuần Nhận Thức của {pronoun} đã xong. Mai sang Hành Động — đồ thị giảm bắt đầu. Đêm nay ngủ — không phải để chuẩn bị "chiến đấu". Để chuẩn bị "đi tiếp". Khác nhau. — Khang Sol' WHERE id = 'cmotg5j6i00068qmdx6vtbg21';
UPDATE "ContentItem" SET title = 'Đêm 8 — delay đầu tiên.', body = 'Hôm nay {pronoun} thử delay 10 phút lần nào không? Nếu có — Sol mừng. Nếu không — mai khác. Tuần này không vội. Đêm nay {pronoun} chỉ cần ngủ ngon, ngày mai não thử lại.' WHERE id = 'cmotg5j6n00078qmdi5tfeq4w';
UPDATE "ContentItem" SET title = 'Đêm 9 — vòng lặp đang lung lay.', body = 'Mỗi lần {pronoun} delay được, vòng lặp cũ bị lung lay 1 chút. Đêm nay não đang sắp xếp lại — đó là lúc giấc ngủ sâu quan trọng. Tắt điện thoại sớm hơn 30 phút.' WHERE id = 'cmotg5j6t00088qmdolpxqj4t';
UPDATE "ContentItem" SET title = 'Đêm 10 — Plan B đã có.', body = 'Hôm nay Sol gợi Plan B cho top trigger của {pronoun}. Đã thử chưa? Nếu thử — note 1 câu vào sổ tay: "Hôm nay tôi thay [hút] bằng [đi bộ / nước]". Câu đó ngày mai đọc lại sẽ thấy mình.' WHERE id = 'cmotg5j6z00098qmdt16pnglv';
UPDATE "ContentItem" SET title = 'Đêm 11 — giảm nhẹ.', body = 'Hôm nay so với baseline tuần Nhận Thức — {pronoun} đã giảm bao nhiêu? Mở /analytics xem nếu chưa rõ. Mỗi điếu giảm = 1 lần não chọn khác. Đêm yên với chính mình.' WHERE id = 'cmotg5j75000a8qmdyvlug94e';
UPDATE "ContentItem" SET title = 'Đêm 12 — stress đã qua.', body = 'Stress hôm nay đã xuống chưa? Nếu hôm nay {pronoun} có lúc stress mà không hút — đó là chiến thắng to. Não đang học: stress không bắt buộc đi cùng nicotin. Ghi vào sổ.' WHERE id = 'cmotg5j7c000b8qmdj9fxi6oh';
UPDATE "ContentItem" SET title = 'Đêm 13 — bữa cơm khác.', body = '{pronoun} có thử đánh răng sau bữa cơm hôm nay không? Vị bạc hà thay điếu — nhỏ nhưng thay đổi mạnh. Mai cũng vậy. Đêm này nghỉ.' WHERE id = 'cmotg5j7i000c8qmdycbwonnt';
UPDATE "ContentItem" SET title = 'Đêm 14 — 1 tuần Hành Động.', body = 'Mình là Khang. {pronoun} đã đi 14 ngày từ Day 1 — 1 tuần Nhận Thức + 1 tuần Hành Động. Receptor nicotin trong não đã giảm đáng kể. Cơ thể đang cảm ơn {pronoun} thầm. Đêm nay xứng đáng ngủ sâu. — Khang Sol' WHERE id = 'cmotg5j7n000d8qmd86ho45gb';
UPDATE "ContentItem" SET title = 'Đêm 15 — câu hỏi identity.', body = 'Sáng nay Sol hỏi: {pronoun} là ai khi không hút? Tối nay {pronoun} có câu trả lời không? Không cần đầy đủ — chỉ 1 câu. Viết ra giấy, để cạnh giường. Mai đọc lại.' WHERE id = 'cmotg5j7s000e8qmdoo5hagi6';
UPDATE "ContentItem" SET title = 'Đêm 16 — vào tuần khó.', body = 'Tuần này có thể có lúc não nói "thử 1 điếu xem sao". Đêm nay nếu cảm giác đó lên — không cần đánh nó. Chỉ cần nhận ra: "Đây là não đang phản đối, không phải tôi". Rồi ngủ.' WHERE id = 'cmotg5j7z000f8qmd615g8eu2';
UPDATE "ContentItem" SET title = 'Đêm 17 — không cô đơn.', body = 'Hôm nay Sol mời {pronoun} mở Đội Sol. Có nhìn không? 5-10 đồng đội cùng phase với {pronoun} đang ngủ trong các thành phố khác. Có người đang Day 17 như {pronoun}, có người đang Day 35. Cùng đường.' WHERE id = 'cmotg5j84000g8qmd3tiv9bb8';
UPDATE "ContentItem" SET title = 'Đêm 21 — 3 lý do.', body = 'Mình là Khang. Hôm nay {pronoun} viết 3 lý do chưa? Nếu có — để cạnh giường. Mỗi đêm đọc lại. Tuần sau lúc Q-Day, mình muốn {pronoun} đã đọc 7 lần. 3 lý do trở thành 21 lần ghi nhớ. Mạnh hơn ý chí. — Khang Sol' WHERE id = 'cmotg5j8p000k8qmdx9kws27r';
UPDATE "ContentItem" SET title = 'Đêm 22 — đã hỏi vợ chưa?', body = 'Hôm nay sáng Sol gợi {pronoun} hỏi vợ/người thân: "Tôi nên cam kết gì?" Đã hỏi chưa? Nếu chưa — không sao, mai. Nếu rồi — câu trả lời của họ ghi vào sổ. Tuần sau Q-Day {pronoun} sẽ cần câu đó.' WHERE id = 'cmotg5j8v000l8qmdsh2fib9q';
UPDATE "ContentItem" SET title = 'Đêm 23 — người thân thấy gì.', body = 'Hôm nay có ai trong nhà nhận xét {pronoun} khác chưa? Da tươi hơn? Hơi thở đỡ? Hỏi 1 người. Câu trả lời của họ là gương trung thực. Đêm này nghỉ với confirmation đó.' WHERE id = 'cmotg5j90000m8qmdog5fk9wy';
UPDATE "ContentItem" SET title = 'Đêm 24 — 5 ngày nữa.', body = 'Còn 4 ngày là Q-Day. Đêm nay tưởng tượng: sáng 7h Day 28, {pronoun} dậy, mở dashboard, bấm "Tôi cam kết". Hình ảnh đó in vào não trong giấc ngủ — visualization. Nhẹ nhàng ngủ.' WHERE id = 'cmotg5j95000n8qmdb1qnw90d';
UPDATE "ContentItem" SET title = 'Đêm 25 — chuẩn bị nhà.', body = 'Mai cuối tuần. {pronoun} có dọn bao thuốc còn lại + gạt tàn không? Không cần dọn ngay tối nay — sáng mai. Đêm nay ngủ. Não cần nghỉ trước decision lớn.' WHERE id = 'cmotg5j9b000o8qmdi1t2b8xz';
UPDATE "ContentItem" SET title = 'Đêm 26 — T-2.', body = 'Còn 2 ngày là Q-Day. Sáng nay Sol đã gửi push T-2. Đêm nay {pronoun} đọc lại 3 lý do (nếu chưa làm) — slowly, không vội. Rồi ngủ. Mai T-1.' WHERE id = 'cmotg5j9g000p8qmdl5cfwztk';
UPDATE "ContentItem" SET title = 'Đêm 27 — đêm trước Q-Day.', body = 'Mình là Khang. Đêm nay là đêm cuối Phase Hành Động. Mình muốn nói 1 câu cho {pronoun}: "Mình đã ở chỗ {pronoun} đang đứng năm 2018." Mình ngủ đêm đó như đứa trẻ — vì biết sáng mai mình quyết định cứu chính mình. Mai cũng vậy. — Khang Sol' WHERE id = 'cmotg5j9l000q8qmddywshdf0';
UPDATE "ContentItem" SET title = 'Đêm 28 — Q-Day kết thúc.', body = 'Mình là Khang. Hôm nay {pronoun} đã bấm "Tôi cam kết". Đêm đầu tiên với đồng hồ tự do đang chạy. Đây là đêm thiêng — cơ thể đang sạch nicotin. Nếu khó ngủ — bình thường, đêm thứ 2-3 dễ hơn. Sol bên {pronoun}. Ngủ ngon, người không hút. — Khang Sol' WHERE id = 'cmotg5j9r000r8qmdzu66sett';
UPDATE "ContentItem" SET title = 'Đêm 59 — 30 ngày tự do.', body = 'Mình là Khang. Đêm nay {pronoun} ngủ không có nicotin trong máu — đêm thứ 30 liên tiếp. Não đã quen. Tim đập chậm hơn 8-10 nhịp/phút lúc nghỉ. Ngủ sâu hơn. {pronoun} có cảm thấy không? Đêm yên với chính cơ thể. — Khang Sol' WHERE id = 'cmotg5j9w000s8qmdxkqboacd';
UPDATE "ContentItem" SET title = 'Đêm 62 — ai là {pronoun} bây giờ.', body = 'Mình là Khang. Câu sáng nay: "{pronoun} là gì bây giờ?". Đêm nay không cần trả lời gấp. Cứ để câu hỏi nằm bên cạnh, ngủ với nó. Mai dậy có thể câu trả lời sẽ rõ — hoặc không, vẫn không sao. Identity là quá trình, không phải kết quả. — Khang Sol' WHERE id = 'cmotg5ja1000t8qmdvuw7rxjr';
UPDATE "ContentItem" SET title = 'Đêm 65 — phản ứng với người hút.', body = 'Hôm nay {pronoun} có gặp người đang hút không? Phản ứng đầu tiên — nếu là "bình thản, không quan tâm" — đó là dấu hiệu identity đã chuyển. Sol thấy {pronoun} ngày càng xa pattern cũ. Đêm nay nghỉ với chính mình mới.' WHERE id = 'cmotg5ja7000u8qmdti7qgejw';
UPDATE "ContentItem" SET title = 'Đêm 68 — biết trước Day 75.', body = 'Mình là Khang. Sáng nay mình cảnh báo Day 75 trap. Đêm nay tự nhắc: "1 điếu thử = 72 giờ thèm trở lại". Não muốn dùng cảm giác "an toàn" để gài. Biết trước = đã thắng nửa. {pronoun} không yếu — {pronoun} đã đi 68 ngày. Đêm yên. — Khang Sol' WHERE id = 'cmotg5jac000v8qmdz78hl170';
UPDATE "ContentItem" SET title = 'Đêm 71 — cách giữ vững.', body = 'Sáng nay Sol gợi: chia sẻ với 1 người mới đang muốn cai. Đêm nay tưởng tượng câu {pronoun} sẽ nói. Không cần lý thuyết — kể {pronoun} đã đi sao. Đêm này tích trữ ý — mai có cơ hội thử.' WHERE id = 'cmotg5jah000w8qmdv3mp0q0r';
UPDATE "ContentItem" SET title = 'Đêm 74 — body đã hồi.', body = 'Cơ thể {pronoun} đêm nay khác cơ thể đêm Day 1: phổi sạch hơn, tim đập đều, ngủ sâu hơn. Đặt tay lên ngực, cảm nhận nhịp. Đó là nhịp của người không hút. Đêm yên với cơ thể đó.' WHERE id = 'cmotg5jam000x8qmdb0ydthlr';
UPDATE "ContentItem" SET title = 'Đêm 77 — 1 năm sau.', body = 'Mình là Khang. Sáng nay câu hỏi: 1 năm sau {pronoun} là ai? Đêm nay ngủ với 1 hình ảnh cụ thể — không generic. Vd "1 năm nữa tôi đi Đà Lạt với vợ, không cần ngừng hút giữa đường". Hình ảnh đó nuôi não trong giấc ngủ. — Khang Sol' WHERE id = 'cmotg5jas000y8qmdrpb223a8';
UPDATE "ContentItem" SET title = 'Đêm 80 — vì người khác.', body = 'Mình là Khang. Mình bỏ vì cu Tí — mình đã nói. Đêm nay {pronoun} đọc lại lý do của mình. Nếu lý do gốc còn — đó là rễ. Nếu cần đổi — đổi không sao, sự thật quan trọng hơn câu chữ. {pronoun} đang sống cho ai? — Khang Sol' WHERE id = 'cmotg5jax000z8qmdmno56v16';
UPDATE "ContentItem" SET title = 'Đêm 83 — Sol nhỏ dần.', body = 'Sol giảm tần suất nhắc — đêm nay là 1 trong những đêm cuối Sol nói. Không phải bỏ {pronoun} — là {pronoun} không cần Sol nữa. Khi nào cần, mở widget, gõ 1 câu. Sol vẫn đợi. Đêm yên.' WHERE id = 'cmotg5jb200108qmdpqyx72gu';
UPDATE "ContentItem" SET title = 'Đêm 86 — gần tốt nghiệp.', body = 'Mình là Khang. Còn 2 đêm nữa là Day 88. {pronoun} đang gần xong cuộc hành trình mình thiết kế. Đêm này nghĩ: ai trong gia đình {pronoun} sẽ ăn mừng cùng? Mai mời 1 người. Đại Sứ là chia sẻ — bắt đầu từ trong nhà. — Khang Sol' WHERE id = 'cmotg5jb800118qmdo3jothfv';

SELECT title, LEFT(body, 50) FROM "ContentItem" ORDER BY "dayNumber" LIMIT 5;
