-- Run với: docker cp + docker exec psql -f
\set ON_ERROR_STOP on

UPDATE "CannedReply" SET answer = 'Cơn thèm chỉ kéo dài 3–5 phút rồi tự dịu. Bạn thử ngay 1 trong 3 cách: hít thở 4-7-8 ba lần · uống ngụm nước lạnh · đi 200 bước. Sau 5 phút quay lại đây — phần lớn cơn đã qua. Bạn không phải đấu một mình.' WHERE slug = 'them-thuoc';
UPDATE "CannedReply" SET answer = 'Mệt là dấu hiệu cơ thể đang sửa, không phải dấu hiệu thất bại. Bạn không cần "cai cả đời" — chỉ cần không hút trong 1 giờ tới. Một giờ thôi. Nếu vẫn khó, mở mục SOS 90 giây ở góc dưới — Sol sẽ ở cạnh bạn từng nhịp thở.' WHERE slug = 'bo-cuoc';
UPDATE "CannedReply" SET answer = 'Có. Chỉ 1 điếu là nicotin về nồng độ cao trong 10 phút, thiết lập lại "đồng hồ thèm" 72 giờ. Nghiên cứu thấy 95% người "chỉ hút 1 điếu" sẽ hút trở lại trong 1 tuần. Đã đi được tới đây thì giữ nguyên — đừng cho não cơ hội học lại.' WHERE slug = 'mot-dieu';
UPDATE "CannedReply" SET answer = 'Cơn thèm cấp tính (thể chất): 3–7 ngày, đỉnh ở ngày 2-3. Cơn thèm tâm lý (theo thói quen, mùi): 4–12 tuần. Sau 3 tháng, hầu như không còn nhớ. Bạn đang ở giai đoạn khó nhất — vượt qua là phần thưởng cả đời.' WHERE slug = 'bao-lau-het-them';
UPDATE "CannedReply" SET answer = 'Bình thường — não đang dựng lại receptor dopamine, giấc ngủ sẽ nông trong 1–2 tuần đầu. Tránh cà phê sau 14h, tắt điện thoại 30 phút trước ngủ, ngâm chân nước ấm 10 phút. Nếu sau 2 tuần vẫn mất ngủ nặng, nói với bác sĩ — không tự uống thuốc ngủ.' WHERE slug = 'mat-ngu';
UPDATE "CannedReply" SET answer = 'Rất bình thường. Não thiếu dopamine từ nicotin nên dễ nổi nóng. Đỉnh điểm là ngày 3–5, sau 2 tuần dịu nhiều, hết hẳn sau ~1 tháng. Báo trước với người thân để họ thông cảm. Đi bộ 15 phút khi tức giận thay vì cãi nhau.' WHERE slug = 'cau-gat';
UPDATE "CannedReply" SET answer = 'Trung bình tăng 2–4 kg trong 3 tháng đầu — vẫn an toàn hơn hút thuốc rất nhiều. Cách giữ cân: uống đủ 2 lít nước/ngày, nhai kẹo cao su không đường khi thèm, đi bộ 30 phút mỗi tối. Ưu tiên bỏ thuốc trước — giảm cân tính sau.' WHERE slug = 'tang-can';
UPDATE "CannedReply" SET answer = 'Không. Vape vẫn chứa nicotin + hoá chất khác (formaldehyde, kim loại nặng). Nghiên cứu thấy >60% người dùng vape để "cai" sẽ quay lại thuốc lá truyền thống trong 6 tháng. Bỏ nguyên (cold turkey) hoặc dùng miếng dán nicotin theo bác sĩ — đó là 2 cách đã chứng minh hiệu quả.' WHERE slug = 'vape-an-toan';
UPDATE "CannedReply" SET answer = 'Sóng thèm mạnh nhất chỉ kéo 90 giây. Đứng dậy, đi ra cửa sổ, hít vào 4 giây — giữ 7 giây — thở ra 8 giây. Lặp 3 lần. Trong lúc thở, đếm to "tôi đã không hút bao nhiêu giờ". Đây là cuộc đấu của 90 giây — không phải cả đời.' WHERE slug = 'them-du-doi';
UPDATE "CannedReply" SET answer = 'Bạn còn 30 giây — đủ để cứu 30 ngày qua. Đặt điện thoại xuống. Đi ra ngoài. Gọi 1 người trong danh sách hỗ trợ. Nếu không gọi được ai, viết ra đây 3 lý do bạn đã chọn cai. Sau 5 phút sóng sẽ hạ — bạn KHÔNG yếu, bạn đang chiến đấu.' WHERE slug = 'sap-hut-lai';
UPDATE "CannedReply" SET answer = '1 điếu không xoá những ngày sạch trước đó. Đây là vấp — không phải thất bại. Đứng dậy ngay từ lúc này, không phải "ngày mai bắt đầu lại". Quan trọng: viết ra điều gì đã trigger để học cho lần sau. Khang đã vấp 6 lần trước khi cai được lần thứ 7.' WHERE slug = 'lo-hut-roi';
UPDATE "CannedReply" SET answer = 'Tin tốt — đó là cilia (lông phổi) đang hồi phục và đẩy nhựa tích lâu năm ra. Đờm vàng/nâu là bình thường trong 2-4 tuần đầu. Uống nhiều nước ấm (2-3 lít/ngày), tránh chỗ khói bụi. Nếu ho ra MÁU hoặc đau ngực — đi khám ngay.' WHERE slug = 'ho-co-dom';
UPDATE "CannedReply" SET answer = 'Mạch máu não đang giãn lại sau nhiều năm bị nicotine co. Đau đầu tập trung 3-7 ngày đầu, dịu dần. Cách giảm: uống đủ nước, ngủ thêm 1 giờ, tránh cà phê đậm. Có thể uống paracetamol bình thường. Sau 1 tuần vẫn đau → đi khám.' WHERE slug = 'dau-dau';
UPDATE "CannedReply" SET answer = 'Bình thường — não đang điều chỉnh oxy cao hơn (do CO trong máu giảm). Đỉnh ở ngày 2-5. Cách giảm: đứng lên chậm, uống nước nhiều, ăn nhẹ thường xuyên. Nếu chóng mặt kèm nôn hoặc kéo dài >30 phút → đi khám ngay.' WHERE slug = 'chong-mat';
UPDATE "CannedReply" SET answer = 'Một số người thấy "khó thở" trong tuần đầu vì phổi đang dọn dẹp + nhịp thở chưa quen "thở sâu" sau nhiều năm thở nông do thuốc. Tập thở 4-7-8 và đi bộ chậm 15 phút/ngày. Nếu KHÓ THỞ DỮ DỘI hoặc đau ngực → gọi 115 ngay.' WHERE slug = 'kho-tho';
UPDATE "CannedReply" SET answer = 'Hệ tiêu hoá đang chậm lại vì không còn nicotine kích thích nhu động ruột. Bình thường, tự ổn sau 2-3 tuần. Cách giải: 2 lít nước/ngày, ăn rau xanh + chuối + đu đủ, đi bộ 30 phút sau bữa cơm. Tránh thuốc xổ — để cơ thể tự điều chỉnh.' WHERE slug = 'tao-bon';
UPDATE "CannedReply" SET answer = 'Vi khuẩn miệng đang điều chỉnh sau khi không có khói. Lở loét + đắng miệng kéo 1-2 tuần. Cách giảm: súc miệng nước muối ấm 3 lần/ngày, đánh răng nhẹ với bàn chải mềm, uống nhiều nước. Tránh đồ chua/cay tuần đầu.' WHERE slug = 'mieng-lo-loet';
UPDATE "CannedReply" SET answer = 'Đây là "Đống Tro Tàn" — dopamine tự nhiên chưa hồi phục đủ sau khi mất nguồn nicotine. Cảm giác trống rỗng, mất hứng thú là khoa học, không phải bạn yếu lòng. Tự sửa sau 2-4 tuần. Tập thể dục nhẹ + gặp người thân + ngủ đủ 7 tiếng. Nếu kéo dài >1 tháng → bác sĩ tâm lý.' WHERE slug = 'buon-chan';
UPDATE "CannedReply" SET answer = 'Cai thuốc đôi khi mất cả "bạn nhậu" cũ — họ vẫn hút, mình thấy lạc lõng. Đây là tín hiệu bạn đang đổi sang con người mới, không phải dấu hiệu sai. Hãy gọi 1 người trong gia đình hoặc 1 người bạn không hút — nói rằng bạn đang cai. Trao đổi vài câu, đủ để qua sóng.' WHERE slug = 'co-don';
UPDATE "CannedReply" SET answer = 'Cảm giác "ngực tức + lo" rất phổ biến tuần 1-2. Là hệ thần kinh giao cảm đang tự điều chỉnh — tim/phổi đang hồi phục. KHÔNG phải bệnh tim. Cách giảm: hít thở 4-7-8 trước khi ngủ, đi bộ ngoài trời 20 phút mỗi sáng, hạn chế cà phê. Nếu kèm đau ngực dữ → khám tim.' WHERE slug = 'lo-au';
UPDATE "CannedReply" SET answer = 'Lúc còn hút, bạn nghĩ "thuốc giải stress" — thực ra nó CHỈ giải cơn thèm nicotine do chính nó tạo. Sau cai 2-3 tuần, mức stress trung bình GIẢM xuống. Bây giờ thay điếu thuốc bằng: 1 ly trà ấm, 5 phút đi ra ngoài, 1 cuộc gọi ngắn cho người thân. 5 phút thôi.' WHERE slug = 'stress-cong-viec';
UPDATE "CannedReply" SET answer = 'Đúng — bạn không phải người cũ nữa. Não bạn đang xây lại mạch thần kinh thói quen mới. 30 năm hút tạo ra một "phiên bản" của bạn, bây giờ phiên bản đó đang chuyển đổi. Khó chịu là tự nhiên. Sau 6-12 tuần bạn sẽ thấy "phiên bản mới" — nhẹ hơn, sáng hơn, tự do hơn.' WHERE slug = 'khong-la-minh';
UPDATE "CannedReply" SET answer = 'Trong 60 ngày đầu: tránh nhậu nếu được. Nếu phải đi: ngồi xa người hút, uống nước/bia thay rượu, ăn no trước, có "lý do về sớm" chuẩn bị sẵn (vợ gọi, con sốt, sáng sớm họp). Đừng giấu chuyện cai — nói thẳng "tôi bỏ thuốc rồi". Bạn thật sẽ tôn trọng.' WHERE slug = 'di-nhau';
UPDATE "CannedReply" SET answer = 'Đây là điếu thuốc nguy hiểm nhất với người Việt 45+. Não đã link "cà phê = nicotine" trong nhiều thập kỷ. Cách phá: tuần 1-2 đổi sang trà ấm, ngồi chỗ KHÁC (không ngồi bàn cũ), không xem điện thoại — đọc báo giấy. Sau 2-3 tuần não cắt link, có thể quay về cà phê.' WHERE slug = 'ca-phe-sang';
UPDATE "CannedReply" SET answer = '"Cảm ơn, tôi không hút." — không xin lỗi, không "đang cố nhịn", không giải thích dài. Càng đơn giản càng vững. Người tôn trọng sẽ dừng. Người ép thêm 2 lần — đứng dậy đi vệ sinh, quay lại đổi chủ đề. Nếu họ ép lần 3 — đó không phải bạn thật.' WHERE slug = 'ban-moi-thuoc';
UPDATE "CannedReply" SET answer = 'Bạn đang cáu kỉnh vì cai — họ chịu phần lớn. Bình thường tuần 1-3. Nói thẳng: "Anh đang khó tính vì cai, em chịu giúp anh 2 tuần — anh hứa sẽ tốt hơn." Cụ thể: không hét, đi ra ngoài hít thở khi muốn nổi nóng. Sau cai, gia đình nói: lần đầu thấy bạn "thật sự ở đây".' WHERE slug = 'vo-chong-gian';
UPDATE "CannedReply" SET answer = 'Đám cưới/tang ở VN có khói thuốc khắp nơi. Plan trước: ngồi bàn ngoài hoặc gần cửa, ăn nhanh, đi sớm 30 phút. Không cần giải thích — "có việc gấp" là đủ. Cảm xúc mạnh ở đám tang dễ trigger — kèm 1 chai nước, 1 viên kẹo cao su trong túi. Vượt qua ngày này, mình ổn.' WHERE slug = 'dam-tang-cuoi';
UPDATE "CannedReply" SET answer = 'Tết là thử thách lớn nhất với người cai năm đầu. Chiến lược: thông báo cả họ trước Tết "tôi đã bỏ thuốc — đừng mời". Mang quà cho người thân (không phải thuốc). Đi thăm sáng sớm khi ít người. Nếu áp lực quá — về sớm. Sau Tết, bạn có 1 thắng lợi lớn.' WHERE slug = 'tet-le';
UPDATE "CannedReply" SET answer = 'Có — phần lớn. Cilia (lông phổi) tái sinh trong 1-9 tháng, dung tích phổi tăng 10-30% sau 3 tháng. Nguy cơ ung thư phổi giảm 50% sau 10 năm cai. Phần đã tổn thương vĩnh viễn (vd phế nang giãn) không hồi nhưng tiến triển CHẬM lại. Cai càng sớm, cứu càng nhiều.' WHERE slug = 'phoi-hoi-phuc';
UPDATE "CannedReply" SET answer = 'Nhanh hơn bạn nghĩ. 24h: nguy cơ nhồi máu cơ tim bắt đầu giảm. 1 năm: rủi ro CHD giảm 50%. 5 năm: nguy cơ đột quỵ ≈ người chưa hút. 15 năm: rủi ro CHD ≈ người chưa hút. Cai thuốc là can thiệp tim mạch hiệu quả nhất — vượt cả statin và aspirin.' WHERE slug = 'tim-mach';
UPDATE "CannedReply" SET answer = 'Champix (Varenicline) là 1 trong 3 thuốc FDA approve cho cai. Hiệu quả gấp 2 so với cai chỉ bằng ý chí (USPHS Guidelines). Nhưng có tác dụng phụ — phải kê đơn + theo dõi bác sĩ. Nếu FTND ≥ 6 (nghiện nặng) hoặc đã thất bại 2-3 lần — hỏi bác sĩ về Champix hoặc Bupropion.' WHERE slug = 'champix';
UPDATE "CannedReply" SET answer = 'Có. NRT (Nicotine Replacement Therapy) gồm miếng dán/kẹo/xịt tăng tỷ lệ cai thành công 50-70% (Cochrane Review). Nguyên tắc: dán liều cao 4-6 tuần đầu, giảm dần. Mua ở pharmacy không cần đơn nhưng nên hỏi bác sĩ chọn liều. KHÔNG dùng miếng dán + hút thuốc cùng lúc.' WHERE slug = 'mieng-dan-nicotine';
UPDATE "CannedReply" SET answer = '"Có. Tôi đã thèm dữ dội, đã cáu kỉnh đến mức vợ giận, đã muốn bỏ cuộc 6 lần đầu. Lần thứ 7 thành công không phải vì tôi mạnh hơn — mà vì tôi đã học. Hôm nay bạn đang ở trong một ngày của tôi 5 năm trước. Bạn không một mình — Khang."' WHERE slug = 'khang-tung-cam-thay';
UPDATE "CannedReply" SET answer = 'Khoa học: trung bình người Việt cần 6-11 lần thử mới cai được hẳn. Lần này hay lần thứ 5 — không quan trọng. Quan trọng là bạn đang ở đây HÔM NAY, đọc tin nhắn này, không hút thuốc. Mỗi ngày cai là 1 lá phiếu cho phiên bản mới của mình. Cứ tiếp tục.' WHERE slug = 'thanh-cong-toi';
UPDATE "CannedReply" SET answer = 'Bạn không hi sinh — bạn đổi. Đổi 30 ngày khó để có 10-20 năm sống thêm. Đổi 1 thói quen cũ để có ông bà khoẻ cho cháu nội. Đổi 16 triệu/năm tiền thuốc để đầu tư cho con. Đây không phải mất mát — là phép tính tốt nhất đời bạn.' WHERE slug = 'dang-hi-sinh';
UPDATE "CannedReply" SET answer = '4 việc mỗi ngày: (1) Check-in 1 phút sáng — báo mood + cơn thèm. (2) Đọc bài tập ngày — workbook trong dashboard. (3) Khi thèm — bấm "Tôi đang thèm" hoặc chat. (4) Tối — ghi 1 câu vào sổ tay. 5 phút mỗi ngày là đủ. Không cần hoàn hảo — cần đều.' WHERE slug = 'cach-dung-app';
UPDATE "CannedReply" SET answer = 'Vào Cài đặt → Hồ sơ cai thuốc → đổi ngày bắt đầu. Lưu ý: đổi Q-Day reset đồng hồ + tier về Free (nếu có). Chỉ đổi nếu bạn muốn KHỞI ĐỘNG LẠI hoàn toàn. Nếu chỉ "mệt 1 ngày" — đừng đổi, hãy nhắn Khang trước.' WHERE slug = 'doi-q-day';
UPDATE "CannedReply" SET answer = 'Gói Đồng hành 199k được hoàn tiền theo tỷ lệ ngày còn lại — từ Ngày 15 trở đi. Vào Cài đặt → Hoàn tiền → ghi lý do (không bắt buộc) → gửi yêu cầu. Khang đọc trong 24h và chuyển tiền về MoMo/TK. Gói Khởi động 99k không hoàn (gói nhỏ, ngắn).' WHERE slug = 'hoan-tien';
UPDATE "CannedReply" SET answer = 'Khang đọc tin nhắn của user trả phí mỗi ngày. Nhắn câu chuyện của bạn ở đây — Khang sẽ reply trong 24h cho khách Đồng hành, 48h cho Khởi động. Nếu khẩn cấp y tế (đau ngực, khạc máu, ý nghĩ tự hại) — gọi 115 hoặc hotline tâm lý 1800 1567 trước.' WHERE slug = 'lien-he-khang';
UPDATE "CannedReply" SET answer = 'Voice Khang gửi vào những ngày khó nhất: Ngày 1 (chào mừng), Ngày 3 (đỉnh withdrawal), Ngày 7 (tuần đầu hoàn tất). Gói Đồng hành có thêm Ngày 14, 21, 30 + thư cuối. Vào mục "Voice Khang" trong dashboard để nghe lại bất cứ lúc nào.' WHERE slug = 'voice-khang';
UPDATE "CannedReply" SET answer = '⚠️ ĐI KHÁM NGAY HÔM NAY. Khạc máu (dù ít) cần CT phổi để loại trừ ung thư hoặc nhiễm trùng nặng. Đừng đợi. Trong khi đợi khám: không hút lại (sẽ làm tệ hơn), uống nhiều nước, không tập thể dục mạnh. Báo bác sĩ bạn đã hút bao lâu, cai từ khi nào.' WHERE slug = 'khac-mau';
UPDATE "CannedReply" SET answer = '🚨 GỌI 115 NGAY. Đau ngực dữ dội + khó thở + đổ mồ hôi = dấu hiệu nhồi máu cơ tim. Không lái xe đi cấp cứu — gọi xe. Trong khi chờ: ngồi nghỉ, nhai 1 viên aspirin (nếu không dị ứng). Cai thuốc lá KHÔNG gây MI — nhưng MI tiềm ẩn lâu năm có thể bộc phát. Đừng chần chừ.' WHERE slug = 'dau-nguc-du';
UPDATE "CannedReply" SET answer = 'Khang ở đây với bạn ngay bây giờ. Cai thuốc đôi khi làm tệ hơn trầm cảm tiềm ẩn — không phải lỗi của bạn. GỌI hotline tâm lý 1800 1567 (miễn phí, 24/7). Hoặc gọi 1 người thân ngay bây giờ — không cần giải thích, chỉ cần "tôi đang khó". Bạn không một mình. Bạn quan trọng.' WHERE slug = 'y-nghi-tu-hai';

-- Verify
SELECT slug, LEFT(answer, 60) AS answer_preview FROM "CannedReply" WHERE enabled = true LIMIT 5;
