#!/bin/bash
# Setup auto-backup Postgres huongdi_prod - Daily 3AM + 7 days rolling
# Chay 1 lan tren VPS: bash /tmp/setup-db-daily-backup.sh
# Script se:
#   1. Tao script backup /usr/local/bin/db-backup.sh
#   2. Tao cron job chay hang ngay 3AM
#   3. Tao folder /var/backups/db-daily/
#   4. Test chay 1 lan de verify

set -e

# ==================================================================
# CONFIG
# ==================================================================
BACKUP_DIR="/var/backups/db-daily"
BACKUP_SCRIPT="/usr/local/bin/db-backup.sh"
RETENTION_DAYS=7
DB_NAME="huongdi_prod"
CRON_TIME="0 3 * * *"  # 3AM daily

echo "==============================================="
echo "  Setup Auto-Backup DB huongdi_prod"
echo "  Schedule: Daily 3AM"
echo "  Retention: $RETENTION_DAYS days"
echo "==============================================="

# ==================================================================
# STEP 1: Tao backup folder
# ==================================================================
echo ""
echo "[1/4] Create backup folder"
sudo mkdir -p "$BACKUP_DIR"
sudo chown solop:solop "$BACKUP_DIR"
echo "  OK: $BACKUP_DIR"

# ==================================================================
# STEP 2: Tao script backup
# ==================================================================
echo ""
echo "[2/4] Create backup script $BACKUP_SCRIPT"

sudo tee "$BACKUP_SCRIPT" > /dev/null << 'SCRIPT_EOF'
#!/bin/bash
# Daily backup Postgres huongdi_prod
# Auto-generated by setup-db-daily-backup.sh

set -e

BACKUP_DIR="/var/backups/db-daily"
DB_NAME="huongdi_prod"
RETENTION_DAYS=7
DATE=$(date +'%Y-%m-%d_%H-%M-%S')
LOG_FILE="/var/log/db-backup.log"

# Log helper
log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1" | sudo tee -a "$LOG_FILE" > /dev/null
}

log "=== Backup START ==="

# Dump DB
BACKUP_FILE="$BACKUP_DIR/${DB_NAME}_${DATE}.sql.gz"
if sudo -u postgres pg_dump "$DB_NAME" --no-owner --no-acl --clean --if-exists 2>/dev/null | gzip > "$BACKUP_FILE"; then
    SIZE=$(du -h "$BACKUP_FILE" | cut -f1)
    log "Backup OK: $BACKUP_FILE ($SIZE)"
else
    log "Backup FAILED"
    exit 1
fi

# Cleanup old backups (>7 days)
DELETED=$(find "$BACKUP_DIR" -type f -name "*.sql.gz" -mtime +$RETENTION_DAYS -delete -print | wc -l)
if [ "$DELETED" -gt 0 ]; then
    log "Cleaned $DELETED old backups"
fi

# Show total size
TOTAL=$(du -sh "$BACKUP_DIR" | cut -f1)
log "Total backup dir size: $TOTAL"
log "=== Backup END ==="
SCRIPT_EOF

sudo chmod +x "$BACKUP_SCRIPT"
sudo chown solop:solop "$BACKUP_SCRIPT"
echo "  OK: $BACKUP_SCRIPT (executable)"

# ==================================================================
# STEP 3: Setup cron job
# ==================================================================
echo ""
echo "[3/4] Setup cron job daily 3AM"

# Add to solop crontab (idempotent - remove old, add new)
(crontab -l 2>/dev/null | grep -v "$BACKUP_SCRIPT"; echo "$CRON_TIME $BACKUP_SCRIPT") | crontab -

echo "  OK: Cron job added"
echo "  Current crontab:"
crontab -l | grep -E "(db-backup|BACKUP)" || echo "    (check crontab -l)"

# ==================================================================
# STEP 4: Test run
# ==================================================================
echo ""
echo "[4/4] Test backup - run 1 time now"
bash "$BACKUP_SCRIPT"

LATEST=$(ls -1t "$BACKUP_DIR"/*.sql.gz 2>/dev/null | head -1)
if [ -f "$LATEST" ]; then
    SIZE=$(du -h "$LATEST" | cut -f1)
    echo "  OK: Test backup created: $LATEST ($SIZE)"
else
    echo "  ERR: Test backup failed - check /var/log/db-backup.log"
    exit 1
fi

# ==================================================================
# SUMMARY
# ==================================================================
echo ""
echo "==============================================="
echo "  SETUP COMPLETE"
echo "==============================================="
echo ""
echo "  Backup script: $BACKUP_SCRIPT"
echo "  Backup folder: $BACKUP_DIR"
echo "  Schedule:      Daily 3AM ($CRON_TIME)"
echo "  Retention:     $RETENTION_DAYS days"
echo "  Log file:      /var/log/db-backup.log"
echo ""
echo "  Commands:"
echo "    Manual run:  bash $BACKUP_SCRIPT"
echo "    View logs:   tail -f /var/log/db-backup.log"
echo "    List:        ls -lah $BACKUP_DIR"
echo "    Cron check:  crontab -l | grep db-backup"
echo ""
echo "  === WEEKLY DOWNLOAD (chay tren PowerShell) ==="
echo "  Chua ship - se ship sau khi verify cron chay OK 1-2 ngay"
