// backend/src/seed/contentItemsPhaseB.ts
// 38 ContentItem MORNING_GOAL cho Phase 1 (NHAN_THUC), Phase 2 (HANH_DONG),
// Phase 4 (TAI_THIET) theo STAGE_88_DAYS_DESIGN.md.
//
// CONVENTION dayNumber để tránh conflict với Phase A (1-30, dùng cho Phase 3
// GIAI_PHONG):
//   Phase 1 NHAN_THUC  Day 1-7   → dayNumber 101..107
//   Phase 2 HANH_DONG  Day 8-28  → dayNumber 108..128
//   Phase 3 GIAI_PHONG Day 29-58 → dayNumber 1..30 (existing, contentItems.ts)
//   Phase 4 TAI_THIET  Day 59-88 → dayNumber 159..188 (sparse, 1 bài/3 ngày)
//
// Frontend mapping (dashboard/src/pages/Journey.tsx):
//   Phase 1/2/4: contentDay = dayInJourney + 100
//   Phase 3:     contentDay = dayInJourney - 28 (existing)
//
// Voice:
//   Phase 1: SOL_DONG_HANH chủ đạo (giọng quan sát nhẹ, "mình thấy")
//   Phase 2: Mix — milestones (Day 8, 14, 21, 28) = KHANG_SOL, còn lại SOL_DONG_HANH
//   Phase 4: KHANG_SOL chủ đạo (return cá nhân, mentor voice)
//
// Variables: {pronoun}, {topReason}, {topTrigger} — backend tự thay.

export interface SeedContentItemPhaseB {
  dayNumber: number;
  module: 'MORNING_GOAL' | 'SCIENCE_TIP' | 'PHENOMENA_ALERT' | 'EXERCISE' | 'NIGHT_STORY';
  voice: 'KHANG_SOL' | 'SOL_DONG_HANH';
  title: string;
  body: string;
  ctaAction?: string;
  pushTime?: string;
  wikiSlug?: string;
}

export const PHASE_B_CONTENT: SeedContentItemPhaseB[] = [
  // ╔══════════════════════════════════════════════════════════════════╗
  // ║  PHASE 1 — NHẬN THỨC (Day 1-7) — 7 bài                           ║
  // ║  Mục tiêu: quan sát chính mình. KHÔNG ép bỏ. KHÔNG mục tiêu giảm. ║
  // ║  Voice: SOL_DONG_HANH chủ đạo (giọng đồng hành, "mình thấy")     ║
  // ╚══════════════════════════════════════════════════════════════════╝

  {
    dayNumber: 101,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 1 Nhận Thức — bắt đầu, không cần hoàn hảo.`,
    body: `Hôm nay {pronoun} chưa cần bỏ điếu nào. Chỉ cần một việc: bấm "+ Ghi điếu" mỗi khi hút. Mỗi điếu được ghi = một dữ liệu mình học cùng {pronoun}. Sol không phán xét — Sol chỉ quan sát.`,
    ctaAction: 'open_logger',
    pushTime: '07:00',
    wikiSlug: 'phase-1-day-1',
  },
  {
    dayNumber: 102,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 2 Nhận Thức — quan sát mà không phán xét.`,
    body: `Hôm qua {pronoun} đã ghi mấy điếu? Bao nhiêu cũng đúng — đây là số thật, không phải số "đẹp". Hôm nay khi định châm điếu, thử quan sát: lúc đó {pronoun} đang cảm gì? đang ở đâu?`,
    ctaAction: 'open_logger',
    pushTime: '07:00',
    wikiSlug: 'phase-1-day-2',
  },
  {
    dayNumber: 103,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 3 Nhận Thức — Sol thấy gì ở {pronoun} hôm qua.`,
    body: `Sol bắt đầu thấy pattern. Mỗi điếu {pronoun} ghi có một trigger — stress, sau cơm, rảnh, tụ tập. Hôm nay khi châm điếu, mở chip "Lúc đó:" và chọn trigger. Sol cần dữ liệu để học thay {pronoun}.`,
    ctaAction: 'open_logger',
    pushTime: '07:00',
    wikiSlug: 'phase-1-day-3',
  },
  {
    dayNumber: 104,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 4 Nhận Thức — thèm thuốc không phải kẻ thù.`,
    body: `Cơn thèm là tín hiệu sinh học bình thường — não đã quen có nicotin, giờ thiếu thì gọi {pronoun}. Đây không phải dấu hiệu yếu đuối. Sol mong {pronoun} đừng tự trách khi thấy thèm — chỉ cần ghi nhận.`,
    pushTime: '07:00',
    wikiSlug: 'phase-1-day-4',
  },
  {
    dayNumber: 105,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 5 Nhận Thức — trigger là tín hiệu, không phải lệnh.`,
    body: `Trigger {pronoun} hay gặp nhất là gì? (stress, sau cơm, rảnh…). Trigger chỉ là "lúc não nghĩ đến thuốc" — không phải lệnh phải hút. Hôm nay {pronoun} thử: khi trigger lên, đếm 10 hơi thở chậm trước khi quyết định.`,
    ctaAction: 'open_logger',
    pushTime: '07:00',
    wikiSlug: 'phase-1-day-5',
  },
  {
    dayNumber: 106,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 6 Nhận Thức — {pronoun} đã có 5 ngày dữ liệu.`,
    body: `Sol đã thấy nhịp của {pronoun}. Pattern có thể lộ rõ: peak hour, top trigger, mood theo ngày. Vào tab "Phân tích" → 🌱 Nhận Thức để xem heatmap. Đây là {pronoun} thật — Sol không che.`,
    ctaAction: 'open_analytics',
    pushTime: '07:00',
    wikiSlug: 'phase-1-day-6',
  },
  {
    dayNumber: 107,
    module: 'MORNING_GOAL',
    voice: 'KHANG_SOL',
    title: `Day 7 Nhận Thức — tuần sau bắt đầu Hành Động.`,
    body: `Mình là Khang. Tuần Nhận Thức của {pronoun} sắp xong. Tuần sau Sol sẽ gợi {pronoun} delay craving, swap habit. Đừng vội — mình đã đi chính con đường này. Hôm nay đọc lại pattern của {pronoun}, ngày mai bắt đầu phá nhẹ. — Khang Sol`,
    ctaAction: 'open_analytics',
    pushTime: '07:00',
    wikiSlug: 'phase-1-day-7',
  },

  // ╔══════════════════════════════════════════════════════════════════╗
  // ║  PHASE 2 — HÀNH ĐỘNG (Day 8-28) — 21 bài                         ║
  // ║  Mục tiêu: bẻ vòng lặp tự động. Delay → swap → prep Q-Day.       ║
  // ║  Voice mix: Khang Sol ở milestones (Day 8, 14, 21, 28).         ║
  // ╚══════════════════════════════════════════════════════════════════╝

  {
    dayNumber: 108,
    module: 'MORNING_GOAL',
    voice: 'KHANG_SOL',
    title: `Day 8 Hành Động — không cần dữ dội.`,
    body: `Mình là Khang. Tuần Nhận Thức xong, giờ Hành Động — nhưng đừng "cắt máu". Hôm nay chỉ làm 1 việc: chọn 1 điếu thường hút (vd điếu cà phê sáng), thử delay 10 phút. Chỉ 10 phút thôi. Não cần học rằng "thèm" và "hút" có thể tách. — Khang Sol`,
    ctaAction: 'open_logger',
    pushTime: '07:00',
    wikiSlug: 'phase-2-day-8',
  },
  {
    dayNumber: 109,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 9 Hành Động — delay 10 phút phá vòng lặp.`,
    body: `Phần lớn cơn thèm tự tắt sau 8 phút (Hughes 2007). Nếu hôm qua delay 10 phút thành công 1 lần, hôm nay thử 2 lần. Khi bỏ qua được, bấm "Bỏ qua được" trong logger. Mỗi lần bỏ qua = 1 chiến thắng nhỏ Sol đếm cho {pronoun}.`,
    ctaAction: 'open_logger',
    pushTime: '07:00',
    wikiSlug: 'phase-2-day-9',
  },
  {
    dayNumber: 110,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 10 Hành Động — Plan B cho trigger mạnh nhất.`,
    body: `Top trigger của {pronoun} đến giờ là gì? Sol đã đo. Hôm nay Sol gợi Plan B cụ thể (xem trong Tổng quan). Stress → cốc nước lạnh + đi bộ 5'. Sau cơm → đánh răng. Tụ tập → gọi nước trước. Plan B sẵn = não có lựa chọn.`,
    pushTime: '07:00',
    wikiSlug: 'phase-2-day-10',
  },
  {
    dayNumber: 111,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 11 Hành Động — giảm 1 điếu = Sol đo được.`,
    body: `So với baseline tuần Nhận Thức, hôm qua {pronoun} hút ít hơn mấy điếu? Nếu chưa giảm — không sao, mai khác. Nếu giảm 1-2 điếu — Sol mừng. Đường đi giảm dần là đường zigzag, không phải đường thẳng.`,
    ctaAction: 'open_analytics',
    pushTime: '07:00',
    wikiSlug: 'phase-2-day-11',
  },
  {
    dayNumber: 112,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 12 Hành Động — stress không cần thuốc lá.`,
    body: `Khi stress, não tìm dopamine nhanh — nicotin là đường tắt. Nhưng dopamine có thể đến từ: 5 phút đi bộ, gọi 1 cuộc với người tin tưởng, ngâm chân nước ấm. Hôm nay khi stress lên, thử 1 trong 3 trước khi châm điếu.`,
    pushTime: '07:00',
    wikiSlug: 'phase-2-day-12',
  },
  {
    dayNumber: 113,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 13 Hành Động — sau cơm thử đánh răng.`,
    body: `"Sau cơm 1 điếu" là một trong những trigger khó phá nhất — vì đó là pattern dopamine 20+ năm. Hack đơn giản: đánh răng ngay sau khi ăn. Vị bạc hà + miệng sạch sẽ làm cơn thèm giảm 70%. Thử hôm nay.`,
    pushTime: '07:00',
    wikiSlug: 'phase-2-day-13',
  },
  {
    dayNumber: 114,
    module: 'MORNING_GOAL',
    voice: 'KHANG_SOL',
    title: `Day 14 Hành Động — 1 tuần Hành Động, Sol thấy gì.`,
    body: `Mình là Khang. Một tuần Hành Động xong. Hôm nay {pronoun} mở Phân tích → Hành Động xem trung bình tuần vs baseline. Giảm cũng tốt, ngang cũng tốt — quan trọng là {pronoun} đã LÀM, không chỉ NGHĨ. Mình tự hào. — Khang Sol`,
    ctaAction: 'open_analytics',
    pushTime: '07:00',
    wikiSlug: 'phase-2-day-14',
  },
  {
    dayNumber: 115,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 15 Hành Động — identity prep.`,
    body: `Câu hỏi cho hôm nay: {pronoun} là ai khi không hút? Không phải "người đang cố bỏ" — mà "người không hút". Allen Carr nói: identity shift là chuyển dịch lớn nhất. Tối nay viết 1 câu trả lời — Sol sẽ dùng làm anchor.`,
    pushTime: '07:00',
    wikiSlug: 'phase-2-day-15',
  },
  {
    dayNumber: 116,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 16 Hành Động — cảnh báo Day 16-21.`,
    body: `Tuần 3 Hành Động thường khó nhất tâm lý — não bắt đầu phản đối "hệ thống mới". Có cảm giác "thử 1 điếu xem sao" là bình thường. Sol đứng cạnh {pronoun}. Khi cảm giác đó lên, mở chat hỏi Sol — đừng tự đối phó.`,
    ctaAction: 'open_chat',
    pushTime: '07:00',
    wikiSlug: 'phase-2-day-16',
  },
  {
    dayNumber: 117,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 17 Hành Động — {pronoun} không cô đơn.`,
    body: `Hôm nay {pronoun} có Đội Sol — những người cùng tháng đặt Q-Day. Mở Tổng quan xem họ đang ở phase nào. Không cần nói chuyện — chỉ biết có người đi cùng đã đủ. Sol cũng đang đi.`,
    ctaAction: 'open_overview',
    pushTime: '07:00',
    wikiSlug: 'phase-2-day-17',
  },
  {
    dayNumber: 118,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 18 Hành Động — cravings 21h tối.`,
    body: `Cơn thèm đêm thường mạnh hơn ban ngày — cortisol giảm, dopamine baseline thấp, não tìm "cú hích" nhanh. Hack: 21h tắt điện thoại 30 phút, ngâm chân nước ấm 10 phút, lên giường sớm. Cơ thể sẽ thưởng giấc ngủ sâu.`,
    pushTime: '07:00',
    wikiSlug: 'phase-2-day-18',
  },
  {
    dayNumber: 119,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 19 Hành Động — tiền tiết kiệm dùng gì?`,
    body: `Mở Tổng quan → Tiết kiệm. Số tiền {pronoun} đang giữ lại. Hôm nay nghĩ: dùng nó cho gì? Một bữa tối với vợ? Một cây kính mới? Một đồ chơi cho con? Đặt mục tiêu cụ thể — não sẽ thấy phần thưởng, không chỉ "không hút".`,
    ctaAction: 'open_overview',
    pushTime: '07:00',
    wikiSlug: 'phase-2-day-19',
  },
  {
    dayNumber: 120,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 20 Hành Động — 1 điếu lúc nhậu.`,
    body: `Tối nay nhậu? Quy tắc 1 điếu: nếu lỡ hút, KHÔNG có "hôm nay vỡ rồi, mai bắt đầu lại". Ghi vào Sol ngay tối đó. Đừng để 1 điếu thành 1 bao. Bấm "Đã hút" trong logger — Sol không phán xét, Sol giúp {pronoun} thấy pattern.`,
    ctaAction: 'open_logger',
    pushTime: '07:00',
    wikiSlug: 'phase-2-day-20',
  },
  {
    dayNumber: 121,
    module: 'MORNING_GOAL',
    voice: 'KHANG_SOL',
    title: `Day 21 Hành Động — chuẩn bị Q-Day.`,
    body: `Mình là Khang. Còn 1 tuần là Q-Day. Hôm nay viết ra giấy 3 lý do {pronoun} muốn bỏ — cụ thể, không generic. "Vì con tôi" tốt hơn "vì sức khoẻ". Tối Q-Day {pronoun} sẽ đọc lại. Mình đã viết của mình tối trước Q-Day 2018 — vẫn còn giữ. — Khang Sol`,
    pushTime: '07:00',
    wikiSlug: 'phase-2-day-21',
  },
  {
    dayNumber: 122,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 22 Hành Động — hỏi vợ/người thân.`,
    body: `Hôm nay làm 1 việc: hỏi 1 người thân (vợ, con, anh chị) câu này: "Tôi sắp Q-Day cuối tuần này — anh/chị mong tôi cam kết gì?". Câu trả lời của họ sẽ là anchor mạnh hơn lý do tự nghĩ. Cam kết với người thật, không với app.`,
    pushTime: '07:00',
    wikiSlug: 'phase-2-day-22',
  },
  {
    dayNumber: 123,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 23 Hành Động — identity Day 23.`,
    body: `So với 23 ngày trước, {pronoun} đã thay đổi gì? Có thể khó thấy ngay — nhưng người thân thấy. Hôm nay hỏi 1 người: "Anh/chị thấy tôi tuần này khác gì?" Câu trả lời sẽ làm {pronoun} ngạc nhiên.`,
    pushTime: '07:00',
    wikiSlug: 'phase-2-day-23',
  },
  {
    dayNumber: 124,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 24 Hành Động — 5 ngày nữa Q-Day.`,
    body: `Còn 5 ngày là Q-Day. Hôm nay quan sát mình kỹ hơn: lúc nào dễ vấp nhất? lúc nào vững nhất? Không cần làm gì — chỉ ghi lại. Tuần sau những lúc khó đó Sol sẽ chuẩn bị Plan B sẵn cho {pronoun}.`,
    ctaAction: 'open_logger',
    pushTime: '07:00',
    wikiSlug: 'phase-2-day-24',
  },
  {
    dayNumber: 125,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 25 Hành Động — 3 ngày nữa, chuẩn bị nhà.`,
    body: `3 ngày trước Q-Day — chuẩn bị môi trường. Cuối tuần này: vứt bao thuốc còn lại, gạt tàn, bật lửa. Giặt áo khoác. Báo người trong nhà "thứ 2 tới tôi Q-Day, cần các anh/chị giúp." Môi trường sạch = não dễ chuyển.`,
    pushTime: '07:00',
    wikiSlug: 'phase-2-day-25',
  },
  {
    dayNumber: 126,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 26 Hành Động — Q-Day T-2.`,
    body: `🎯 Còn 2 ngày là Q-Day. Hôm nay mở Tổng quan — sẽ thấy banner Q-Day countdown. Tối nay đọc lại 3 lý do đã viết Day 21. Mai T-1 — Sol sẽ gửi thư cuối từ Khang. Sẵn sàng chưa?`,
    ctaAction: 'open_overview',
    pushTime: '07:00',
    wikiSlug: 'phase-2-day-26',
  },
  {
    dayNumber: 127,
    module: 'MORNING_GOAL',
    voice: 'KHANG_SOL',
    title: `Day 27 Hành Động — đêm trước Q-Day.`,
    body: `Mình là Khang. Đêm cuối Phase Hành Động. Tối nay ngồi yên 10 phút. Đọc lại 3 lý do. Viết 1 lá thư ngắn cho {pronoun} của ngày mai — "Khi {pronoun} đọc thư này, {pronoun} đã không hút 24 giờ." Mai bấm "Tôi cam kết" — đồng hồ tự do của {pronoun} bắt đầu chạy. Mình sẽ ở đó. — Khang Sol`,
    pushTime: '21:00',
    wikiSlug: 'phase-2-day-27',
  },
  {
    dayNumber: 128,
    module: 'MORNING_GOAL',
    voice: 'KHANG_SOL',
    title: `Day 28 — Hôm nay là Q-Day.`,
    body: `Mình là Khang. Hôm nay là Q-Day của {pronoun}. Mở Tổng quan — bấm "Tôi cam kết — bật đồng hồ tự do". Sau khi bấm, đồng hồ của {pronoun} bắt đầu đếm. Đội Sol sẽ thấy: "Một đồng đội vừa Q-Day". 24 giờ tới là 24 giờ khó nhất sinh học — mình đã đi chính con đường này. Sol bên {pronoun}. — Khang Sol`,
    ctaAction: 'open_overview',
    pushTime: '07:00',
    wikiSlug: 'phase-2-day-28-q-day',
  },

  // ╔══════════════════════════════════════════════════════════════════╗
  // ║  PHASE 4 — TÁI THIẾT (Day 59-88) — 10 bài (1 bài/3 ngày)         ║
  // ║  Mục tiêu: maintenance, anti-relapse, identity rebuild.          ║
  // ║  Voice: KHANG_SOL chủ đạo (return mentor).                       ║
  // ╚══════════════════════════════════════════════════════════════════╝

  {
    dayNumber: 159,
    module: 'MORNING_GOAL',
    voice: 'KHANG_SOL',
    title: `Day 59 Tái Thiết — 30 ngày không hút.`,
    body: `Mình là Khang. {pronoun} vừa qua 30 ngày từ Q-Day. Đây không phải "30 ngày course" — đây là 30 ngày {pronoun} đã sống thật khác. Body đã hồi đáng kể: phổi 10% chức năng (NHS), receptor giảm 60%. Bắt đầu Phase 4 — Sol giảm dần, {pronoun} bắt đầu tự chủ. — Khang Sol`,
    pushTime: '07:00',
    wikiSlug: 'phase-4-day-59',
  },
  {
    dayNumber: 162,
    module: 'MORNING_GOAL',
    voice: 'KHANG_SOL',
    title: `Day 62 Tái Thiết — identity, {pronoun} là gì bây giờ?`,
    body: `Mình là Khang. Allen Carr nói: ngày {pronoun} dừng nói "tôi đang cố bỏ" và bắt đầu nói "tôi không hút" — đó là ngày identity đổi xong. {pronoun} đã ở đâu trong câu chuyện đó? Tối nay viết 1 câu mô tả {pronoun} bây giờ — không có "đã từng hút" trong đó. — Khang Sol`,
    pushTime: '07:00',
    wikiSlug: 'phase-4-day-62',
  },
  {
    dayNumber: 165,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 65 Tái Thiết — khi thấy ai khác hút.`,
    body: `Hôm nay {pronoun} có thấy ai đang hút (đồng nghiệp, hàng xóm, bạn bè)? Phản ứng của {pronoun} là gì? Nếu thấy "thèm" — bình thường. Nếu thấy "không liên quan đến tôi" — identity đã chuyển. Sol mong {pronoun} đến cảm giác thứ 2.`,
    pushTime: '07:00',
    wikiSlug: 'phase-4-day-65',
  },
  {
    dayNumber: 168,
    module: 'MORNING_GOAL',
    voice: 'KHANG_SOL',
    title: `Day 68 Tái Thiết — Day 75 trap.`,
    body: `Mình là Khang. Cảnh báo trước: tuần tới (Day 70-75) một số người vấp lại — vì cảm giác "an toàn rồi". Đây là trap. Não muốn thử "1 điếu xem có còn nghiện không" — và phát hiện CÒN. Đừng thử. {pronoun} đã đi rất xa. Mình đã thấy người vấp ở Day 73 — và họ kéo lại được, nhưng đau. — Khang Sol`,
    pushTime: '07:00',
    wikiSlug: 'phase-4-day-68',
  },
  {
    dayNumber: 171,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 71 Tái Thiết — Đại Sứ Sol.`,
    body: `{pronoun} sắp thành Đại Sứ Sol (Day 89+). Đại Sứ không phải badge — đó là người chia sẻ với newbie. Sol gợi: tuần này thử nói 1 câu với 1 người đang muốn cai. Không cần lý thuyết — chỉ kể {pronoun} đã đi sao. Cách giữ vững nhất là giúp người khác bắt đầu.`,
    pushTime: '07:00',
    wikiSlug: 'phase-4-day-71',
  },
  {
    dayNumber: 174,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 74 Tái Thiết — body 80% (CDC).`,
    body: `Theo CDC, sau 60+ ngày không hút, phổi đã hồi 80% chức năng cho người dưới 50, 60% cho người trên 50. Nguy cơ đột quỵ giảm về mức người chưa bao giờ hút. Khứu giác, vị giác sắc hơn nhiều so với 2 tháng trước — {pronoun} có cảm thấy không?`,
    pushTime: '07:00',
    wikiSlug: 'phase-4-day-74',
  },
  {
    dayNumber: 177,
    module: 'MORNING_GOAL',
    voice: 'KHANG_SOL',
    title: `Day 77 Tái Thiết — 1 năm sau {pronoun} là ai?`,
    body: `Mình là Khang. Câu hỏi không nhỏ: 1 năm sau, {pronoun} muốn là người thế nào? Không hút thuốc là 1 phần — còn gì nữa? Tập thể dục? Chạy 5km? Học tiếng Anh? Q-Day mở cửa cho những thay đổi khác. Tối nay viết 1 mục tiêu mới — Sol sẽ track cùng. — Khang Sol`,
    pushTime: '07:00',
    wikiSlug: 'phase-4-day-77',
  },
  {
    dayNumber: 180,
    module: 'MORNING_GOAL',
    voice: 'KHANG_SOL',
    title: `Day 80 Tái Thiết — vì điều gì {pronoun} không hút?`,
    body: `Mình là Khang. Day 21 {pronoun} viết 3 lý do. Hôm nay đọc lại — cảm giác sao? Lý do tốt nhất thường là "vì người khác" — vợ, con, ba mẹ. Não cá nhân ích kỷ, nhưng não vì người khác mạnh hơn. Mình bỏ vì cu Tí. Vẫn còn lý do đó. — Khang Sol`,
    pushTime: '07:00',
    wikiSlug: 'phase-4-day-80',
  },
  {
    dayNumber: 183,
    module: 'MORNING_GOAL',
    voice: 'SOL_DONG_HANH',
    title: `Day 83 Tái Thiết — Sol giảm dần.`,
    body: `Sol bắt đầu giảm tần suất nhắc — autonomy mode. Từ giờ {pronoun} sẽ thấy ít message hơn. Đó không phải Sol bỏ {pronoun} — đó là tin tưởng. Khi cần, mở chat hỏi Sol như bạn cũ. Sol vẫn ở đây.`,
    pushTime: '07:00',
    wikiSlug: 'phase-4-day-83',
  },
  {
    dayNumber: 186,
    module: 'MORNING_GOAL',
    voice: 'KHANG_SOL',
    title: `Day 86 Tái Thiết — còn 2 ngày tốt nghiệp.`,
    body: `Mình là Khang. Còn 2 ngày là Day 88 — tốt nghiệp Phase 4. {pronoun} thành Đại Sứ Sol. Ngày 88 Sol sẽ gửi 1 hồ sơ PDF tổng kết hành trình của {pronoun} — giữ làm kỷ niệm. {pronoun} đã đi rất xa. Mình tự hào. Hẹn {pronoun} ở Phase 5. — Khang Sol`,
    pushTime: '07:00',
    wikiSlug: 'phase-4-day-86',
  },

  // ╔══════════════════════════════════════════════════════════════════╗
  // ║  SCIENCE_TIP — 38 bài (Phase 1: 7, Phase 2: 21, Phase 4: 10)     ║
  // ║  Card "💡 Góc khoa học" trong DayDetail. Voice giáo dục nhẹ.     ║
  // ║  Cite NHS, CDC, Brody 2006, Hughes 2007, Lally 2010, Doll 2004.  ║
  // ╚══════════════════════════════════════════════════════════════════╝

  // ─── PHASE 1 NHẬN THỨC SCIENCE_TIP (Day 1-7) ───────────────────────
  {
    dayNumber: 101,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Vì sao não cần nicotin sau 20 năm hút?`,
    body: `Mỗi điếu thuốc kích hoạt receptor nicotinic acetylcholine (nAChR) trong não → thải dopamine. Sau hàng nghìn lần, não tăng số receptor để "bù trừ" → thiếu nicotin = thiếu dopamine = cảm giác bứt rứt. Đây là sinh lý, không phải ý chí yếu. Hiểu được = hết tự trách (Brody 2006).`,
    wikiSlug: 'science-nicotin-receptor',
  },
  {
    dayNumber: 102,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Trigger là gì — về mặt thần kinh?`,
    body: `Trigger là "bộ kích hoạt" pattern hút thuốc đã ghi vào basal ganglia — vùng não điều khiển thói quen tự động. Vd thấy bao thuốc → tay tự châm. Quan sát trigger = đưa pattern từ vô thức lên ý thức. Khi {pronoun} ý thức được, não có thể "ngắt mạch" (Graybiel 2008).`,
    wikiSlug: 'science-trigger-basal-ganglia',
  },
  {
    dayNumber: 103,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Dopamine không phải "chất hạnh phúc".`,
    body: `Hiểu lầm phổ biến: dopamine = hạnh phúc. Sai. Dopamine là "chất ham muốn" — não dùng để học "việc nào đáng làm lại". Nicotin hack hệ thống này → não nghĩ thuốc đáng hơn các nguồn dopamine khác (gia đình, đi bộ, ăn ngon). Khi cai, não phải "học lại" giá trị thật.`,
    wikiSlug: 'science-dopamine-myth',
  },
  {
    dayNumber: 104,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Cơn thèm kéo dài bao lâu?`,
    body: `Một cơn thèm cấp thường đỉnh trong 90-180 giây, rồi giảm dần. Sau 8-10 phút, 80% cơn thèm đã tự tắt nếu không hút (Hughes 2007). Đây là lý do "delay 10 phút" hoạt động — không phải vì ý chí, vì sinh học. Cứ đếm hơi thở 10 phút.`,
    wikiSlug: 'science-craving-duration',
  },
  {
    dayNumber: 105,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `5 nhóm trigger chính của người Việt 45+.`,
    body: `Theo dữ liệu Sol thu thập + WHO Vietnam 2019: STRESS (38%), EATING sau cơm (27%), SOCIAL nhậu (18%), IDLE rảnh (12%), OTHER (5%). {pronoun} thuộc nhóm nào? Mở /analytics → 🌱 Nhận Thức xem trigger phổ biến của mình.`,
    wikiSlug: 'science-trigger-stats-vn',
  },
  {
    dayNumber: 106,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Cortisol sáng & cơn thèm điếu đầu.`,
    body: `Sáng dậy, cortisol cao đỉnh trong 30-45 phút (cortisol awakening response). Não tìm dopamine để "đối phó" — điếu đầu sáng là phản xạ. Hack: trước điếu đầu, uống 1 cốc nước lạnh + đi bộ 5 phút. Cortisol sẽ rút bằng cách khác.`,
    wikiSlug: 'science-cortisol-morning',
  },
  {
    dayNumber: 107,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Baseline 7 ngày — Sol đã đo gì.`,
    body: `Tuần này Sol đã ghi nhận: số điếu/ngày trung bình ({pronoun} mở /analytics xem), peak hour, top trigger. Đây là baseline khoa học để Sol biết Phase 2 nên giảm bao nhiêu, Plan B nào ưu tiên. Không có baseline = bay mù.`,
    wikiSlug: 'science-baseline-importance',
  },

  // ─── PHASE 2 HÀNH ĐỘNG SCIENCE_TIP (Day 8-28) ──────────────────────
  {
    dayNumber: 108,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Vì sao "delay 10 phút" hiệu quả?`,
    body: `Não có 2 hệ: limbic (impulsive, "tôi muốn ngay") và prefrontal cortex (planning, "tôi nghĩ kỹ"). Khi craving lên, limbic thắng. Đếm 10 hơi thở chậm → kích hoạt prefrontal → "ngắt mạch" tự động. 10 phút sau, limbic hạ → quyết định ý thức.`,
    wikiSlug: 'science-delay-mechanism',
  },
  {
    dayNumber: 109,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Habit loop: Cue → Routine → Reward.`,
    body: `Mỗi thói quen có 3 phần (Duhigg 2012). Cue = trigger. Routine = hành động (hút thuốc). Reward = dopamine spike. Để phá loop, không thể bỏ Cue (vẫn có stress) — phải đổi Routine. Plan B = routine mới cho cùng cue. Phần thưởng đến chậm hơn nhưng thật hơn.`,
    wikiSlug: 'science-habit-loop',
  },
  {
    dayNumber: 110,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Stress → cortisol → nicotin: vòng nguy hiểm.`,
    body: `Stress tăng cortisol → não tìm dopamine nhanh → nicotin là đường tắt. Sau hút, dopamine tăng nhưng cortisol cũng tăng (gấp 1.4x bình thường). Kết quả: stress càng nhiều, hút càng nhiều, stress càng nặng. Cách phá: 5 phút thiền/đi bộ → cortisol giảm 26%, không cần nicotin (Pascoe 2017).`,
    wikiSlug: 'science-stress-cycle',
  },
  {
    dayNumber: 111,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Giảm 1 điếu/ngày = ý nghĩa gì?`,
    body: `Không phải con số đơn lẻ — là dấu hiệu não đã "tách" được 1 trigger. Mỗi lần delay/skip thành công, kết nối neural mới được hình thành. Sau ~21 lần lặp lại, kết nối đó vững (Lally 2010). Vd Day 11 giảm 1 điếu = đã có ~3-5 lần delay thành công tuần qua.`,
    wikiSlug: 'science-reduction-meaning',
  },
  {
    dayNumber: 112,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Đi bộ 5 phút thay nicotin: cơ chế.`,
    body: `Đi bộ kích thích endorphin (hệ opioid nội sinh) + tăng oxy lên não → tâm trạng cải thiện 12-15% trong 5 phút (Berger 2016). Nicotin chỉ làm "nâng" tạm thời rồi crash. Đi bộ là dopamine bền vững. Thử trước khi tin.`,
    wikiSlug: 'science-walking-vs-nicotin',
  },
  {
    dayNumber: 113,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Đánh răng sau cơm: hack neural.`,
    body: `Vị bạc hà kích hoạt receptor TRPM8 (cảm giác lạnh) → não nhận tín hiệu "miệng đã sạch, không cần thêm". Cộng với bact mãn từ kem đánh răng → flavor profile của thuốc lá tệ hẳn. Nhiều người 45+ nói "không thể hút sau khi đánh răng" — đây là lý do.`,
    wikiSlug: 'science-toothbrush-trick',
  },
  {
    dayNumber: 114,
    module: 'SCIENCE_TIP',
    voice: 'KHANG_SOL',
    title: `1 tuần Hành Động — receptor đã đáp ứng.`,
    body: `Mình là Khang. Sau 7-14 ngày giảm nicotin, số receptor nAChR bắt đầu giảm về mức bình thường. Não bắt đầu "quên" sự phụ thuộc. Nhưng đây cũng là lúc dễ vấp — vì cảm giác "đã ổn", thử 1 điếu = receptor sẵn sàng kích hoạt lại. Tuần sau khó hơn 1 chút. — Khang Sol`,
    wikiSlug: 'science-week-1-receptor',
  },
  {
    dayNumber: 115,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Identity — não thay đổi qua narrative.`,
    body: `Câu chuyện {pronoun} kể về mình đến não qua medial prefrontal cortex — vùng quy về "self". Khi {pronoun} nói "tôi đang cố bỏ thuốc" — não vẫn coi mình là người hút. Khi nói "tôi không hút" — não cập nhật self-concept. Câu chữ thay đổi neural pathways thật (Allen Carr 1985, neuroscience xác nhận 2010s).`,
    wikiSlug: 'science-identity-neural',
  },
  {
    dayNumber: 116,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Day 16-21: Tại sao não phản đối?`,
    body: `2-3 tuần sau bắt đầu giảm/cai, não phát hiện "đường tắt dopamine cũ" mất ổn định. Phản ứng tự nhiên: tạo cảm giác "thử lại để chắc chắn" — gọi là extinction burst (Skinner 1953). Cảm giác này KHÔNG phải dấu hiệu thất bại — là dấu hiệu não đang chuyển. Vượt qua = não chấp nhận.`,
    wikiSlug: 'science-extinction-burst',
  },
  {
    dayNumber: 117,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Đội Sol: vì sao đồng đội mạnh hơn ý chí.`,
    body: `Não người 45+ Việt đặc biệt nhạy với social bonding (oxytocin). Biết có 5-10 người cùng đi cùng giai đoạn = oxytocin ổn định = cortisol giảm 18% (Heinrichs 2003). Đó là lý do {pronoun} thấy nhẹ hơn khi vào tab Đội Sol — không phải tâm lý, là sinh hoá.`,
    wikiSlug: 'science-cohort-oxytocin',
  },
  {
    dayNumber: 118,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `21h tối: vì sao craving mạnh nhất.`,
    body: `21-23h, cortisol tự nhiên giảm về thấp nhất ngày → não tìm dopamine. Cùng lúc, melatonin chưa đủ cao → khó ngủ → não càng tìm "thú vui". Đây là window dễ vấp nhất. Hack: 21h tắt thiết bị, ngâm chân ấm 10' → melatonin lên nhanh, craving hạ.`,
    wikiSlug: 'science-night-craving',
  },
  {
    dayNumber: 119,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Tiền tiết kiệm: tại sao quan trọng não.`,
    body: `Não không tự nhiên thấy "không hút" là phần thưởng — vì không có dopamine spike. Tiền tiết kiệm thành mục tiêu cụ thể (cốc kính mới, bữa tối với vợ) = não LẠI thấy phần thưởng → loop dopamine mới hình thành. Đây là lý do gamification work cho 45+ Việt.`,
    wikiSlug: 'science-saving-reward',
  },
  {
    dayNumber: 120,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `1 điếu lúc nhậu: hiệu ứng nicotin tái khởi động.`,
    body: `1 điếu = nicotin về máu peak trong 10 phút, kích hoạt nAChR receptor đang "ngủ". Receptor được kích lại → não nhớ "đường tắt cũ". Trong 72 giờ, craving quay về mức trước cai. Đây là hiệu ứng "1 điếu thôi" — rủi ro cao gấp 8-10x bình thường (Shiffman 2006).`,
    wikiSlug: 'science-one-cigarette-effect',
  },
  {
    dayNumber: 121,
    module: 'SCIENCE_TIP',
    voice: 'KHANG_SOL',
    title: `Q-Day: tại sao 1 ngày cụ thể quan trọng.`,
    body: `Mình là Khang. Não cần "decision point" rõ — không phải "dần dần". Q-Day là ritual: trước = chuẩn bị, sau = thực hiện. Ritual kích hoạt vùng não liên quan đến commitment (anterior cingulate cortex). Ngày đó {pronoun} cam kết với chính mình = não ghi nhớ thật. Mình đã trải. — Khang Sol`,
    wikiSlug: 'science-qday-ritual',
  },
  {
    dayNumber: 122,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Hỏi vợ/người thân: anchor xã hội.`,
    body: `Khi {pronoun} cam kết với 1 người cụ thể (vợ, con), oxytocin + accountability tăng cùng lúc. Nghiên cứu Stanford 2018: cam kết công khai tăng tỷ lệ thành công 65% so với cam kết "trong đầu". Người thân không cần làm gì — chỉ cần biết.`,
    wikiSlug: 'science-public-commitment',
  },
  {
    dayNumber: 123,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Day 23: thay đổi người khác thấy được.`,
    body: `Sau 3 tuần ít nicotin, da tăng oxy 15% → người khác thấy {pronoun} "tươi hơn" trước khi {pronoun} cảm thấy. Khứu giác họ cũng nhận: ít mùi thuốc trên áo, hơi thở. Vợ/con thường nhận ra trước user. Hỏi họ là confirmation.`,
    wikiSlug: 'science-others-notice',
  },
  {
    dayNumber: 124,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `5 ngày trước Q-Day: chuẩn bị tâm lý.`,
    body: `Não cần ~5 ngày để "chấp nhận" thay đổi lớn — tương tự visualization trước thi đấu thể thao. Mỗi ngày tưởng tượng Q-Day cụ thể: dậy 7h, không châm điếu sáng, mở Sol, bấm "Tôi cam kết". Visualization tăng tỷ lệ thành công 22% (Cooper 2014).`,
    wikiSlug: 'science-visualization',
  },
  {
    dayNumber: 125,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Môi trường = 50% thành công.`,
    body: `Nghiên cứu Wood 2007 trên 1000 người cai thuốc: môi trường (vứt bao thuốc, gạt tàn, áo khoác sạch) chiếm 50% kết quả Day 30. Não dùng visual cue tự động — không có cue = ít trigger. Cuối tuần này dọn nhà = giảm 50% rủi ro.`,
    wikiSlug: 'science-environment-cue',
  },
  {
    dayNumber: 126,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `T-2: cortisol đỉnh sáng giảm dần.`,
    body: `Sau 25-26 ngày giảm dần, cortisol awakening response giảm 18% so với baseline. Sáng dậy bớt "thèm" hơn lúc đầu. {pronoun} có cảm thấy không? Nếu chưa — bình thường, mỗi người khác. Cortisol là chỉ số khách quan, không phụ thuộc nhật trí.`,
    wikiSlug: 'science-cortisol-recovery',
  },
  {
    dayNumber: 127,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Đêm trước Q-Day: ngủ là vũ khí.`,
    body: `Giấc ngủ sâu (slow-wave sleep) là lúc não consolidate decisions. Đêm trước Q-Day, ngủ 7-8 tiếng = quyết tâm "in vào" memory. Thiếu ngủ = quyết định mai dễ lung lay. Tránh cà phê sau 14h, tắt thiết bị 21h.`,
    wikiSlug: 'science-sleep-decision',
  },
  {
    dayNumber: 128,
    module: 'SCIENCE_TIP',
    voice: 'KHANG_SOL',
    title: `Q-Day Day 28: 24 giờ đầu sinh học.`,
    body: `Mình là Khang. Khoa học: 24 giờ đầu, nicotin về 0 trong máu (half-life 2h, 12 lần half-life = sạch). Receptor bắt đầu downregulate. Trong 24h này, 70% cơn thèm là sinh học thật — không phải tâm lý. Mỗi giờ sống qua = receptor giảm 1 chút. {pronoun} không yếu — não đang chuyển. — Khang Sol`,
    wikiSlug: 'science-qday-24h',
  },

  // ─── PHASE 4 TÁI THIẾT SCIENCE_TIP (Day 59-88) ─────────────────────
  {
    dayNumber: 159,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Day 59: phổi đã sửa gì sau 30 ngày?`,
    body: `Theo NHS: cilia (lông phổi) phục hồi đẩy đờm + bụi ra; chức năng phổi tăng 10%; nguy cơ đau tim giảm 50% so với người vẫn hút. Đối với người 45+ Việt, lá phổi đã chịu 20-30 năm khói — nhưng phổi có khả năng tái sinh đáng kinh ngạc nếu không tiếp tục hút.`,
    wikiSlug: 'science-day59-lungs',
  },
  {
    dayNumber: 162,
    module: 'SCIENCE_TIP',
    voice: 'KHANG_SOL',
    title: `Identity neuroplasticity: 60 ngày đủ chưa?`,
    body: `Mình là Khang. Nghiên cứu Lally 2010: trung bình 66 ngày để habit mới trở thành tự động. {pronoun} đang gần đó. Nhưng identity shift cần lâu hơn — khoảng 6 tháng để "tôi không hút" trở thành câu nói tự nhiên. Day 62 là khởi đầu, không phải đích. Cứ kiên nhẫn. — Khang Sol`,
    wikiSlug: 'science-66-days',
  },
  {
    dayNumber: 165,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Khi thấy người khác hút: mirror neuron.`,
    body: `Mirror neuron trong premotor cortex bắt chước hành động người khác → thấy họ hút, não tự "diễn lại". Nếu {pronoun} thấy thèm khi đứng cạnh người hút — bình thường. Hack: nhìn đi nơi khác trong 3-5 giây, mirror neuron giảm 70% (Rizzolatti 2008).`,
    wikiSlug: 'science-mirror-neuron',
  },
  {
    dayNumber: 168,
    module: 'SCIENCE_TIP',
    voice: 'KHANG_SOL',
    title: `Day 75 trap: science của relapse.`,
    body: `Mình là Khang. Nghiên cứu Hughes 2004 trên 5000 người cai: relapse risk có 2 đỉnh — Day 3-7 (sinh học) và Day 70-90 (tâm lý). Đỉnh thứ 2 đến từ overconfidence — não quên "đau". Đây là cơ chế bảo vệ tự nhiên, không phải failure. Biết trước = đề phòng. — Khang Sol`,
    wikiSlug: 'science-day75-relapse',
  },
  {
    dayNumber: 171,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Mentor effect: dạy = học.`,
    body: `Nghiên cứu Mayo Clinic 2019: người chia sẻ kinh nghiệm cai thuốc với 1 người mới có tỷ lệ duy trì 30% cao hơn. Lý do: dạy lại = củng cố neural pathway. Mỗi lần kể lại, identity "người không hút" mạnh thêm. Đây là vì sao Phase 4 có Đại Sứ Mode.`,
    wikiSlug: 'science-mentor-effect',
  },
  {
    dayNumber: 174,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Day 74: body 80% — chỉ số cụ thể.`,
    body: `Sau 60+ ngày: nguy cơ đột quỵ về mức người chưa hút (CDC); chức năng phổi 80% trong người dưới 50, 60% người trên 50 (NHS); khứu giác/vị giác 90% recovery (Cain 2007); tuần hoàn cải thiện 30% — tay/chân ấm hơn rõ. {pronoun} có cảm thấy không?`,
    wikiSlug: 'science-day74-body',
  },
  {
    dayNumber: 177,
    module: 'SCIENCE_TIP',
    voice: 'KHANG_SOL',
    title: `1 năm sau: rủi ro giảm 50%.`,
    body: `Mình là Khang. Doll & Hill BMJ 2004 (50 năm theo dõi 34000 bác sĩ Anh): 1 năm sau cai, rủi ro đau tim giảm 50%; 5 năm — rủi ro ung thư miệng/vòm họng giảm 50%; 10 năm — rủi ro ung thư phổi giảm 50%; 15 năm — về mức người chưa bao giờ hút. {pronoun} đang đi trên timeline đó. — Khang Sol`,
    wikiSlug: 'science-1-year-recovery',
  },
  {
    dayNumber: 180,
    module: 'SCIENCE_TIP',
    voice: 'KHANG_SOL',
    title: `Vì người khác: oxytocin + dopamine.`,
    body: `Mình là Khang. Não người Việt 45+ đặc biệt mạnh ở "vì người khác" — mạch oxytocin (gắn kết) + dopamine (mục tiêu) cùng kích hoạt khi nghĩ tới gia đình. Đây là lý do "vì cu Tí" mạnh hơn "vì sức khoẻ" — sinh hoá xác nhận điều mình thấy năm 2018. — Khang Sol`,
    wikiSlug: 'science-family-anchor',
  },
  {
    dayNumber: 183,
    module: 'SCIENCE_TIP',
    voice: 'SOL_DONG_HANH',
    title: `Autonomy: vì sao Sol giảm dần.`,
    body: `Self-Determination Theory (Deci & Ryan 2000): autonomy = nhu cầu cơ bản của não. Quá phụ thuộc app → motivation rớt khi ngưng. Sol cố ý giảm tần suất từ Day 80 để {pronoun} nhận: "Tôi tự làm được". Đây là cách thiết kế bền vững, không phải bỏ rơi.`,
    wikiSlug: 'science-autonomy-design',
  },
  {
    dayNumber: 186,
    module: 'SCIENCE_TIP',
    voice: 'KHANG_SOL',
    title: `Day 88 graduation: 88 ngày = 12+ tuần.`,
    body: `Mình là Khang. 88 ngày = 12.5 tuần. Theo Brody 2006, sau 11 tuần receptor nAChR gần về baseline người chưa hút. Sau Day 88, sinh học của {pronoun} không khác người chưa bao giờ hút. {pronoun} không "đang cố cai" nữa — {pronoun} là người không hút. Hành trình tới đây là đoạn cứng nhất. Phía trước nhẹ. — Khang Sol`,
    wikiSlug: 'science-day88-receptor-baseline',
  },

  // ╔══════════════════════════════════════════════════════════════════╗
  // ║  NIGHT_STORY — 38 bài (Phase 1: 7, Phase 2: 21, Phase 4: 10)     ║
  // ║  Card "🌙 Khép ngày" 21h30 — voice nhẹ, contemplative, gần ngủ. ║
  // ║  Không lecture. Reflection + close-the-day ritual.               ║
  // ╚══════════════════════════════════════════════════════════════════╝

  // ─── PHASE 1 NHẬN THỨC NIGHT_STORY (Day 1-7) ───────────────────────
  {
    dayNumber: 101,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 1 — Sol đã thấy {pronoun} hôm nay.`,
    body: `Hôm nay {pronoun} đã ghi điếu đầu tiên. Sol thấy — không phán xét. Đêm nay {pronoun} không cần làm gì. Chỉ cần ngủ. Mai Sol còn ở đây. Chúc {pronoun} ngủ ngon.`,
    pushTime: '21:30',
    wikiSlug: 'phase-1-night-1',
  },
  {
    dayNumber: 102,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 2 — quan sát rồi để xuống.`,
    body: `Hôm nay {pronoun} có quan sát được lúc nào dễ châm điếu nhất chưa? Không sao nếu chưa rõ — Sol đang học cùng {pronoun}. Trước khi ngủ, để mọi cố gắng xuống. Mai sáng dậy, ngày mới.`,
    pushTime: '21:30',
    wikiSlug: 'phase-1-night-2',
  },
  {
    dayNumber: 103,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 3 — pattern bắt đầu lộ.`,
    body: `Sol đã thấy: {pronoun} có lúc châm vì stress, có lúc vì rảnh, có lúc vì sau cơm. Mỗi lúc một lý do khác. Đó là chân dung sống của {pronoun} — không có gì sai. Đêm nay nghỉ — Sol đang ghi.`,
    pushTime: '21:30',
    wikiSlug: 'phase-1-night-3',
  },
  {
    dayNumber: 104,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 4 — thèm hôm nay đã qua chưa?`,
    body: `Mỗi cơn thèm hôm nay đã đến rồi đi. {pronoun} đã sống qua tất cả — dù hút hay không. Đó là chiến thắng nhỏ Sol đếm. Đêm nay ngủ kỹ — não đang sửa.`,
    pushTime: '21:30',
    wikiSlug: 'phase-1-night-4',
  },
  {
    dayNumber: 105,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 5 — gần nửa tuần Nhận Thức.`,
    body: `5 ngày qua {pronoun} đã ghi nhận. Đó là dữ liệu thật — không có ai khác trên đời này biết {pronoun} hơn lúc này. Chính {pronoun} đang biết mình. Đêm yên.`,
    pushTime: '21:30',
    wikiSlug: 'phase-1-night-5',
  },
  {
    dayNumber: 106,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 6 — gần xong tuần Nhận Thức.`,
    body: `Mai là ngày 7. Mai Sol sẽ tổng kết tuần với {pronoun}. Đêm nay không cần kết luận gì — chỉ ngủ. Ngày 7 sáng mai sẽ rõ.`,
    pushTime: '21:30',
    wikiSlug: 'phase-1-night-6',
  },
  {
    dayNumber: 107,
    module: 'NIGHT_STORY',
    voice: 'KHANG_SOL',
    title: `Đêm 7 — chuyển trang.`,
    body: `Mình là Khang. Tuần Nhận Thức của {pronoun} đã xong. Mai sang Hành Động — đồ thị giảm bắt đầu. Đêm nay ngủ — không phải để chuẩn bị "chiến đấu". Để chuẩn bị "đi tiếp". Khác nhau. — Khang Sol`,
    pushTime: '21:30',
    wikiSlug: 'phase-1-night-7',
  },

  // ─── PHASE 2 HÀNH ĐỘNG NIGHT_STORY (Day 8-28) ──────────────────────
  {
    dayNumber: 108,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 8 — delay đầu tiên.`,
    body: `Hôm nay {pronoun} thử delay 10 phút lần nào không? Nếu có — Sol mừng. Nếu không — mai khác. Tuần này không vội. Đêm nay {pronoun} chỉ cần ngủ ngon, ngày mai não thử lại.`,
    pushTime: '21:30',
    wikiSlug: 'phase-2-night-8',
  },
  {
    dayNumber: 109,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 9 — vòng lặp đang lung lay.`,
    body: `Mỗi lần {pronoun} delay được, vòng lặp cũ bị lung lay 1 chút. Đêm nay não đang sắp xếp lại — đó là lúc giấc ngủ sâu quan trọng. Tắt điện thoại sớm hơn 30 phút.`,
    pushTime: '21:30',
    wikiSlug: 'phase-2-night-9',
  },
  {
    dayNumber: 110,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 10 — Plan B đã có.`,
    body: `Hôm nay Sol gợi Plan B cho top trigger của {pronoun}. Đã thử chưa? Nếu thử — note 1 câu vào sổ tay: "Hôm nay tôi thay [hút] bằng [đi bộ / nước]". Câu đó ngày mai đọc lại sẽ thấy mình.`,
    pushTime: '21:30',
    wikiSlug: 'phase-2-night-10',
  },
  {
    dayNumber: 111,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 11 — giảm nhẹ.`,
    body: `Hôm nay so với baseline tuần Nhận Thức — {pronoun} đã giảm bao nhiêu? Mở /analytics xem nếu chưa rõ. Mỗi điếu giảm = 1 lần não chọn khác. Đêm yên với chính mình.`,
    pushTime: '21:30',
    wikiSlug: 'phase-2-night-11',
  },
  {
    dayNumber: 112,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 12 — stress đã qua.`,
    body: `Stress hôm nay đã xuống chưa? Nếu hôm nay {pronoun} có lúc stress mà không hút — đó là chiến thắng to. Não đang học: stress không bắt buộc đi cùng nicotin. Ghi vào sổ.`,
    pushTime: '21:30',
    wikiSlug: 'phase-2-night-12',
  },
  {
    dayNumber: 113,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 13 — bữa cơm khác.`,
    body: `{pronoun} có thử đánh răng sau bữa cơm hôm nay không? Vị bạc hà thay điếu — nhỏ nhưng thay đổi mạnh. Mai cũng vậy. Đêm này nghỉ.`,
    pushTime: '21:30',
    wikiSlug: 'phase-2-night-13',
  },
  {
    dayNumber: 114,
    module: 'NIGHT_STORY',
    voice: 'KHANG_SOL',
    title: `Đêm 14 — 1 tuần Hành Động.`,
    body: `Mình là Khang. {pronoun} đã đi 14 ngày từ Day 1 — 1 tuần Nhận Thức + 1 tuần Hành Động. Receptor nicotin trong não đã giảm đáng kể. Cơ thể đang cảm ơn {pronoun} thầm. Đêm nay xứng đáng ngủ sâu. — Khang Sol`,
    pushTime: '21:30',
    wikiSlug: 'phase-2-night-14',
  },
  {
    dayNumber: 115,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 15 — câu hỏi identity.`,
    body: `Sáng nay Sol hỏi: {pronoun} là ai khi không hút? Tối nay {pronoun} có câu trả lời không? Không cần đầy đủ — chỉ 1 câu. Viết ra giấy, để cạnh giường. Mai đọc lại.`,
    pushTime: '21:30',
    wikiSlug: 'phase-2-night-15',
  },
  {
    dayNumber: 116,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 16 — vào tuần khó.`,
    body: `Tuần này có thể có lúc não nói "thử 1 điếu xem sao". Đêm nay nếu cảm giác đó lên — không cần đánh nó. Chỉ cần nhận ra: "Đây là não đang phản đối, không phải tôi". Rồi ngủ.`,
    pushTime: '21:30',
    wikiSlug: 'phase-2-night-16',
  },
  {
    dayNumber: 117,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 17 — không cô đơn.`,
    body: `Hôm nay Sol mời {pronoun} mở Đội Sol. Có nhìn không? 5-10 đồng đội cùng phase với {pronoun} đang ngủ trong các thành phố khác. Có người đang Day 17 như {pronoun}, có người đang Day 35. Cùng đường.`,
    pushTime: '21:30',
    wikiSlug: 'phase-2-night-17',
  },
  {
    dayNumber: 118,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 18 — 21h thèm.`,
    body: `Đây chính là giờ Sol cảnh báo sáng — craving 21h. Nếu lúc này {pronoun} thấy thèm: tắt điện thoại, ngâm chân nước ấm, lên giường. 30 phút nữa cơn sẽ qua. Sol biết — Sol đo nhịp này nhiều người.`,
    pushTime: '21:30',
    wikiSlug: 'phase-2-night-18',
  },
  {
    dayNumber: 119,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 19 — tiền dồn lại.`,
    body: `Tiền {pronoun} không hút hôm nay đang dồn vào tiết kiệm. Tối nay tưởng tượng: dùng nó cho ai? Một bữa tối cuối tuần với vợ? Một thứ cho con? Hình ảnh cụ thể giúp não giữ vững.`,
    pushTime: '21:30',
    wikiSlug: 'phase-2-night-19',
  },
  {
    dayNumber: 120,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 20 — nếu lỡ nhậu.`,
    body: `Tối nay {pronoun} có nhậu không? Nếu lỡ hút 1-2 điếu — không sao. Quy tắc: ghi vào logger ngay. Đừng để 1 điếu thành "đêm vỡ". Đêm nay vẫn ngủ. Mai thức dậy là ngày mới.`,
    pushTime: '21:30',
    wikiSlug: 'phase-2-night-20',
  },
  {
    dayNumber: 121,
    module: 'NIGHT_STORY',
    voice: 'KHANG_SOL',
    title: `Đêm 21 — 3 lý do.`,
    body: `Mình là Khang. Hôm nay {pronoun} viết 3 lý do chưa? Nếu có — để cạnh giường. Mỗi đêm đọc lại. Tuần sau lúc Q-Day, mình muốn {pronoun} đã đọc 7 lần. 3 lý do trở thành 21 lần ghi nhớ. Mạnh hơn ý chí. — Khang Sol`,
    pushTime: '21:30',
    wikiSlug: 'phase-2-night-21',
  },
  {
    dayNumber: 122,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 22 — đã hỏi vợ chưa?`,
    body: `Hôm nay sáng Sol gợi {pronoun} hỏi vợ/người thân: "Tôi nên cam kết gì?" Đã hỏi chưa? Nếu chưa — không sao, mai. Nếu rồi — câu trả lời của họ ghi vào sổ. Tuần sau Q-Day {pronoun} sẽ cần câu đó.`,
    pushTime: '21:30',
    wikiSlug: 'phase-2-night-22',
  },
  {
    dayNumber: 123,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 23 — người thân thấy gì.`,
    body: `Hôm nay có ai trong nhà nhận xét {pronoun} khác chưa? Da tươi hơn? Hơi thở đỡ? Hỏi 1 người. Câu trả lời của họ là gương trung thực. Đêm này nghỉ với confirmation đó.`,
    pushTime: '21:30',
    wikiSlug: 'phase-2-night-23',
  },
  {
    dayNumber: 124,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 24 — 5 ngày nữa.`,
    body: `Còn 4 ngày là Q-Day. Đêm nay tưởng tượng: sáng 7h Day 28, {pronoun} dậy, mở dashboard, bấm "Tôi cam kết". Hình ảnh đó in vào não trong giấc ngủ — visualization. Nhẹ nhàng ngủ.`,
    pushTime: '21:30',
    wikiSlug: 'phase-2-night-24',
  },
  {
    dayNumber: 125,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 25 — chuẩn bị nhà.`,
    body: `Mai cuối tuần. {pronoun} có dọn bao thuốc còn lại + gạt tàn không? Không cần dọn ngay tối nay — sáng mai. Đêm nay ngủ. Não cần nghỉ trước decision lớn.`,
    pushTime: '21:30',
    wikiSlug: 'phase-2-night-25',
  },
  {
    dayNumber: 126,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 26 — T-2.`,
    body: `Còn 2 ngày là Q-Day. Sáng nay Sol đã gửi push T-2. Đêm nay {pronoun} đọc lại 3 lý do (nếu chưa làm) — slowly, không vội. Rồi ngủ. Mai T-1.`,
    pushTime: '21:30',
    wikiSlug: 'phase-2-night-26',
  },
  {
    dayNumber: 127,
    module: 'NIGHT_STORY',
    voice: 'KHANG_SOL',
    title: `Đêm 27 — đêm trước Q-Day.`,
    body: `Mình là Khang. Đêm nay là đêm cuối Phase Hành Động. Mình muốn nói 1 câu cho {pronoun}: "Mình đã ở chỗ {pronoun} đang đứng năm 2018." Mình ngủ đêm đó như đứa trẻ — vì biết sáng mai mình quyết định cứu chính mình. Mai cũng vậy. — Khang Sol`,
    pushTime: '21:30',
    wikiSlug: 'phase-2-night-27',
  },
  {
    dayNumber: 128,
    module: 'NIGHT_STORY',
    voice: 'KHANG_SOL',
    title: `Đêm 28 — Q-Day kết thúc.`,
    body: `Mình là Khang. Hôm nay {pronoun} đã bấm "Tôi cam kết". Đêm đầu tiên với đồng hồ tự do đang chạy. Đây là đêm thiêng — cơ thể đang sạch nicotin. Nếu khó ngủ — bình thường, đêm thứ 2-3 dễ hơn. Sol bên {pronoun}. Ngủ ngon, người không hút. — Khang Sol`,
    pushTime: '21:30',
    wikiSlug: 'phase-2-night-28-q-day',
  },

  // ─── PHASE 4 TÁI THIẾT NIGHT_STORY (Day 59-88) — sparse ────────────
  {
    dayNumber: 159,
    module: 'NIGHT_STORY',
    voice: 'KHANG_SOL',
    title: `Đêm 59 — 30 ngày tự do.`,
    body: `Mình là Khang. Đêm nay {pronoun} ngủ không có nicotin trong máu — đêm thứ 30 liên tiếp. Não đã quen. Tim đập chậm hơn 8-10 nhịp/phút lúc nghỉ. Ngủ sâu hơn. {pronoun} có cảm thấy không? Đêm yên với chính cơ thể. — Khang Sol`,
    pushTime: '21:30',
    wikiSlug: 'phase-4-night-59',
  },
  {
    dayNumber: 162,
    module: 'NIGHT_STORY',
    voice: 'KHANG_SOL',
    title: `Đêm 62 — ai là {pronoun} bây giờ.`,
    body: `Mình là Khang. Câu sáng nay: "{pronoun} là gì bây giờ?". Đêm nay không cần trả lời gấp. Cứ để câu hỏi nằm bên cạnh, ngủ với nó. Mai dậy có thể câu trả lời sẽ rõ — hoặc không, vẫn không sao. Identity là quá trình, không phải kết quả. — Khang Sol`,
    pushTime: '21:30',
    wikiSlug: 'phase-4-night-62',
  },
  {
    dayNumber: 165,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 65 — phản ứng với người hút.`,
    body: `Hôm nay {pronoun} có gặp người đang hút không? Phản ứng đầu tiên — nếu là "bình thản, không quan tâm" — đó là dấu hiệu identity đã chuyển. Sol thấy {pronoun} ngày càng xa pattern cũ. Đêm nay nghỉ với chính mình mới.`,
    pushTime: '21:30',
    wikiSlug: 'phase-4-night-65',
  },
  {
    dayNumber: 168,
    module: 'NIGHT_STORY',
    voice: 'KHANG_SOL',
    title: `Đêm 68 — biết trước Day 75.`,
    body: `Mình là Khang. Sáng nay mình cảnh báo Day 75 trap. Đêm nay tự nhắc: "1 điếu thử = 72 giờ thèm trở lại". Não muốn dùng cảm giác "an toàn" để gài. Biết trước = đã thắng nửa. {pronoun} không yếu — {pronoun} đã đi 68 ngày. Đêm yên. — Khang Sol`,
    pushTime: '21:30',
    wikiSlug: 'phase-4-night-68',
  },
  {
    dayNumber: 171,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 71 — cách giữ vững.`,
    body: `Sáng nay Sol gợi: chia sẻ với 1 người mới đang muốn cai. Đêm nay tưởng tượng câu {pronoun} sẽ nói. Không cần lý thuyết — kể {pronoun} đã đi sao. Đêm này tích trữ ý — mai có cơ hội thử.`,
    pushTime: '21:30',
    wikiSlug: 'phase-4-night-71',
  },
  {
    dayNumber: 174,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 74 — body đã hồi.`,
    body: `Cơ thể {pronoun} đêm nay khác cơ thể đêm Day 1: phổi sạch hơn, tim đập đều, ngủ sâu hơn. Đặt tay lên ngực, cảm nhận nhịp. Đó là nhịp của người không hút. Đêm yên với cơ thể đó.`,
    pushTime: '21:30',
    wikiSlug: 'phase-4-night-74',
  },
  {
    dayNumber: 177,
    module: 'NIGHT_STORY',
    voice: 'KHANG_SOL',
    title: `Đêm 77 — 1 năm sau.`,
    body: `Mình là Khang. Sáng nay câu hỏi: 1 năm sau {pronoun} là ai? Đêm nay ngủ với 1 hình ảnh cụ thể — không generic. Vd "1 năm nữa tôi đi Đà Lạt với vợ, không cần ngừng hút giữa đường". Hình ảnh đó nuôi não trong giấc ngủ. — Khang Sol`,
    pushTime: '21:30',
    wikiSlug: 'phase-4-night-77',
  },
  {
    dayNumber: 180,
    module: 'NIGHT_STORY',
    voice: 'KHANG_SOL',
    title: `Đêm 80 — vì người khác.`,
    body: `Mình là Khang. Mình bỏ vì cu Tí — mình đã nói. Đêm nay {pronoun} đọc lại lý do của mình. Nếu lý do gốc còn — đó là rễ. Nếu cần đổi — đổi không sao, sự thật quan trọng hơn câu chữ. {pronoun} đang sống cho ai? — Khang Sol`,
    pushTime: '21:30',
    wikiSlug: 'phase-4-night-80',
  },
  {
    dayNumber: 183,
    module: 'NIGHT_STORY',
    voice: 'SOL_DONG_HANH',
    title: `Đêm 83 — Sol nhỏ dần.`,
    body: `Sol giảm tần suất nhắc — đêm nay là 1 trong những đêm cuối Sol nói. Không phải bỏ {pronoun} — là {pronoun} không cần Sol nữa. Khi nào cần, mở widget, gõ 1 câu. Sol vẫn đợi. Đêm yên.`,
    pushTime: '21:30',
    wikiSlug: 'phase-4-night-83',
  },
  {
    dayNumber: 186,
    module: 'NIGHT_STORY',
    voice: 'KHANG_SOL',
    title: `Đêm 86 — gần tốt nghiệp.`,
    body: `Mình là Khang. Còn 2 đêm nữa là Day 88. {pronoun} đang gần xong cuộc hành trình mình thiết kế. Đêm này nghĩ: ai trong gia đình {pronoun} sẽ ăn mừng cùng? Mai mời 1 người. Đại Sứ là chia sẻ — bắt đầu từ trong nhà. — Khang Sol`,
    pushTime: '21:30',
    wikiSlug: 'phase-4-night-86',
  },
];

export const PHASE_B_CONTENT_BY_DAY = PHASE_B_CONTENT.reduce<Record<number, SeedContentItemPhaseB[]>>(
  (acc, item) => {
    if (!acc[item.dayNumber]) acc[item.dayNumber] = [];
    acc[item.dayNumber].push(item);
    return acc;
  },
  {},
);
