// backend/src/seed/contentItems.ts
// 127 ContentItem theo MESSAGING_PLAYBOOK 30-day emotional arc.
// REWRITE 2026-05-04 — voice nhất quán Khang Sol vs Sol Đồng hành.
//
// Variables: {pronouns} {pronoun} {name} {greet} {assistantName} {selfRef}
//            {topReason} {topTrigger} — backend tự thay
//
// Arc 7 giai đoạn:
//   Khởi động (Day 1-2)   — Khang Sol giọng cá nhân ở MORNING
//   Đỉnh sóng (Day 3-5)   — Sol Đồng hành đồng cảm + Plan B cụ thể
//   Bức tường (Day 6-10)  — cite science nhiều, replay {topReason}
//   Bước ngoặt (Day 11-14) — celebrate, build confidence
//   Tự tin giả (Day 15-21) — cảnh báo phenomena, không overconfident
//   Nội hóa (Day 22-28)   — reflection nhẹ, identity shift
//   Cột mốc (Day 29-30)   — Khang Sol return, set up next chapter

export interface SeedContentItem {
  dayNumber: number;
  module: 'MORNING_GOAL' | 'SCIENCE_TIP' | 'PHENOMENA_ALERT' | 'EXERCISE' | 'NIGHT_STORY';
  title: string;
  body: string;
  ctaAction?: string;
  pushTime?: string;
  wikiSlug?: string;
  exerciseKey?: string;
}

export const CONTENT_ITEMS: SeedContentItem[] = [
  // ════════════ MORNING_GOAL × 30 — 07:00 — Mở ngày, set 1 goal cụ thể ════════════
  // Day 1-2: KHỞI ĐỘNG (Khang Sol giọng cá nhân — ký tên "Khang Sol")
  {
    dayNumber: 1,
    module: 'MORNING_GOAL',
    title: `Day 1, {pronoun}: Hôm nay không hút.`,
    body: `Lý do {pronoun} bắt đầu: {topReason}. Lúc khó nhất, nhớ câu này. 24 giờ đầu là 24 giờ khó nhất sinh học. Mình đi với {pronoun}. — Khang Sol`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-1',
  },
  {
    dayNumber: 2,
    module: 'MORNING_GOAL',
    title: `Day 2, {pronoun}: Đỉnh thèm hôm nay.`,
    body: `Hôm nay nicotin đã rời máu, nhưng não chưa thích nghi. Cơn thèm là dấu hiệu não đang HỌC. Mỗi sóng vượt = não bớt phụ thuộc. Mình đã đi qua chính ngày này. — Khang Sol`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-2-dinh-con-them',
  },
  // Day 3-5: ĐỈNH SÓNG (Sol Đồng hành đồng cảm + Plan B cụ thể)
  {
    dayNumber: 3,
    module: 'MORNING_GOAL',
    title: `Day 3 — bức tường.`,
    body: `Triệu chứng đỉnh điểm: cáu, mất ngủ, đói. Đây là "bức tường" Hughes 2007. Vượt được Day 3, tỷ lệ thành công 30 ngày tăng 3x. Hôm nay {pronoun} có Plan B chưa?`,
    ctaAction: 'open_exercise:day_3',
    pushTime: '07:00',
    wikiSlug: 'ngay-3-buc-tuong',
  },
  {
    dayNumber: 4,
    module: 'MORNING_GOAL',
    title: `Day 4: Đêm qua khó ngủ?`,
    body: `Bình thường — não đang điều chỉnh dopamine. Hôm nay tránh cà phê sau 14h, đi bộ 20 phút trước 18h. Cơ thể sẽ thưởng giấc ngủ sâu đêm nay.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-4-mat-ngu',
  },
  {
    dayNumber: 5,
    module: 'MORNING_GOAL',
    title: `Day 5: Cáu hơn? Bình thường.`,
    body: `Não nicotin-đói cảm xúc thô hơn 30-40% (Cosgrove). Báo trước người thân. Khi cáu lên — uống nước lạnh, đếm 10 hơi thở chậm. Sóng sẽ rút.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-5-cau-bat-thuong',
  },
  // Day 6-10: BỨC TƯỜNG (cite science, replay {topReason})
  {
    dayNumber: 6,
    module: 'MORNING_GOAL',
    title: `Day 6: Cuối tuần đầu.`,
    body: `Cơn thèm tuần đầu chủ yếu là sinh học. Sang tuần 2 là tâm lý. Hôm nay nghỉ — không lên kế hoạch lớn, chỉ qua từng giờ.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-6',
  },
  {
    dayNumber: 7,
    module: 'MORNING_GOAL',
    title: `Day 7: 168 giờ.`,
    body: `Tuần đầu xong rồi {pronoun}. Hôm nay thưởng cho mình một việc nhỏ — đi bộ 15 phút, uống cà phê chậm, gì cũng được. {pronoun} xứng đáng.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-7-mot-tuan',
  },
  {
    dayNumber: 8,
    module: 'MORNING_GOAL',
    title: `Day 8: Tuần 2 — đầu khác.`,
    body: `Sinh học đã ổn 80%. Trận chính từ giờ là tâm lý: thói quen ngày, tình huống quen, người quen rủ. Nhận diện 1 tình huống khó hôm nay, prep trước.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-8',
  },
  {
    dayNumber: 9,
    module: 'MORNING_GOAL',
    title: `Day 9: Vẫn còn cơn thèm?`,
    body: `Bình thường — receptor đang giảm. Cơn thèm Day 9 yếu hơn Day 3 ~50%. Mỗi lần qua = não yếu thêm. Đếm số cơn hôm nay, tối kiểm.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-9',
  },
  {
    dayNumber: 10,
    module: 'MORNING_GOAL',
    title: `Day 10: 1/3 chặng.`,
    body: `Phổi đã sạch lông mao, ho ra đờm nâu là dấu hiệu tốt — phổi tự dọn. Khứu giác hôm nay sắc hơn — thử ngửi cà phê sáng.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-10',
  },
  // Day 11-14: BƯỚC NGOẶT (celebrate, build confidence, {topReason} Day 14)
  {
    dayNumber: 11,
    module: 'MORNING_GOAL',
    title: `Day 11: Tim đập chậm hơn.`,
    body: `Nhịp tim nghỉ giảm ~5-10 bpm so với khi hút (Mayo Clinic). Tim làm việc đỡ hơn. Hôm nay leo cầu thang chậm rãi — cảm nhận sự khác.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-11',
  },
  {
    dayNumber: 12,
    module: 'MORNING_GOAL',
    title: `Day 12: Tuần hoàn cải thiện.`,
    body: `Ngón tay, ngón chân ấm hơn. Da bớt xỉn. {pronoun} đã trả lại oxy cho tế bào. Hôm nay ngắm tay mình lúc rảnh.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-12',
  },
  {
    dayNumber: 13,
    module: 'MORNING_GOAL',
    title: `Day 13: Mai là Day 14.`,
    body: `Day 14 là cột mốc receptor giảm 40%. Não bắt đầu coi không-hút là default. Hôm nay sống bình thường — đừng overprepare. Bình thản là thành tựu lớn nhất.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-13',
  },
  {
    dayNumber: 14,
    module: 'MORNING_GOAL',
    title: `Day 14: 2 TUẦN — receptor giảm 40%.`,
    body: `{greet}. Hôm nay receptor nicotine não giảm 40%. {topReason} — 14 ngày rồi {pronoun} vẫn giữ. Cơn thèm tâm lý là mặt trận chính từ giờ. Mình gửi {pronoun} voice Day 14.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-14-receptor',
  },
  // Day 15-21: TỰ TIN GIẢ (cảnh báo phenomena, không overconfident)
  {
    dayNumber: 15,
    module: 'MORNING_GOAL',
    title: `Day 15: Nửa chặng.`,
    body: `15 ngày sạch — đa số người không tin được làm được. Nhưng đây cũng là điểm risky: tự tin có thể dẫn tới "thử 1 điếu xem". Đừng. Não chưa hoàn toàn reset.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-15',
  },
  {
    dayNumber: 16,
    module: 'MORNING_GOAL',
    title: `Day 16: Tăng cân?`,
    body: `Bình thường — vi sinh đường ruột phục hồi, hấp thụ tốt hơn. Trung bình tăng 2-4kg trong 30 ngày (NHS). Đừng diet ngay — cơ thể đang sửa chữa.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-16-tang-can',
  },
  {
    dayNumber: 17,
    module: 'MORNING_GOAL',
    title: `Day 17: Nhậu cuối tuần?`,
    body: `Rượu hạ guard, dopamine drop sâu — cơn thèm trở lại mạnh. Nếu phải đi: gọi nước trước, ngồi xa người hút, có cớ về sớm.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-17-nhau',
  },
  {
    dayNumber: 18,
    module: 'MORNING_GOAL',
    title: `Day 18: Mơ hút thuốc?`,
    body: `Bình thường — não REM đang xử lý ký ức. Mơ KHÔNG phải dấu hiệu thèm thật. Nhiều người mơ rõ tới Day 30+. Tỉnh dậy là bình thường lại.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-18-mo-hut',
  },
  {
    dayNumber: 19,
    module: 'MORNING_GOAL',
    title: `Day 19: Ho dai dẳng?`,
    body: `Lông mao phổi đang mọc lại — đẩy đờm tích tụ ra. Ho nhiều 1-3 tuần là tốt. Nếu ho ra máu hoặc khó thở dữ dội — đi khám.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-19-ho',
  },
  {
    dayNumber: 20,
    module: 'MORNING_GOAL',
    title: `Day 20: Lo lắng vô cớ?`,
    body: `Não đang reset baseline cảm xúc. 3-5 ngày sẽ qua. Đi bộ ngoài trời 20 phút giúp. Không cần điều trị — đây là quá trình.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-20-lo-au',
  },
  {
    dayNumber: 21,
    module: 'MORNING_GOAL',
    title: `Day 21: 3 TUẦN — thói quen mới.`,
    body: `21 ngày là khung Lally 2010 cho thói quen mới hình thành. Não đã viết xong "không hút" thành default. Từ giờ là duy trì, không phải nỗ lực.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-21',
  },
  // Day 22-28: NỘI HÓA (reflection nhẹ, identity shift)
  {
    dayNumber: 22,
    module: 'MORNING_GOAL',
    title: `Day 22: {pronoun} không hút thuốc.`,
    body: `Câu này. {pronoun} không nói "đang cai" hay "đang cố" — {pronoun} không hút thuốc. Identity shift. Nói ra miệng 1 lần hôm nay.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-22-identity',
  },
  {
    dayNumber: 23,
    module: 'MORNING_GOAL',
    title: `Day 23: Ai đó rủ?`,
    body: `Nói ngắn: "Mình đã bỏ rồi." Không cần giải thích, không cần xin lỗi. Người tốt sẽ tôn trọng. Người không tốt — {pronoun} không cần.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-23',
  },
  {
    dayNumber: 24,
    module: 'MORNING_GOAL',
    title: `Day 24: Tiền đã tiết kiệm.`,
    body: `Trung bình ~24 ngày × 25.000đ/gói = 600.000đ. Hôm nay làm gì với số đó? Một bữa ngon, sách hay, gọi xe đỡ vợ. Chuyển dopamine sang chỗ tốt.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-24-tien',
  },
  {
    dayNumber: 25,
    module: 'MORNING_GOAL',
    title: `Day 25: Hơi thở dài hơn.`,
    body: `Phổi đã hồi phục ~10% chức năng. Leo cầu thang đỡ thở dốc. Hôm nay thử hít sâu 5 giây — giữ 2 — thở 7. Phổi mới hơn 25 ngày trước.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-25-hoi-tho',
  },
  {
    dayNumber: 26,
    module: 'MORNING_GOAL',
    title: `Day 26: Vị giác sắc hơn.`,
    body: `Nụ vị giác phục hồi ~80%. Bữa cơm thường ngày tự nhiên ngon hơn. Hôm nay ăn chậm 1 bữa — nếm thật sự.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-26-vi-giac',
  },
  {
    dayNumber: 27,
    module: 'MORNING_GOAL',
    title: `Day 27: Sắp 30 ngày.`,
    body: `3 ngày nữa tới cột mốc. Đừng overprepare. Hôm nay sống bình thường — vì bình thường BÂY GIỜ là không hút. Đó là chiến thắng.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-27',
  },
  {
    dayNumber: 28,
    module: 'MORNING_GOAL',
    title: `Day 28: Sắp xong.`,
    body: `Điều khó nhất không phải bỏ — mà giữ. {pronoun} đã giữ 28 ngày. Tự hào nhỏ thôi, không phô trương. Phòng vệ vẫn cần — đời còn dài.`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-28',
  },
  // Day 29-30: CỘT MỐC (Khang Sol return, set up next chapter)
  {
    dayNumber: 29,
    module: 'MORNING_GOAL',
    title: `Day 29: Mai là 30.`,
    body: `Mình muốn nói thật với {pronoun}: 30 ngày KHÔNG phải đích. Là cột mốc. Sau Day 30 là tiếp tục — nhưng dễ hơn nhiều. Mình đã đi đường đó. — Khang Sol`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-29',
  },
  {
    dayNumber: 30,
    module: 'MORNING_GOAL',
    title: `Day 30: 30 NGÀY — TÁI SINH.`,
    body: `{greet}. Day 30. Phổi sửa được ~30%, tim đập chậm, tuần hoàn về bình thường, vị giác về 80%. Doll & Hill BMJ 2004: cai 30+ tuổi giảm 90% nguy cơ ung thư phổi. {pronoun} đã viết lại cuộc đời. — Khang Sol`,
    ctaAction: 'open_checkin',
    pushTime: '07:00',
    wikiSlug: 'ngay-30',
  },

  // ════════════ SCIENCE_TIP × 30 — 10:00 — Giải thích cơ thể, cite source ════════════
  {
    dayNumber: 1,
    module: 'SCIENCE_TIP',
    title: `8 giờ — CO máu giảm 50%.`,
    body: `Sau 8 giờ không hút, carbon monoxide trong máu giảm một nửa (CDC). Hồng cầu chở oxy hiệu quả hơn rồi {pronoun}.`,
    pushTime: '10:00',
    wikiSlug: 'co-giam',
  },
  {
    dayNumber: 2,
    module: 'SCIENCE_TIP',
    title: `48 giờ — nicotin sạch máu.`,
    body: `Nicotin có half-life 2 giờ — sau 48 giờ ~99% đã thải qua nước tiểu (NHS). Cái còn lại hôm nay là TÂM LÝ, không phải sinh học.`,
    pushTime: '10:00',
    wikiSlug: 'nicotin-half-life',
  },
  {
    dayNumber: 3,
    module: 'SCIENCE_TIP',
    title: `72 giờ — phổi bắt đầu mở.`,
    body: `Ống phế quản giãn ra sau 72 giờ. Hô hấp dễ hơn. Đây cũng là lúc cơn thèm sinh học đỉnh điểm — vì receptor não chưa kịp giảm (Hughes 2007).`,
    pushTime: '10:00',
    wikiSlug: 'phoi-72h',
  },
  {
    dayNumber: 4,
    module: 'SCIENCE_TIP',
    title: `Mất ngủ — tại sao?`,
    body: `Nicotin là chất kích thích. Bỏ rồi, não phải tự sản xuất dopamine — quá trình mất 1-2 tuần. Đêm là lúc não điều chỉnh nhiều nhất → mất ngủ.`,
    pushTime: '10:00',
    wikiSlug: 'mat-ngu-co-che',
  },
  {
    dayNumber: 5,
    module: 'SCIENCE_TIP',
    title: `Cáu kỉnh — có thật.`,
    body: `Não nicotin-đói cảm xúc thô hơn 30-40% (Cosgrove 2009). Đây không phải tính cách {pronoun} — là sinh học tạm thời. 1-2 tuần sẽ về.`,
    pushTime: '10:00',
    wikiSlug: 'cau-kinh',
  },
  {
    dayNumber: 6,
    module: 'SCIENCE_TIP',
    title: `Khứu giác phục hồi.`,
    body: `Mũi đã sạch hắc ín. Nụ khứu giác bắt đầu mọc lại. Hôm nay {pronoun} có thể ngửi rõ hơn — thử ngửi tách cà phê chậm.`,
    pushTime: '10:00',
    wikiSlug: 'khuu-giac',
  },
  {
    dayNumber: 7,
    module: 'SCIENCE_TIP',
    title: `1 tuần — tỷ lệ thành công.`,
    body: `Người vượt được tuần đầu, tỷ lệ giữ 30 ngày là 60% (Hughes 2007). {pronoun} đã ở top này rồi.`,
    pushTime: '10:00',
    wikiSlug: 'ty-le-tuan-1',
  },
  {
    dayNumber: 8,
    module: 'SCIENCE_TIP',
    title: `Receptor — sao não đói?`,
    body: `Nicotin chiếm receptor acetylcholine não. Bỏ → receptor "đòi". Mỗi lần không cấp, não giảm receptor dần. 14 ngày giảm 40% (Brody 2006).`,
    pushTime: '10:00',
    wikiSlug: 'receptor',
  },
  {
    dayNumber: 9,
    module: 'SCIENCE_TIP',
    title: `Ho ra đờm nâu — tốt.`,
    body: `Lông mao phổi đang mọc lại, đẩy đờm tích tụ 25 năm ra. Có thể kéo dài 1-3 tuần. Đây là dọn nhà, không phải bệnh.`,
    pushTime: '10:00',
    wikiSlug: 'ho-dom',
  },
  {
    dayNumber: 10,
    module: 'SCIENCE_TIP',
    title: `Tuần hoàn cải thiện.`,
    body: `Sau 2-12 tuần, lưu lượng máu tăng đáng kể (Mayo Clinic). Ngón tay ấm hơn, sẹo lành nhanh hơn, da đỡ xỉn. Đó là máu trở lại.`,
    pushTime: '10:00',
    wikiSlug: 'tuan-hoan',
  },
  {
    dayNumber: 11,
    module: 'SCIENCE_TIP',
    title: `Tim đập chậm hơn.`,
    body: `Nhịp tim nghỉ giảm 5-10 bpm so với khi hút (Mayo Clinic). Tim đỡ làm việc, kéo dài tuổi thọ ~3-5 năm với người cai 50+.`,
    pushTime: '10:00',
    wikiSlug: 'tim-dap',
  },
  {
    dayNumber: 12,
    module: 'SCIENCE_TIP',
    title: `Vi sinh ruột — và tăng cân.`,
    body: `Nicotin ức chế vi sinh đường ruột. Bỏ → ruột phục hồi, hấp thụ tốt → tăng cân tự nhiên 2-4kg (NHS). Đừng diet — ăn uống lành mạnh là đủ.`,
    pushTime: '10:00',
    wikiSlug: 'vi-sinh-ruot',
  },
  {
    dayNumber: 13,
    module: 'SCIENCE_TIP',
    title: `Dopamine baseline.`,
    body: `Não đang sửa lại "thước đo vui". Trong 2-3 tuần, cảm giác vui có thể nhạt — gọi là anhedonia. Bình thường, có sẽ qua.`,
    pushTime: '10:00',
    wikiSlug: 'dopamine-baseline',
  },
  {
    dayNumber: 14,
    module: 'SCIENCE_TIP',
    title: `2 tuần — receptor giảm 40%.`,
    body: `Brody 2006 PET scan: sau 14 ngày, receptor nicotinic não giảm ~40%. Não không còn coi nicotin là default. Đỉnh sinh học đã xa.`,
    pushTime: '10:00',
    wikiSlug: 'brody-pet',
  },
  {
    dayNumber: 15,
    module: 'SCIENCE_TIP',
    title: `Nửa chặng — thống kê.`,
    body: `Người vượt 14 ngày giữ được 30 ngày: ~75% (Hughes 2007). {pronoun} đang ở đoạn dễ hơn. Nguy cơ giờ là tự tin quá mức.`,
    pushTime: '10:00',
    wikiSlug: 'thong-ke-15',
  },
  {
    dayNumber: 16,
    module: 'SCIENCE_TIP',
    title: `Sao bỏ thuốc lại tăng cân?`,
    body: `3 lý do: vi sinh ruột phục hồi, nụ vị giác trở lại (ăn ngon hơn), thay thuốc bằng đồ ngọt. Đây không phải mỡ xấu — là sửa chữa.`,
    pushTime: '10:00',
    wikiSlug: 'tang-can-co-che',
  },
  {
    dayNumber: 17,
    module: 'SCIENCE_TIP',
    title: `Rượu + cai thuốc.`,
    body: `Rượu giảm GABA → hạ guard. Đồng thời drop dopamine sâu hơn → cơn thèm thuốc trở lại mạnh. 1 ly cũng nguy hiểm trong 30 ngày đầu.`,
    pushTime: '10:00',
    wikiSlug: 'ruou-cai-thuoc',
  },
  {
    dayNumber: 18,
    module: 'SCIENCE_TIP',
    title: `Mơ hút thuốc — tại sao?`,
    body: `REM xử lý ký ức 25 năm hút. Não dọn dẹp, không phải đòi. Mơ rõ tới Day 30-60. Tỉnh dậy bình thường — không phải dấu hiệu thất bại.`,
    pushTime: '10:00',
    wikiSlug: 'mo-hut-rem',
  },
  {
    dayNumber: 19,
    module: 'SCIENCE_TIP',
    title: `Ho dai 3 tuần — bình thường.`,
    body: `Lông mao phổi mọc lại, đẩy hắc ín ra. Quá trình kéo 2-12 tuần (NHS). Ho có đờm = tốt. Ho ra máu hoặc khó thở = đi khám ngay.`,
    pushTime: '10:00',
    wikiSlug: 'ho-3-tuan',
  },
  {
    dayNumber: 20,
    module: 'SCIENCE_TIP',
    title: `Lo âu nhẹ — não đang sửa.`,
    body: `Stress system não đang reset baseline. 3-5 ngày sẽ qua. Ánh nắng + đi bộ 20 phút giúp regulate cortisol. Không cần thuốc.`,
    pushTime: '10:00',
    wikiSlug: 'lo-au',
  },
  {
    dayNumber: 21,
    module: 'SCIENCE_TIP',
    title: `Lally 2010 — 21 ngày = thói quen?`,
    body: `Lally 2010 thực ra trung bình 66 ngày để thói quen tự động. 21 ngày là điểm khởi đầu — não đã coi không-hút là default, nhưng vẫn cần phòng vệ.`,
    pushTime: '10:00',
    wikiSlug: 'lally-21-ngay',
  },
  {
    dayNumber: 22,
    module: 'SCIENCE_TIP',
    title: `Identity > willpower.`,
    body: `Người nói "tôi đang bỏ" relapse cao hơn người nói "tôi không hút thuốc" 2x (James Clear). Định nghĩa lại bản thân → não follow.`,
    pushTime: '10:00',
    wikiSlug: 'identity-shift',
  },
  {
    dayNumber: 23,
    module: 'SCIENCE_TIP',
    title: `Áp lực xã hội — chuẩn bị.`,
    body: `Người rủ thường không ác ý — họ tự bảo vệ thói quen. Câu ngắn "Mình bỏ rồi" hiệu quả hơn giải thích dài. Càng ngắn càng tự nhiên.`,
    pushTime: '10:00',
    wikiSlug: 'ap-luc-xa-hoi',
  },
  {
    dayNumber: 24,
    module: 'SCIENCE_TIP',
    title: `Tiền tiết kiệm — và dopamine.`,
    body: `Mỗi tuần ~175.000đ. Chuyển sang chi tiêu mang lại dopamine lành mạnh: cuốn sách, bữa ngon, quà cho người thân. Não learn pattern mới.`,
    pushTime: '10:00',
    wikiSlug: 'tien-dopamine',
  },
  {
    dayNumber: 25,
    module: 'SCIENCE_TIP',
    title: `25 ngày — phổi 10% hồi phục.`,
    body: `Theo NHS, sau 1 tháng phổi hồi 10% chức năng. Đến 9 tháng đạt 90%. Cuộc đua dài, từng ngày là 1 bước.`,
    pushTime: '10:00',
    wikiSlug: '25-ngay-phoi',
  },
  {
    dayNumber: 26,
    module: 'SCIENCE_TIP',
    title: `Vị giác phục hồi 80%.`,
    body: `Sau 26 ngày, ~80% nụ vị giác đã sống lại. Bữa cơm vợ nấu ngon hơn 25 năm trước. Đó là phần thưởng sinh học.`,
    pushTime: '10:00',
    wikiSlug: 'vi-giac-80',
  },
  {
    dayNumber: 27,
    module: 'SCIENCE_TIP',
    title: `Cuối tháng — ngủ sâu hơn.`,
    body: `Não REM cycle ổn định lại. Trung bình ngủ sâu thêm 30-45 phút/đêm so với khi hút (NHS). Sáng dậy đỡ mệt — đó là não nghỉ thật sự.`,
    pushTime: '10:00',
    wikiSlug: 'ngu-sau-cuoi-thang',
  },
  {
    dayNumber: 28,
    module: 'SCIENCE_TIP',
    title: `Người 50+ cai — tuổi thọ.`,
    body: `Doll & Hill BMJ 2004: cai trước 60 tuổi → đảo ngược 60% nguy cơ tử vong sớm do hút. Cai trước 50 → 90%. {pronoun} đang đua thời gian thắng.`,
    pushTime: '10:00',
    wikiSlug: 'tuoi-tho-cai',
  },
  {
    dayNumber: 29,
    module: 'SCIENCE_TIP',
    title: `Mai là 30 — sao quan trọng?`,
    body: `30 ngày là cột mốc não bộ ổn định cấu trúc mới. Sau Day 30, "không hút" là default — không cần ý chí mỗi ngày nữa. Đó là khác biệt.`,
    pushTime: '10:00',
    wikiSlug: 'sao-30-ngay-quan-trong',
  },
  {
    dayNumber: 30,
    module: 'SCIENCE_TIP',
    title: `Sau 30 ngày — life change.`,
    body: `Theo Doll & Hill BMJ 2004, cai 30+ tuổi giảm 90% nguy cơ ung thư phổi. 30 ngày này là khởi đầu của phần đời mới — không phải đích đến.`,
    pushTime: '10:00',
    wikiSlug: 'y-nghia-30-ngay',
  },

  // ════════════ PHENOMENA_ALERT × 7 — 14:00 — Cảnh báo trước phenomena trọng yếu ════════════
  {
    dayNumber: 1,
    module: 'PHENOMENA_ALERT',
    title: `Cảnh báo: 21h tối nay khó.`,
    body: `Hầu hết người Việt 45+ có cơn thèm mạnh nhất 19-22h (sau cơm + thư giãn). Tối nay có Plan B chưa? Chuẩn bị: nước lạnh, kẹo bạc hà, đi bộ 5 phút.`,
    pushTime: '14:00',
    wikiSlug: 'phenomena-day-1',
  },
  {
    dayNumber: 3,
    module: 'PHENOMENA_ALERT',
    title: `Đêm nay có thể khó ngủ.`,
    body: `Day 3 não đỉnh điều chỉnh dopamine → khó vào giấc. Tránh cà phê sau 14h. Đọc sách giấy 30 phút trước ngủ. Thở 4-7-8 nếu trằn trọc.`,
    pushTime: '14:00',
    wikiSlug: 'phenomena-mat-ngu',
  },
  {
    dayNumber: 5,
    module: 'PHENOMENA_ALERT',
    title: `Cuối tuần đầu — bẫy lớn.`,
    body: `Cuối tuần là khi guard hạ + thời gian rảnh nhiều. Khoảng 40% relapse xảy ra cuối tuần đầu (Hughes). Tối nay tránh nhậu, tránh tụ tập có người hút.`,
    pushTime: '14:00',
    wikiSlug: 'phenomena-cuoi-tuan',
  },
  {
    dayNumber: 14,
    module: 'PHENOMENA_ALERT',
    title: `Tự tin giả từ hôm nay.`,
    body: `2 tuần sạch — não bắt đầu nói "thử 1 điếu xem". Cảnh báo trước: 1 điếu = relapse 80% trong 7 ngày tới (Cosgrove). Đừng đùa với receptor.`,
    pushTime: '14:00',
    wikiSlug: 'phenomena-tu-tin-gia',
  },
  {
    dayNumber: 17,
    module: 'PHENOMENA_ALERT',
    title: `Nhậu cuối tuần — risky.`,
    body: `Rượu hạ guard + drop dopamine → cơn thèm mạnh trở lại. Nếu phải đi: gọi nước trước, ngồi xa người hút, cớ về sớm. Hoặc skip — không ai giận đâu.`,
    pushTime: '14:00',
    wikiSlug: 'phenomena-nhau',
  },
  {
    dayNumber: 21,
    module: 'PHENOMENA_ALERT',
    title: `Buồn không lý do?`,
    body: `Ngày này nhiều người báo "tự nhiên buồn" — não đang reset baseline cảm xúc. 3-5 ngày sẽ qua. Đi bộ ngoài trời, gọi 1 người thân, viết 3 dòng.`,
    pushTime: '14:00',
    wikiSlug: 'phenomena-buon-vo-co',
  },
  {
    dayNumber: 28,
    module: 'PHENOMENA_ALERT',
    title: `Sắp 30 — đừng buông.`,
    body: `Cảnh báo cuối: nhiều người relapse Day 28-32 vì "đã xong rồi, ăn mừng 1 điếu". 1 điếu = quay lại Day 1. Day 30 không phải đích — là khởi đầu.`,
    pushTime: '14:00',
    wikiSlug: 'phenomena-day-28',
  },

  // ════════════ EXERCISE × 30 — 16:30 — Bài tập 5-10 phút ════════════
  {
    dayNumber: 1,
    module: 'EXERCISE',
    title: `Viết 3 lý do.`,
    body: `Mở Exercise Card. Viết 3 lý do {pronoun} bỏ thuốc — câu ngắn, từ trái tim. Đây sẽ là Plan B của {pronoun} 30 ngày tới.`,
    ctaAction: 'open_exercise:day_1',
    pushTime: '16:30',
    exerciseKey: 'free_text_3_reasons',
  },
  {
    dayNumber: 2,
    module: 'EXERCISE',
    title: `Thở 4-7-8.`,
    body: `Khi thèm: hít 4 giây, giữ 7 giây, thở 8 giây. Lặp 4 lần. Cơn thèm trung bình kéo 3-5 phút — bài này chiếm 4 phút.`,
    ctaAction: 'open_exercise:day_2',
    pushTime: '16:30',
    exerciseKey: 'breathing_4_7_8',
  },
  {
    dayNumber: 3,
    module: 'EXERCISE',
    title: `Liệt kê 5 trigger.`,
    body: `Tình huống nào hay rủ {pronoun} hút? Sau cơm? Cà phê? Nhậu? Stress? Liệt kê 5 cái lớn nhất. Biết rõ = phòng vệ được.`,
    ctaAction: 'open_exercise:day_3',
    pushTime: '16:30',
    exerciseKey: 'list_triggers',
  },
  {
    dayNumber: 4,
    module: 'EXERCISE',
    title: `Đi bộ 10 phút.`,
    body: `Ngoài trời. Không điện thoại. Chỉ thở + nhìn. Đi bộ giảm cortisol 25-30% (Stanford). Đêm nay sẽ ngủ ngon hơn.`,
    ctaAction: 'open_exercise:day_4',
    pushTime: '16:30',
    exerciseKey: 'walk_10_min',
  },
  {
    dayNumber: 5,
    module: 'EXERCISE',
    title: `Uống nước lạnh chậm.`,
    body: `Khi cáu lên: 1 cốc nước lạnh, uống chậm từng ngụm. Nước lạnh kích thích dây vagus → hạ cortisol nhanh. Khoa học, không vớ vẩn.`,
    ctaAction: 'open_exercise:day_5',
    pushTime: '16:30',
    exerciseKey: 'cold_water_pause',
  },
  {
    dayNumber: 6,
    module: 'EXERCISE',
    title: `Note 1 thứ tốt.`,
    body: `Hôm nay {pronoun} thấy 1 điều tốt nhất trong người là gì? Hơi thở dài hơn? Da đỡ xám? Note 1 câu — không cần dài.`,
    ctaAction: 'open_exercise:day_6',
    pushTime: '16:30',
    exerciseKey: 'one_good_thing',
  },
  {
    dayNumber: 7,
    module: 'EXERCISE',
    title: `Tự thưởng nhỏ.`,
    body: `1 tuần xong. Tự mua/làm gì thưởng cho mình? Không phải bữa nhậu — gì khác. Sách, áo, hoa, gọi xe đỡ vợ. Note xuống.`,
    ctaAction: 'open_exercise:day_7',
    pushTime: '16:30',
    exerciseKey: 'self_reward',
  },
  {
    dayNumber: 8,
    module: 'EXERCISE',
    title: `Mạng người hỗ trợ.`,
    body: `Ai trong cuộc sống biết {pronoun} đang bỏ? Liệt kê 3 người. Họ là phòng tuyến — ngày khó nhất gọi 1 người.`,
    ctaAction: 'open_exercise:day_8',
    pushTime: '16:30',
    exerciseKey: 'support_network',
  },
  {
    dayNumber: 9,
    module: 'EXERCISE',
    title: `Đếm cơn thèm.`,
    body: `Hôm nay đếm bao nhiêu cơn thèm. Nhiều/ít không quan trọng — đếm là thấy não đang yếu đi. Note số ở đâu đó.`,
    ctaAction: 'open_exercise:day_9',
    pushTime: '16:30',
    exerciseKey: 'count_cravings',
  },
  {
    dayNumber: 10,
    module: 'EXERCISE',
    title: `Hít thật sâu — cảm phổi.`,
    body: `Đứng thẳng. Hít vào 5 giây, đầy bụng. Giữ 2. Thở ra 7 giây. Lặp 5 lần. Phổi 25 năm cũ giờ đang sửa.`,
    ctaAction: 'open_exercise:day_10',
    pushTime: '16:30',
    exerciseKey: 'deep_breath_5',
  },
  {
    dayNumber: 11,
    module: 'EXERCISE',
    title: `Leo cầu thang chậm.`,
    body: `1 tầng đi lên — đếm số nhịp tim cuối. Sau 11 ngày tim chậm hơn. Mai làm lại — sẽ có số khác.`,
    ctaAction: 'open_exercise:day_11',
    pushTime: '16:30',
    exerciseKey: 'stairs_pulse',
  },
  {
    dayNumber: 12,
    module: 'EXERCISE',
    title: `Ngắm tay mình.`,
    body: `Đặt 2 tay trên bàn. Quan sát 1 phút — màu, ấm, tĩnh mạch. {pronoun} đã trả lại oxy cho bàn tay. Cảm nhận sự sống lại.`,
    ctaAction: 'open_exercise:day_12',
    pushTime: '16:30',
    exerciseKey: 'observe_hands',
  },
  {
    dayNumber: 13,
    module: 'EXERCISE',
    title: `Thư cho mình Day 14.`,
    body: `Viết 3-5 câu cho {pronoun} hôm nay. Mai đọc lại. Đây là chứng cứ {pronoun} đã ở đây.`,
    ctaAction: 'open_exercise:day_13',
    pushTime: '16:30',
    exerciseKey: 'letter_to_self',
  },
  {
    dayNumber: 14,
    module: 'EXERCISE',
    title: `Đo nhịp tim nghỉ.`,
    body: `Ngồi yên 5 phút. Đo nhịp tim 1 phút. So với khi {pronoun} còn hút (~75-85). Số bây giờ = chiến tích.`,
    ctaAction: 'open_exercise:day_14',
    pushTime: '16:30',
    exerciseKey: 'measure_pulse',
  },
  {
    dayNumber: 15,
    module: 'EXERCISE',
    title: `Plan tuần sau.`,
    body: `Liệt kê 1-2 tình huống risky tuần tới (đám cưới? nhậu công ty?). Plan B trước. Đừng để bị surprise.`,
    ctaAction: 'open_exercise:day_15',
    pushTime: '16:30',
    exerciseKey: 'plan_risky_week',
  },
  {
    dayNumber: 16,
    module: 'EXERCISE',
    title: `Cân nhanh.`,
    body: `Cân hôm nay. Note. Trung bình tăng 2-4kg trong 30 ngày là bình thường. Đừng diet — chỉ ăn rau nhiều hơn 1 chút.`,
    ctaAction: 'open_exercise:day_16',
    pushTime: '16:30',
    exerciseKey: 'weigh_in',
  },
  {
    dayNumber: 17,
    module: 'EXERCISE',
    title: `Plan đi tiệc.`,
    body: `Sắp có tiệc/nhậu? Plan: 1 chai nước trước, ngồi xa người hút, cớ về sớm. Hoặc skip — không ai để ý đâu.`,
    ctaAction: 'open_exercise:day_17',
    pushTime: '16:30',
    exerciseKey: 'plan_party',
  },
  {
    dayNumber: 18,
    module: 'EXERCISE',
    title: `Note giấc mơ.`,
    body: `Đêm qua mơ hút? Note 1 dòng. Mơ là não đang dọn ký ức 25 năm. Tỉnh dậy bình thường = thắng.`,
    ctaAction: 'open_exercise:day_18',
    pushTime: '16:30',
    exerciseKey: 'note_dream',
  },
  {
    dayNumber: 19,
    module: 'EXERCISE',
    title: `Dọn 1 ngăn tủ.`,
    body: `Tìm bao thuốc cũ, bật lửa, gạt tàn — bỏ hết. Hành động vật lý giúp não accept "không hút" thật. 5 phút.`,
    ctaAction: 'open_exercise:day_19',
    pushTime: '16:30',
    exerciseKey: 'declutter',
  },
  {
    dayNumber: 20,
    module: 'EXERCISE',
    title: `Đi bộ 20 phút ngoài trời.`,
    body: `Ánh nắng + vận động giảm cortisol, tăng serotonin. Lo âu vô cớ Day 20 sẽ giảm rõ rệt sau 20 phút.`,
    ctaAction: 'open_exercise:day_20',
    pushTime: '16:30',
    exerciseKey: 'walk_20_sun',
  },
  {
    dayNumber: 21,
    module: 'EXERCISE',
    title: `Ăn mừng 21 ngày — nhỏ.`,
    body: `Tự thưởng món ăn mình thích — KHÔNG phải đi nhậu. Bữa cơm chậm rãi, nếm thật sự. Vị giác đã 80% rồi.`,
    ctaAction: 'open_exercise:day_21',
    pushTime: '16:30',
    exerciseKey: 'celebrate_21',
  },
  {
    dayNumber: 22,
    module: 'EXERCISE',
    title: `Nói: "Tôi không hút thuốc".`,
    body: `Nói ra miệng 1 lần. Trước gương, hoặc với người thân. Định nghĩa lại bản thân — não follow.`,
    ctaAction: 'open_exercise:day_22',
    pushTime: '16:30',
    exerciseKey: 'identity_declaration',
  },
  {
    dayNumber: 23,
    module: 'EXERCISE',
    title: `Practice từ chối.`,
    body: `Nếu ai rủ — câu ngắn nào {pronoun} sẽ dùng? "Mình bỏ rồi." Tập nói trong đầu 3 lần. Lúc thật sẽ tự nhiên.`,
    ctaAction: 'open_exercise:day_23',
    pushTime: '16:30',
    exerciseKey: 'practice_refuse',
  },
  {
    dayNumber: 24,
    module: 'EXERCISE',
    title: `Tính tiền tiết kiệm.`,
    body: `24 ngày × giá 1 gói {pronoun} hay hút = ? Note xuống. Tuần sau dùng số đó cho 1 việc lành mạnh — sách, bữa ngon, quà.`,
    ctaAction: 'open_exercise:day_24',
    pushTime: '16:30',
    exerciseKey: 'calc_savings',
  },
  {
    dayNumber: 25,
    module: 'EXERCISE',
    title: `Hơi thở dài.`,
    body: `Hít sâu 5 — giữ 2 — thở 7. Lặp 5 lần. Cảm nhận phổi mới. 25 ngày trước không thấy được như hôm nay.`,
    ctaAction: 'open_exercise:day_25',
    pushTime: '16:30',
    exerciseKey: 'long_breath',
  },
  {
    dayNumber: 26,
    module: 'EXERCISE',
    title: `Bữa ăn chậm.`,
    body: `1 bữa hôm nay — ăn chậm. Nhai kỹ. Nếm thật. Nụ vị giác 80% rồi — bữa cơm thường giờ ngon hơn.`,
    ctaAction: 'open_exercise:day_26',
    pushTime: '16:30',
    exerciseKey: 'slow_meal',
  },
  {
    dayNumber: 27,
    module: 'EXERCISE',
    title: `Plan Day 30 — bình thường.`,
    body: `Day 30 KHÔNG ăn mừng nhậu. Plan: bữa cơm gia đình, đi bộ buổi sáng, gọi 1 người thân. Bình thường = chiến thắng.`,
    ctaAction: 'open_exercise:day_27',
    pushTime: '16:30',
    exerciseKey: 'plan_day_30',
  },
  {
    dayNumber: 28,
    module: 'EXERCISE',
    title: `Liệt kê 5 thay đổi.`,
    body: `Note 5 thay đổi {pronoun} thấy trong người 28 ngày qua. Da, hơi thở, ngủ, vị giác, năng lượng. Đây là chứng cứ.`,
    ctaAction: 'open_exercise:day_28',
    pushTime: '16:30',
    exerciseKey: 'list_changes',
  },
  {
    dayNumber: 29,
    module: 'EXERCISE',
    title: `Đọc lại thư Day 13.`,
    body: `{pronoun} viết thư cho mình Day 13. Hôm nay đọc lại. So với hiện tại — khoảng cách đó là 16 ngày kiên trì.`,
    ctaAction: 'open_exercise:day_29',
    pushTime: '16:30',
    exerciseKey: 'reread_letter',
  },
  {
    dayNumber: 30,
    module: 'EXERCISE',
    title: `Viết Day 60 plan.`,
    body: `30 ngày KHÔNG phải đích — là cột mốc. Viết 3 dòng cho {pronoun} của Day 60: muốn giữ thói quen nào? Tránh tình huống nào?`,
    ctaAction: 'open_exercise:day_30',
    pushTime: '16:30',
    exerciseKey: 'plan_day_60',
  },

  // ════════════ NIGHT_STORY × 30 — 21:30 — Đóng ngày, tự hào nhỏ ════════════
  // Day 1-2: KHỞI ĐỘNG
  {
    dayNumber: 1,
    module: 'NIGHT_STORY',
    title: `Đêm Day 1 — viên đá đầu.`,
    body: `24 giờ sạch nicotin. Cơ thể bắt đầu thải. Đêm nay {pronoun} ngủ với 1 quyết định lớn nhất 25 năm. Mai dễ hơn 1 chút.`,
    pushTime: '21:30',
    wikiSlug: 'dem-1',
  },
  {
    dayNumber: 2,
    module: 'NIGHT_STORY',
    title: `Đêm Day 2 — đỉnh đang qua.`,
    body: `Hôm nay là đỉnh sinh học. {pronoun} đã không hút trong cơn thèm nặng nhất. Đó là chiến thắng não — không chỉ ý chí.`,
    pushTime: '21:30',
    wikiSlug: 'dem-2',
  },
  // Day 3-5: ĐỈNH SÓNG
  {
    dayNumber: 3,
    module: 'NIGHT_STORY',
    title: `Đêm Day 3 — bức tường đã qua.`,
    body: `Ngày khó nhất mà nhiều người không vượt được — {pronoun} vượt rồi. Tỷ lệ thành công tăng 3x từ giờ. Ngủ ngon — đáng lắm.`,
    pushTime: '21:30',
    wikiSlug: 'dem-3',
  },
  {
    dayNumber: 4,
    module: 'NIGHT_STORY',
    title: `Đêm Day 4.`,
    body: `Nếu hôm nay khó ngủ — đó là não đang điều chỉnh. Không phải bệnh. Mai vẫn dậy, vẫn không hút. Đó là cái thắng.`,
    pushTime: '21:30',
    wikiSlug: 'dem-4',
  },
  {
    dayNumber: 5,
    module: 'NIGHT_STORY',
    title: `Đêm Day 5 — gần xong tuần đầu.`,
    body: `Cuối tuần đầu là cuối đường khó nhất. Mai là Day 6. Nicotin sạch. Não đang relearn. {pronoun} đang viết lại 25 năm.`,
    pushTime: '21:30',
    wikiSlug: 'dem-5',
  },
  // Day 6-10: BỨC TƯỜNG
  {
    dayNumber: 6,
    module: 'NIGHT_STORY',
    title: `Đêm Day 6.`,
    body: `Mai là 1 tuần. Hôm nay không cần làm gì đặc biệt — chỉ qua đêm. Đó là phần lớn việc.`,
    pushTime: '21:30',
    wikiSlug: 'dem-6',
  },
  {
    dayNumber: 7,
    module: 'NIGHT_STORY',
    title: `Đêm Day 7 — 1 tuần kỳ tích.`,
    body: `168 giờ sạch. {pronoun} đã làm điều 9/10 người không. {topReason} — 1 tuần rồi vẫn còn đó. Ngủ ngon — mai sang chương mới.`,
    pushTime: '21:30',
    wikiSlug: 'dem-7',
  },
  {
    dayNumber: 8,
    module: 'NIGHT_STORY',
    title: `Đêm Day 8 — tuần 2 bắt đầu.`,
    body: `Cơ chế khác hẳn tuần 1. Bây giờ là tâm lý, không phải sinh lý. Mạnh đã có, dùng đầu tiếp.`,
    pushTime: '21:30',
    wikiSlug: 'dem-8',
  },
  {
    dayNumber: 9,
    module: 'NIGHT_STORY',
    title: `Đêm Day 9 — bình thản.`,
    body: `Đêm nay tim đập chậm. Hơi thở sâu. Đó là cơ thể không hút — và nó cảm ơn {pronoun}.`,
    pushTime: '21:30',
    wikiSlug: 'dem-9',
  },
  {
    dayNumber: 10,
    module: 'NIGHT_STORY',
    title: `Đêm Day 10 — 1/3 chặng.`,
    body: `Phổi đang dọn 25 năm. Khứu giác đang sống lại. Mỗi đêm ngủ là cơ thể tự sửa. Ngủ ngon nhé.`,
    pushTime: '21:30',
    wikiSlug: 'dem-10',
  },
  // Day 11-14: BƯỚC NGOẶT
  {
    dayNumber: 11,
    module: 'NIGHT_STORY',
    title: `Đêm Day 11.`,
    body: `Tim đập chậm hơn. Tuần hoàn ấm hơn. Những thay đổi nhỏ này gộp lại = thêm 5-10 năm tuổi thọ (Doll & Hill).`,
    pushTime: '21:30',
    wikiSlug: 'dem-11',
  },
  {
    dayNumber: 12,
    module: 'NIGHT_STORY',
    title: `Đêm Day 12.`,
    body: `Mai gần Day 14. Hôm nay không quan trọng — vẫn không hút. Sự bình thường này là chiến thắng lớn nhất.`,
    pushTime: '21:30',
    wikiSlug: 'dem-12',
  },
  {
    dayNumber: 13,
    module: 'NIGHT_STORY',
    title: `Đêm Day 13 — mai là 14.`,
    body: `Mai là cột mốc receptor giảm 40%. Không cần thức dậy chuẩn bị — chỉ ngủ ngon, mai não sẽ làm việc của nó.`,
    pushTime: '21:30',
    wikiSlug: 'dem-13',
  },
  {
    dayNumber: 14,
    module: 'NIGHT_STORY',
    title: `Đêm Day 14 — bước ngoặt.`,
    body: `Receptor não giảm 40%. Não bắt đầu coi không-hút là bình thường. Mặt trận tâm lý từ giờ — mạnh đã có. Đêm nay tự hào nhỏ — đáng.`,
    pushTime: '21:30',
    wikiSlug: 'dem-14',
  },
  // Day 15-21: TỰ TIN GIẢ (cảnh báo nhẹ trong night)
  {
    dayNumber: 15,
    module: 'NIGHT_STORY',
    title: `Đêm Day 15 — nửa chặng.`,
    body: `Đẹp. Nhưng đừng ngủ với "đã xong rồi". Mai vẫn đầy ngày. Phòng vệ giữ — não chưa hoàn toàn reset.`,
    pushTime: '21:30',
    wikiSlug: 'dem-15',
  },
  {
    dayNumber: 16,
    module: 'NIGHT_STORY',
    title: `Đêm Day 16.`,
    body: `Tăng cân chút? Bình thường — cơ thể đang sửa. Đừng trừng phạt mình. Cân lên là cơ chế phục hồi, không phải mỡ xấu.`,
    pushTime: '21:30',
    wikiSlug: 'dem-16',
  },
  {
    dayNumber: 17,
    module: 'NIGHT_STORY',
    title: `Đêm Day 17 — sạch sau cuối tuần.`,
    body: `Vượt được tối nay (nhậu/tiệc) — tuần 3 dễ hơn. Mỗi cuối tuần qua = não bớt liên kết "vui = thuốc".`,
    pushTime: '21:30',
    wikiSlug: 'dem-17',
  },
  {
    dayNumber: 18,
    module: 'NIGHT_STORY',
    title: `Đêm Day 18.`,
    body: `Có thể đêm nay mơ hút — bình thường. Não đang dọn ký ức. Mơ KHÔNG phải dấu hiệu thèm thật. Ngủ tiếp.`,
    pushTime: '21:30',
    wikiSlug: 'dem-18',
  },
  {
    dayNumber: 19,
    module: 'NIGHT_STORY',
    title: `Đêm Day 19.`,
    body: `Ho có đờm cuối ngày? Tốt — phổi đang dọn. Ngủ nghiêng, đỡ hơn. Cơ thể đang làm việc khi {pronoun} ngủ.`,
    pushTime: '21:30',
    wikiSlug: 'dem-19',
  },
  {
    dayNumber: 20,
    module: 'NIGHT_STORY',
    title: `Đêm Day 20.`,
    body: `Nếu hôm nay buồn vô cớ — bình thường, sẽ qua. Đêm nay ngủ sâu, mai serotonin về. Cơ thể đang sửa baseline.`,
    pushTime: '21:30',
    wikiSlug: 'dem-20',
  },
  {
    dayNumber: 21,
    module: 'NIGHT_STORY',
    title: `Đêm 3 tuần.`,
    body: `Mạch thần kinh mới đang hình thành khi {pronoun} ngủ. 21 ngày rồi — {topReason} vẫn ở đó, {pronoun} vẫn ở đây. {pronoun} đang viết lại chính mình.`,
    pushTime: '21:30',
    wikiSlug: 'dem-21',
  },
  // Day 22-28: NỘI HÓA
  {
    dayNumber: 22,
    module: 'NIGHT_STORY',
    title: `Đêm Day 22 — identity mới.`,
    body: `"Tôi không hút thuốc" — câu này đêm nay đã đúng. Không "đang cai" — KHÔNG hút. Thời gian quá khứ. Ngủ với điều đó.`,
    pushTime: '21:30',
    wikiSlug: 'dem-22',
  },
  {
    dayNumber: 23,
    module: 'NIGHT_STORY',
    title: `Đêm Day 23.`,
    body: `Hôm nay nếu có ai rủ và {pronoun} nói "không" — đêm nay ngủ với chiến thắng nhỏ. Mỗi lần "không" là 1 lớp não yếu thêm.`,
    pushTime: '21:30',
    wikiSlug: 'dem-23',
  },
  {
    dayNumber: 24,
    module: 'NIGHT_STORY',
    title: `Đêm Day 24.`,
    body: `~600.000đ tiết kiệm. Sức khoẻ cơ thể không đo được bằng tiền. Cộng cả 2 — {pronoun} đã thắng lớn 24 ngày.`,
    pushTime: '21:30',
    wikiSlug: 'dem-24',
  },
  {
    dayNumber: 25,
    module: 'NIGHT_STORY',
    title: `Đêm Day 25.`,
    body: `Phổi đã hồi 10% chức năng. Cơ thể đang đua thời gian. Mỗi đêm ngủ = 1 vòng đua thắng.`,
    pushTime: '21:30',
    wikiSlug: 'dem-25',
  },
  {
    dayNumber: 26,
    module: 'NIGHT_STORY',
    title: `Đêm Day 26.`,
    body: `Bữa cơm tối nay — vị giác có ngon hơn đầu tháng không? Đó là hồi phục thật. Ngủ ngon.`,
    pushTime: '21:30',
    wikiSlug: 'dem-26',
  },
  {
    dayNumber: 27,
    module: 'NIGHT_STORY',
    title: `Đêm Day 27 — sắp 30.`,
    body: `3 đêm nữa. Đừng overthink. Đêm nay sống bình thường — vì bình thường giờ là không hút. Đó là tất cả.`,
    pushTime: '21:30',
    wikiSlug: 'dem-27',
  },
  {
    dayNumber: 28,
    module: 'NIGHT_STORY',
    title: `Đêm Day 28.`,
    body: `2 đêm nữa. Cảnh báo: đừng nhậu mừng. 1 điếu mừng = quay Day 1. {pronoun} đã đi xa quá để quay đầu vì 1 phút bốc đồng.`,
    pushTime: '21:30',
    wikiSlug: 'dem-28',
  },
  // Day 29-30: CỘT MỐC (Khang Sol return)
  {
    dayNumber: 29,
    module: 'NIGHT_STORY',
    title: `Đêm Day 29 — đêm cuối trước cột mốc.`,
    body: `Mình muốn nói thật: 30 ngày đầu tiên là dữ dội nhất. Sau Day 30 là tự nhiên — không phải nỗ lực. {pronoun} đã đi qua phần khó. — Khang Sol`,
    pushTime: '21:30',
    wikiSlug: 'dem-29',
  },
  {
    dayNumber: 30,
    module: 'NIGHT_STORY',
    title: `Đêm 30 NGÀY — tái sinh.`,
    body: `{pronoun} đã hoàn thành. Phổi 30%, tim chậm hơn, não tái cấu trúc. {topReason} — lý do {pronoun} bắt đầu, hôm nay vẫn còn nguyên. Đêm nay ngủ với một con người mới. — Khang Sol`,
    pushTime: '21:30',
    wikiSlug: 'dem-30',
  },
];

// Total: 127 items
// Breakdown: morning=30 science=30 phenomena=7 exercise=30 night=30
// Voice arc 7 giai đoạn: Khởi động → Đỉnh sóng → Bức tường → Bước ngoặt
//                       → Tự tin giả → Nội hóa → Cột mốc
// {topReason} 5 chỗ strategic: Day 1 MORNING, Day 7 NIGHT, Day 14 MORNING,
//                              Day 21 NIGHT, Day 30 NIGHT
