import { PrismaClient, DirCategory, DirStatus, Confidence } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

// ============================================================
// 37 DIRECTIONS — DNA Vectors
// Vectors: VP (0-100 per axis), VR (0-100 per axis), VB (0-100 per axis), VS (0-100 per axis)
// Convention: higher = more required / more suited
// ============================================================

const directions = [
  // ─────────────────────────────────────────────
  // CHUYÊN MÔN & TƯ VẤN (7)
  // ─────────────────────────────────────────────
  {
    name: 'Freelancer Chuyên Môn',
    slug: 'freelancer-chuyen-mon',
    tagline: 'Bán kỹ năng chuyên môn theo dự án',
    category: 'CHUYEN_MON' as DirCategory,
    confidence: 'HIGH' as Confidence,
    sortOrder: 1,
    vpPeople: 35, vpExpert: 95, vpBuilder: 40, vpIndependent: 85,
    vrCapital: 10, vrTime: 50, vrTech: 45, vrNetwork: 50, vrRisk: 15, vrEnergy: 40,
    vbIncomeSpeed: 70, vbIncomePot: 65, vbScalability: 35, vbAiLeverage: 70,
    vsExpLeverage: 95, vsRelLeverage: 50, vsLearningDiff: 25, vsHealthReq: 20,
    description: 'Cung cấp dịch vụ chuyên môn theo dự án cho khách hàng doanh nghiệp hoặc cá nhân.',
    whyFit: 'Phù hợp nhất với người có kiến thức chuyên sâu, muốn làm việc độc lập và kiếm tiền từ kỹ năng tích lũy nhiều năm.',
    barriers: ['Cạnh tranh cao', 'Cần portfolio', 'Thu nhập không đều ban đầu'],
    roadmap30: { weeks: [
      { week: '1-2', task: 'Kiểm kê kỹ năng, xác định 3 dịch vụ core' },
      { week: '3-4', task: 'Tạo portfolio, định giá dịch vụ, tiếp cận 10 khách hàng tiềm năng' },
    ]},
    roadmap90: { months: [
      { month: 2, task: 'Có 2-3 khách hàng đầu, xây dựng quy trình làm việc' },
      { month: 3, task: 'Tối ưu pricing, nhận referral, chuẩn hóa deliverables' },
    ]},
    roadmap180: { summary: 'Thu nhập ổn định 10-20tr/tháng, bắt đầu chọn lọc dự án, xây thương hiệu cá nhân' },
  },
  {
    name: 'Tư Vấn Doanh Nghiệp',
    slug: 'tu-van-doanh-nghiep',
    tagline: 'Cố vấn chiến lược cho doanh nghiệp vừa và nhỏ',
    category: 'CHUYEN_MON' as DirCategory,
    confidence: 'HIGH' as Confidence,
    sortOrder: 2,
    vpPeople: 60, vpExpert: 90, vpBuilder: 50, vpIndependent: 75,
    vrCapital: 15, vrTime: 40, vrTech: 30, vrNetwork: 75, vrRisk: 20, vrEnergy: 50,
    vbIncomeSpeed: 55, vbIncomePot: 85, vbScalability: 45, vbAiLeverage: 55,
    vsExpLeverage: 95, vsRelLeverage: 80, vsLearningDiff: 30, vsHealthReq: 25,
    description: 'Cung cấp dịch vụ tư vấn chiến lược, vận hành, tài chính cho SMEs.',
    whyFit: 'Lý tưởng cho người có 15+ năm kinh nghiệm quản lý, mạng lưới quan hệ rộng.',
    barriers: ['Cần credibility mạnh', 'Chu kỳ bán hàng dài', 'Cạnh tranh với công ty tư vấn lớn'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Xác định niche, xây dựng case studies từ kinh nghiệm cũ, tiếp cận 5 doanh nghiệp quen biết' }]},
    roadmap90: { months: [{ month: 2, task: 'Ký hợp đồng tư vấn đầu tiên, xây framework' }]},
    roadmap180: { summary: 'Có 3-5 clients retainer, doanh thu 30-80tr/tháng' },
  },
  {
    name: 'Chuyên Gia Đào Tạo Nội Bộ',
    slug: 'chuyen-gia-dao-tao-noi-bo',
    tagline: 'Đào tạo kỹ năng cho đội ngũ doanh nghiệp',
    category: 'CHUYEN_MON' as DirCategory,
    confidence: 'HIGH' as Confidence,
    sortOrder: 3,
    vpPeople: 75, vpExpert: 85, vpBuilder: 40, vpIndependent: 65,
    vrCapital: 20, vrTime: 45, vrTech: 35, vrNetwork: 70, vrRisk: 15, vrEnergy: 55,
    vbIncomeSpeed: 60, vbIncomePot: 70, vbScalability: 50, vbAiLeverage: 45,
    vsExpLeverage: 90, vsRelLeverage: 75, vsLearningDiff: 35, vsHealthReq: 35,
    description: 'Thiết kế và thực hiện chương trình đào tạo kỹ năng cho doanh nghiệp.',
    whyFit: 'Phù hợp người vừa có chuyên môn vừa có khả năng truyền đạt, thích làm việc với người.',
    barriers: ['Cần danh tiếng', 'Phụ thuộc vào ngân sách training của DN'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Xây 1 chương trình pilot, tiếp cận HR của 3 doanh nghiệp quen' }]},
    roadmap90: { months: [{ month: 2, task: 'Chạy pilot training, thu thập feedback, chuẩn hóa module' }]},
    roadmap180: { summary: 'Có lịch training đều đặn, 15-40tr/tháng' },
  },
  {
    name: 'Luật Sư / Kế Toán Độc Lập',
    slug: 'luat-su-ke-toan-doc-lap',
    tagline: 'Dịch vụ pháp lý và tài chính cho SMEs',
    category: 'CHUYEN_MON' as DirCategory,
    confidence: 'MEDIUM' as Confidence,
    sortOrder: 4,
    vpPeople: 50, vpExpert: 95, vpBuilder: 30, vpIndependent: 80,
    vrCapital: 30, vrTime: 50, vrTech: 40, vrNetwork: 65, vrRisk: 20, vrEnergy: 45,
    vbIncomeSpeed: 65, vbIncomePot: 80, vbScalability: 40, vbAiLeverage: 60,
    vsExpLeverage: 98, vsRelLeverage: 65, vsLearningDiff: 20, vsHealthReq: 20,
    description: 'Cung cấp dịch vụ pháp lý hoặc kế toán cho cá nhân và doanh nghiệp nhỏ.',
    whyFit: 'Yêu cầu bằng cấp chuyên ngành, phù hợp người đã có hành nghề và muốn độc lập.',
    barriers: ['Yêu cầu chứng chỉ hành nghề', 'Trách nhiệm pháp lý cao'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Đăng ký hành nghề độc lập, tiếp thị đến mạng lưới cũ' }]},
    roadmap90: { months: [{ month: 2, task: 'Có 5-10 clients, chuẩn hóa hợp đồng dịch vụ' }]},
    roadmap180: { summary: '20-50tr/tháng với client base ổn định' },
  },
  {
    name: 'Thiết Kế Độc Lập (Graphic / UX)',
    slug: 'thiet-ke-doc-lap',
    tagline: 'Freelance thiết kế cho doanh nghiệp và startup',
    category: 'CHUYEN_MON' as DirCategory,
    confidence: 'HIGH' as Confidence,
    sortOrder: 5,
    vpPeople: 30, vpExpert: 85, vpBuilder: 65, vpIndependent: 85,
    vrCapital: 15, vrTime: 55, vrTech: 75, vrNetwork: 45, vrRisk: 15, vrEnergy: 50,
    vbIncomeSpeed: 65, vbIncomePot: 60, vbScalability: 40, vbAiLeverage: 80,
    vsExpLeverage: 85, vsRelLeverage: 45, vsLearningDiff: 40, vsHealthReq: 15,
    description: 'Cung cấp dịch vụ thiết kế đồ họa, UI/UX, brand identity cho doanh nghiệp.',
    whyFit: 'Phù hợp người có tư duy sáng tạo, kỹ năng phần mềm thiết kế tốt.',
    barriers: ['Portfolio là yếu tố quyết định', 'AI đang thay thế một phần công việc'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Cập nhật portfolio, đăng ký Fiverr/Upwork, tiếp cận SMEs địa phương' }]},
    roadmap90: { months: [{ month: 2, task: 'Có 3-5 clients đều đặn, tăng giá 20%' }]},
    roadmap180: { summary: '8-20tr/tháng, chuyên biệt hóa vào 1-2 ngành' },
  },
  {
    name: 'Lập Trình Viên Freelance',
    slug: 'lap-trinh-vien-freelance',
    tagline: 'Phát triển phần mềm, website theo dự án',
    category: 'CHUYEN_MON' as DirCategory,
    confidence: 'HIGH' as Confidence,
    sortOrder: 6,
    vpPeople: 25, vpExpert: 90, vpBuilder: 75, vpIndependent: 90,
    vrCapital: 10, vrTime: 60, vrTech: 90, vrNetwork: 40, vrRisk: 15, vrEnergy: 55,
    vbIncomeSpeed: 75, vbIncomePot: 75, vbScalability: 45, vbAiLeverage: 85,
    vsExpLeverage: 90, vsRelLeverage: 40, vsLearningDiff: 45, vsHealthReq: 10,
    description: 'Nhận dự án phát triển phần mềm, ứng dụng, website từ khách hàng trong và ngoài nước.',
    whyFit: 'Lý tưởng cho kỹ sư phần mềm muốn làm việc tự do, có thể khai thác thị trường quốc tế.',
    barriers: ['Cần kỹ năng tự quản lý', 'Cạnh tranh toàn cầu'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Setup profile Upwork/TopTal, nhận 1-2 dự án nhỏ build portfolio' }]},
    roadmap90: { months: [{ month: 2, task: 'Rate cao hơn, dự án dài hạn' }]},
    roadmap180: { summary: '20-60tr/tháng (có thể nhiều hơn với client quốc tế)' },
  },
  {
    name: 'Dịch Thuật Chuyên Ngành',
    slug: 'dich-thuat-chuyen-nganh',
    tagline: 'Dịch thuật tài liệu kỹ thuật, pháp lý, y tế',
    category: 'CHUYEN_MON' as DirCategory,
    confidence: 'MEDIUM' as Confidence,
    sortOrder: 7,
    vpPeople: 25, vpExpert: 85, vpBuilder: 30, vpIndependent: 90,
    vrCapital: 5, vrTime: 65, vrTech: 50, vrNetwork: 40, vrRisk: 10, vrEnergy: 35,
    vbIncomeSpeed: 60, vbIncomePot: 50, vbScalability: 30, vbAiLeverage: 65,
    vsExpLeverage: 90, vsRelLeverage: 35, vsLearningDiff: 30, vsHealthReq: 10,
    description: 'Dịch tài liệu chuyên ngành (kỹ thuật, y tế, pháp lý, kinh doanh) Anh-Việt và ngược lại.',
    whyFit: 'Phù hợp người thành thạo ngoại ngữ và có chuyên môn ngành.',
    barriers: ['AI dịch ngày càng tốt', 'Giá thấp nếu không có niche rõ ràng'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Đăng ký ProZ, Gengo, tiếp cận công ty xuất nhập khẩu địa phương' }]},
    roadmap90: { months: [{ month: 2, task: 'Chuyên biệt hóa 1 ngành, tăng giá 50%' }]},
    roadmap180: { summary: '5-15tr/tháng, có thể kết hợp với biên phiên dịch' },
  },

  // ─────────────────────────────────────────────
  // ĐÀO TẠO & COACHING (5)
  // ─────────────────────────────────────────────
  {
    name: 'Life Coaching / Career Coaching',
    slug: 'life-coaching',
    tagline: 'Hỗ trợ cá nhân phát triển bản thân và sự nghiệp',
    category: 'DAO_TAO' as DirCategory,
    confidence: 'HIGH' as Confidence,
    sortOrder: 1,
    vpPeople: 90, vpExpert: 70, vpBuilder: 45, vpIndependent: 75,
    vrCapital: 15, vrTime: 50, vrTech: 35, vrNetwork: 60, vrRisk: 20, vrEnergy: 65,
    vbIncomeSpeed: 50, vbIncomePot: 70, vbScalability: 55, vbAiLeverage: 50,
    vsExpLeverage: 80, vsRelLeverage: 65, vsLearningDiff: 50, vsHealthReq: 40,
    description: 'Coaching 1:1 hoặc nhóm giúp khách hàng đạt mục tiêu cá nhân, nghề nghiệp.',
    whyFit: 'Phù hợp người có khả năng lắng nghe, empathy cao, kinh nghiệm sống phong phú.',
    barriers: ['Cần chứng chỉ ICF để tăng credibility', 'Khó định giá ban đầu'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Học khóa coaching căn bản, bắt đầu với 3 client pro-bono để lấy testimonials' }]},
    roadmap90: { months: [{ month: 2, task: 'Charging fee, có 5-8 clients, xây personal brand' }]},
    roadmap180: { summary: '10-30tr/tháng, package coaching rõ ràng, group program' },
  },
  {
    name: 'Giảng Dạy Online (Khóa Học)',
    slug: 'giang-day-online',
    tagline: 'Tạo và bán khóa học trực tuyến',
    category: 'DAO_TAO' as DirCategory,
    confidence: 'HIGH' as Confidence,
    sortOrder: 2,
    vpPeople: 65, vpExpert: 85, vpBuilder: 70, vpIndependent: 80,
    vrCapital: 30, vrTime: 70, vrTech: 65, vrNetwork: 55, vrRisk: 35, vrEnergy: 60,
    vbIncomeSpeed: 30, vbIncomePot: 90, vbScalability: 90, vbAiLeverage: 75,
    vsExpLeverage: 90, vsRelLeverage: 55, vsLearningDiff: 55, vsHealthReq: 20,
    description: 'Thiết kế và bán khóa học online trên Udemy, Kyna, hoặc website riêng.',
    whyFit: 'Phù hợp người muốn thu nhập thụ động dài hạn, sẵn sàng đầu tư thời gian ban đầu.',
    barriers: ['Cần thời gian dài để xây audience', 'Chất lượng video & âm thanh quan trọng'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Outline khóa học, quay pilot module, upload lên 1 platform' }]},
    roadmap90: { months: [{ month: 2, task: 'Hoàn chỉnh khóa học, marketing, có 50+ học viên đầu' }]},
    roadmap180: { summary: 'Thu nhập thụ động 5-20tr/tháng tùy niche' },
  },
  {
    name: 'Gia Sư / Dạy Kèm',
    slug: 'gia-su-day-kem',
    tagline: 'Dạy kèm học sinh hoặc người học ngành nghề',
    category: 'DAO_TAO' as DirCategory,
    confidence: 'HIGH' as Confidence,
    sortOrder: 3,
    vpPeople: 80, vpExpert: 75, vpBuilder: 25, vpIndependent: 65,
    vrCapital: 5, vrTime: 60, vrTech: 25, vrNetwork: 55, vrRisk: 5, vrEnergy: 55,
    vbIncomeSpeed: 85, vbIncomePot: 45, vbScalability: 25, vbAiLeverage: 35,
    vsExpLeverage: 80, vsRelLeverage: 60, vsLearningDiff: 20, vsHealthReq: 30,
    description: 'Dạy kèm các môn học, ngoại ngữ, hoặc kỹ năng nghề nghiệp.',
    whyFit: 'Entry barrier thấp nhất, thu nhập ngay. Phù hợp người có kiến thức nền tốt.',
    barriers: ['Thu nhập có giới hạn (đổi thời gian lấy tiền)', 'Khó scale'],
    roadmap30: { weeks: [{ week: '1-2', task: 'Đăng tin tìm học sinh, tiếp thị qua mạng xã hội cá nhân' }]},
    roadmap90: { months: [{ month: 2, task: 'Có 5-10 học sinh đều đặn, có thể dạy nhóm' }]},
    roadmap180: { summary: '5-15tr/tháng, mở lớp nhóm để tăng thu nhập' },
  },
  {
    name: 'Workshop Chuyên Đề',
    slug: 'workshop-chuyen-de',
    tagline: 'Tổ chức workshop offline/online theo chuyên đề',
    category: 'DAO_TAO' as DirCategory,
    confidence: 'MEDIUM' as Confidence,
    sortOrder: 4,
    vpPeople: 80, vpExpert: 80, vpBuilder: 60, vpIndependent: 65,
    vrCapital: 40, vrTime: 50, vrTech: 45, vrNetwork: 70, vrRisk: 35, vrEnergy: 70,
    vbIncomeSpeed: 55, vbIncomePot: 65, vbScalability: 60, vbAiLeverage: 50,
    vsExpLeverage: 85, vsRelLeverage: 75, vsLearningDiff: 40, vsHealthReq: 45,
    description: 'Tổ chức workshop 1-2 ngày về chủ đề chuyên môn cho nhóm 10-50 người.',
    whyFit: 'Phù hợp người thích nói trước đám đông, có network để quảng bá.',
    barriers: ['Rủi ro lấp đầy ghế', 'Cần logistics và marketing'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Thiết kế 1 workshop pilot, invite 20 người từ network, charge phí thấp' }]},
    roadmap90: { months: [{ month: 2, task: 'Tổ chức workshop thứ 2 với giá cao hơn, thu thập testimonials' }]},
    roadmap180: { summary: '5-20tr/workshop, 2-4 workshop/tháng' },
  },
  {
    name: 'Mentoring Doanh Nhân Trẻ',
    slug: 'mentoring-doanh-nhan',
    tagline: 'Hướng dẫn và đồng hành doanh nhân khởi nghiệp',
    category: 'DAO_TAO' as DirCategory,
    confidence: 'MEDIUM' as Confidence,
    sortOrder: 5,
    vpPeople: 85, vpExpert: 80, vpBuilder: 50, vpIndependent: 70,
    vrCapital: 10, vrTime: 35, vrTech: 30, vrNetwork: 80, vrRisk: 15, vrEnergy: 50,
    vbIncomeSpeed: 40, vbIncomePot: 60, vbScalability: 40, vbAiLeverage: 40,
    vsExpLeverage: 90, vsRelLeverage: 85, vsLearningDiff: 30, vsHealthReq: 25,
    description: 'Mentoring 1:1 cho doanh nhân khởi nghiệp từ kinh nghiệm thực chiến.',
    whyFit: 'Lý tưởng cho cựu CEO/founder muốn truyền kinh nghiệm, ít thời gian nhưng có impact cao.',
    barriers: ['Khó định giá', 'Cần danh tiếng trước'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Thử nghiệm 3 session mentoring miễn phí với startup quen' }]},
    roadmap90: { months: [{ month: 2, task: 'Charging 1-3tr/session, có 4-6 mentees' }]},
    roadmap180: { summary: '5-15tr/tháng, uy tín tăng theo thời gian' },
  },

  // ─────────────────────────────────────────────
  // NỘI DUNG SỐ & CREATOR (6)
  // ─────────────────────────────────────────────
  {
    name: 'Blog / Website Chuyên Môn',
    slug: 'blog-chuyen-mon',
    tagline: 'Viết blog chia sẻ kiến thức chuyên ngành',
    category: 'NOI_DUNG_SO' as DirCategory,
    confidence: 'HIGH' as Confidence,
    sortOrder: 1,
    vpPeople: 30, vpExpert: 85, vpBuilder: 65, vpIndependent: 85,
    vrCapital: 20, vrTime: 70, vrTech: 50, vrNetwork: 40, vrRisk: 15, vrEnergy: 40,
    vbIncomeSpeed: 15, vbIncomePot: 75, vbScalability: 85, vbAiLeverage: 80,
    vsExpLeverage: 85, vsRelLeverage: 40, vsLearningDiff: 45, vsHealthReq: 10,
    description: 'Xây dựng blog chuyên môn để thu hút traffic, monetize qua affiliate, ads, khóa học.',
    whyFit: 'Phù hợp người thích viết, có kiến thức chuyên sâu, kiên nhẫn dài hạn.',
    barriers: ['Mất 6-12 tháng mới có traffic đáng kể', 'Cần nhất quán'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Setup website, viết 8 bài đầu, nghiên cứu SEO cơ bản' }]},
    roadmap90: { months: [{ month: 2, task: '20-30 bài, bắt đầu có traffic organic' }]},
    roadmap180: { summary: 'Traffic 5,000-20,000/tháng, monetize 3-10tr/tháng' },
  },
  {
    name: 'YouTube Channel',
    slug: 'youtube-channel',
    tagline: 'Kênh YouTube chia sẻ kiến thức và kinh nghiệm',
    category: 'NOI_DUNG_SO' as DirCategory,
    confidence: 'MEDIUM' as Confidence,
    sortOrder: 2,
    vpPeople: 55, vpExpert: 80, vpBuilder: 65, vpIndependent: 80,
    vrCapital: 40, vrTime: 75, vrTech: 65, vrNetwork: 45, vrRisk: 25, vrEnergy: 65,
    vbIncomeSpeed: 10, vbIncomePot: 85, vbScalability: 90, vbAiLeverage: 70,
    vsExpLeverage: 85, vsRelLeverage: 50, vsLearningDiff: 55, vsHealthReq: 30,
    description: 'Tạo nội dung video trên YouTube để chia sẻ kiến thức và xây dựng thu nhập.',
    whyFit: 'Phù hợp người tự tin trước camera, kiên nhẫn với quá trình dài.',
    barriers: ['Mất 12-18 tháng để có thu nhập đáng kể', 'Yêu cầu chất lượng video/âm thanh'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Setup kênh, thiết bị cơ bản, quay 4 video đầu' }]},
    roadmap90: { months: [{ month: 2, task: '15+ video, test format, tìm ra content nào được yêu thích' }]},
    roadmap180: { summary: '1,000+ subscriber, bắt đầu monetize qua affiliate' },
  },
  {
    name: 'Podcast',
    slug: 'podcast',
    tagline: 'Podcast chuyên đề cho cộng đồng nghe',
    category: 'NOI_DUNG_SO' as DirCategory,
    confidence: 'LOW' as Confidence,
    sortOrder: 3,
    vpPeople: 60, vpExpert: 75, vpBuilder: 55, vpIndependent: 80,
    vrCapital: 25, vrTime: 65, vrTech: 55, vrNetwork: 55, vrRisk: 20, vrEnergy: 55,
    vbIncomeSpeed: 10, vbIncomePot: 60, vbScalability: 70, vbAiLeverage: 55,
    vsExpLeverage: 80, vsRelLeverage: 60, vsLearningDiff: 40, vsHealthReq: 20,
    description: 'Sản xuất podcast chuyên đề để xây dựng audience và brand.',
    whyFit: 'Phù hợp người thích trò chuyện, có mạng lưới guest tốt.',
    barriers: ['Thị trường podcast VN còn nhỏ', 'Monetize khó hơn YouTube'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Setup, record 3 tập pilot, phát hành trên Spotify/Apple' }]},
    roadmap90: { months: [{ month: 2, task: '15 tập, có 200-500 listener đều đặn' }]},
    roadmap180: { summary: 'Sponsorship, cross-sell khóa học' },
  },
  {
    name: 'Viết Sách / Ebook',
    slug: 'viet-sach-ebook',
    tagline: 'Xuất bản sách hoặc ebook chuyên môn',
    category: 'NOI_DUNG_SO' as DirCategory,
    confidence: 'MEDIUM' as Confidence,
    sortOrder: 4,
    vpPeople: 25, vpExpert: 90, vpBuilder: 50, vpIndependent: 90,
    vrCapital: 15, vrTime: 80, vrTech: 35, vrNetwork: 45, vrRisk: 20, vrEnergy: 40,
    vbIncomeSpeed: 10, vbIncomePot: 65, vbScalability: 85, vbAiLeverage: 75,
    vsExpLeverage: 90, vsRelLeverage: 45, vsLearningDiff: 40, vsHealthReq: 10,
    description: 'Viết và tự xuất bản sách hoặc ebook về chủ đề chuyên môn.',
    whyFit: 'Phù hợp người có kiến thức sâu, thích viết, muốn để lại di sản.',
    barriers: ['Thu nhập thấp nếu không có audience sẵn', 'Cần marketing'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Outline, viết 3 chương đầu, validate với 10 người đọc thử' }]},
    roadmap90: { months: [{ month: 2, task: 'Hoàn thành bản thảo, chỉnh sửa' }]},
    roadmap180: { summary: 'Xuất bản, dùng sách làm lead magnet hoặc bán direct' },
  },
  {
    name: 'Newsletter / Substack',
    slug: 'newsletter',
    tagline: 'Newsletter chuyên đề có trả phí',
    category: 'NOI_DUNG_SO' as DirCategory,
    confidence: 'LOW' as Confidence,
    sortOrder: 5,
    vpPeople: 35, vpExpert: 85, vpBuilder: 55, vpIndependent: 85,
    vrCapital: 10, vrTime: 60, vrTech: 45, vrNetwork: 50, vrRisk: 15, vrEnergy: 40,
    vbIncomeSpeed: 15, vbIncomePot: 60, vbScalability: 75, vbAiLeverage: 75,
    vsExpLeverage: 85, vsRelLeverage: 50, vsLearningDiff: 35, vsHealthReq: 10,
    description: 'Viết newsletter định kỳ có trả phí về chủ đề chuyên môn.',
    whyFit: 'Phù hợp người viết tốt, có góc nhìn độc đáo, audience tiếng Anh hoặc chuyên ngành.',
    barriers: ['Substack VN chưa phổ biến', 'Cần audience sẵn có'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Publish 4 bản newsletter miễn phí, tăng subscriber' }]},
    roadmap90: { months: [{ month: 2, task: 'Có 300-500 free sub, launch paid plan' }]},
    roadmap180: { summary: '50-200 paid subscribers × 99k = 5-20tr/tháng' },
  },
  {
    name: 'Affiliate Marketing',
    slug: 'affiliate-marketing',
    tagline: 'Kiếm hoa hồng từ giới thiệu sản phẩm',
    category: 'NOI_DUNG_SO' as DirCategory,
    confidence: 'MEDIUM' as Confidence,
    sortOrder: 6,
    vpPeople: 45, vpExpert: 55, vpBuilder: 65, vpIndependent: 85,
    vrCapital: 20, vrTime: 65, vrTech: 60, vrNetwork: 50, vrRisk: 20, vrEnergy: 45,
    vbIncomeSpeed: 20, vbIncomePot: 70, vbScalability: 85, vbAiLeverage: 75,
    vsExpLeverage: 65, vsRelLeverage: 55, vsLearningDiff: 50, vsHealthReq: 10,
    description: 'Xây kênh content để giới thiệu sản phẩm/dịch vụ và nhận hoa hồng.',
    whyFit: 'Phù hợp người thích content, muốn thu nhập thụ động.',
    barriers: ['Cần traffic lớn để có thu nhập đáng kể', 'Thuật toán platform thay đổi liên tục'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Chọn niche, đăng ký affiliate programs, tạo 10 bài review' }]},
    roadmap90: { months: [{ month: 2, task: 'Scale content, SEO, link building' }]},
    roadmap180: { summary: '3-15tr/tháng passive income' },
  },

  // ─────────────────────────────────────────────
  // KINH DOANH NHỎ (7)
  // ─────────────────────────────────────────────
  {
    name: 'Kinh Doanh Online 1 Người',
    slug: 'kinh-doanh-online-1-nguoi',
    tagline: 'Bán hàng online qua mạng xã hội và sàn TMĐT',
    category: 'KINH_DOANH' as DirCategory,
    confidence: 'HIGH' as Confidence,
    sortOrder: 1,
    vpPeople: 60, vpExpert: 45, vpBuilder: 70, vpIndependent: 75,
    vrCapital: 45, vrTime: 65, vrTech: 50, vrNetwork: 55, vrRisk: 40, vrEnergy: 65,
    vbIncomeSpeed: 60, vbIncomePot: 65, vbScalability: 60, vbAiLeverage: 60,
    vsExpLeverage: 55, vsRelLeverage: 60, vsLearningDiff: 45, vsHealthReq: 35,
    description: 'Kinh doanh sản phẩm qua Facebook, TikTok, Shopee, Lazada.',
    whyFit: 'Phù hợp người năng động, thích kinh doanh nhưng không muốn cửa hàng cố định.',
    barriers: ['Cạnh tranh cao', 'Cần vốn hàng tồn', 'Logistics phức tạp'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Chọn sản phẩm, tìm nhà cung cấp, mở shop Shopee, chạy test 50 đơn' }]},
    roadmap90: { months: [{ month: 2, task: 'Tối ưu listing, review, scale ads' }]},
    roadmap180: { summary: '10-30tr/tháng lợi nhuận nếu chọn đúng sản phẩm' },
  },
  {
    name: 'Dropshipping',
    slug: 'dropshipping',
    tagline: 'Bán hàng không cần kho, nhà cung cấp giao trực tiếp',
    category: 'KINH_DOANH' as DirCategory,
    confidence: 'MEDIUM' as Confidence,
    sortOrder: 2,
    vpPeople: 40, vpExpert: 40, vpBuilder: 70, vpIndependent: 80,
    vrCapital: 25, vrTime: 60, vrTech: 65, vrNetwork: 40, vrRisk: 35, vrEnergy: 55,
    vbIncomeSpeed: 45, vbIncomePot: 65, vbScalability: 80, vbAiLeverage: 70,
    vsExpLeverage: 40, vsRelLeverage: 35, vsLearningDiff: 55, vsHealthReq: 15,
    description: 'Bán hàng online không cần kho. Đơn hàng đổ về, nhà cung cấp ship thẳng cho khách.',
    whyFit: 'Phù hợp người muốn kinh doanh với vốn thấp, kỹ năng digital marketing.',
    barriers: ['Margin thấp', 'Cạnh tranh cao từ Trung Quốc', 'Khó kiểm soát chất lượng'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Research sản phẩm winning, setup Shopify/Shopee, chạy ads test' }]},
    roadmap90: { months: [{ month: 2, task: 'Scale winning products' }]},
    roadmap180: { summary: '5-20tr/tháng, cần vốn ads liên tục' },
  },
  {
    name: 'Kinh Doanh Đồ Gia Dụng / Nội Thất',
    slug: 'kinh-doanh-do-gia-dung',
    tagline: 'Nhập và phân phối đồ gia dụng, nội thất',
    category: 'KINH_DOANH' as DirCategory,
    confidence: 'HIGH' as Confidence,
    sortOrder: 3,
    vpPeople: 55, vpExpert: 40, vpBuilder: 65, vpIndependent: 70,
    vrCapital: 65, vrTime: 65, vrTech: 40, vrNetwork: 60, vrRisk: 50, vrEnergy: 65,
    vbIncomeSpeed: 55, vbIncomePot: 70, vbScalability: 55, vbAiLeverage: 45,
    vsExpLeverage: 50, vsRelLeverage: 65, vsLearningDiff: 35, vsHealthReq: 45,
    description: 'Nhập hàng gia dụng, nội thất từ nhà sản xuất, bán qua online và offline.',
    whyFit: 'Phù hợp người có vốn, mạng lưới nhà cung cấp, hiểu thị trường địa phương.',
    barriers: ['Cần vốn hàng tồn cao', 'Logistics cồng kềnh'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Nghiên cứu thị trường, tìm 3 nhà cung cấp, thử nghiệm 20 SKU' }]},
    roadmap90: { months: [{ month: 2, task: 'Có kho nhỏ, scale online, thêm kênh phân phối' }]},
    roadmap180: { summary: '15-50tr/tháng lợi nhuận' },
  },
  {
    name: 'Đại Lý / Nhà Phân Phối',
    slug: 'dai-ly-nha-phan-phoi',
    tagline: 'Làm đại lý phân phối cho thương hiệu có sẵn',
    category: 'KINH_DOANH' as DirCategory,
    confidence: 'HIGH' as Confidence,
    sortOrder: 4,
    vpPeople: 65, vpExpert: 40, vpBuilder: 55, vpIndependent: 65,
    vrCapital: 60, vrTime: 65, vrTech: 35, vrNetwork: 70, vrRisk: 45, vrEnergy: 65,
    vbIncomeSpeed: 60, vbIncomePot: 65, vbScalability: 50, vbAiLeverage: 35,
    vsExpLeverage: 55, vsRelLeverage: 75, vsLearningDiff: 30, vsHealthReq: 50,
    description: 'Làm đại lý cấp 1/2 cho nhãn hàng, phân phối qua mạng lưới bán lẻ.',
    whyFit: 'Phù hợp người có vốn, mạng lưới khách hàng, kinh nghiệm bán hàng B2B.',
    barriers: ['Vốn ban đầu lớn', 'Phụ thuộc vào chính sách của nhãn hàng'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Chọn ngành hàng, tiếp cận 5-10 nhãn hàng xin đại lý' }]},
    roadmap90: { months: [{ month: 2, task: 'Ký được 1-2 hợp đồng đại lý, xây mạng lưới bán lẻ' }]},
    roadmap180: { summary: '20-80tr/tháng tùy ngành hàng' },
  },
  {
    name: 'Nhượng Quyền Thương Hiệu',
    slug: 'nhuong-quyen-thuong-hieu',
    tagline: 'Mở kinh doanh theo mô hình franchise',
    category: 'KINH_DOANH' as DirCategory,
    confidence: 'MEDIUM' as Confidence,
    sortOrder: 5,
    vpPeople: 60, vpExpert: 35, vpBuilder: 55, vpIndependent: 50,
    vrCapital: 80, vrTime: 70, vrTech: 35, vrNetwork: 55, vrRisk: 55, vrEnergy: 70,
    vbIncomeSpeed: 65, vbIncomePot: 70, vbScalability: 40, vbAiLeverage: 30,
    vsExpLeverage: 45, vsRelLeverage: 50, vsLearningDiff: 35, vsHealthReq: 60,
    description: 'Mua franchise của thương hiệu F&B, dịch vụ, giáo dục đã có hệ thống.',
    whyFit: 'Phù hợp người có vốn lớn, muốn kinh doanh nhưng không muốn build từ đầu.',
    barriers: ['Vốn đầu tư ban đầu cao', 'Phụ thuộc brand chính', 'Tỷ lệ thất bại vẫn cao'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Research 10 thương hiệu franchise phù hợp, thăm thực tế' }]},
    roadmap90: { months: [{ month: 2, task: 'Ký hợp đồng, chuẩn bị mặt bằng' }]},
    roadmap180: { summary: 'Breakeven sau 12-24 tháng tùy ngành' },
  },
  {
    name: 'Kinh Doanh Thực Phẩm Đặc Sản',
    slug: 'kinh-doanh-thuc-pham-dac-san',
    tagline: 'Bán đặc sản vùng miền qua mạng',
    category: 'KINH_DOANH' as DirCategory,
    confidence: 'HIGH' as Confidence,
    sortOrder: 6,
    vpPeople: 60, vpExpert: 45, vpBuilder: 60, vpIndependent: 70,
    vrCapital: 35, vrTime: 65, vrTech: 45, vrNetwork: 60, vrRisk: 35, vrEnergy: 65,
    vbIncomeSpeed: 55, vbIncomePot: 60, vbScalability: 60, vbAiLeverage: 50,
    vsExpLeverage: 55, vsRelLeverage: 65, vsLearningDiff: 35, vsHealthReq: 45,
    description: 'Tìm nguồn và bán đặc sản địa phương, thực phẩm sạch qua online.',
    whyFit: 'Phù hợp người có mối quan hệ địa phương, hiểu văn hóa vùng miền.',
    barriers: ['An toàn thực phẩm', 'Logistics cho hàng tươi sống'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Xác định 5 sản phẩm, tìm nguồn, thử nghiệm 30 đơn đầu' }]},
    roadmap90: { months: [{ month: 2, task: 'Xây thương hiệu riêng, mở rộng sản phẩm' }]},
    roadmap180: { summary: '5-20tr/tháng, có thể scale qua sàn TMĐT' },
  },
  {
    name: 'Kinh Doanh Handmade / Thủ Công',
    slug: 'kinh-doanh-handmade',
    tagline: 'Làm và bán sản phẩm thủ công mỹ nghệ',
    category: 'KINH_DOANH' as DirCategory,
    confidence: 'MEDIUM' as Confidence,
    sortOrder: 7,
    vpPeople: 50, vpExpert: 65, vpBuilder: 70, vpIndependent: 80,
    vrCapital: 25, vrTime: 75, vrTech: 35, vrNetwork: 45, vrRisk: 20, vrEnergy: 55,
    vbIncomeSpeed: 45, vbIncomePot: 50, vbScalability: 40, vbAiLeverage: 35,
    vsExpLeverage: 70, vsRelLeverage: 45, vsLearningDiff: 25, vsHealthReq: 40,
    description: 'Tạo và bán sản phẩm handmade: gốm, đan móc, gỗ, candle, jewelry.',
    whyFit: 'Phù hợp người có kỹ năng thủ công, thích sáng tạo, muốn làm việc tại nhà.',
    barriers: ['Thời gian tạo sản phẩm lớn', 'Giá bán bị giới hạn bởi thị trường'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Tạo 20 sản phẩm mẫu, chụp ảnh đẹp, mở shop Etsy/Shopee' }]},
    roadmap90: { months: [{ month: 2, task: 'Có đơn hàng đều, tăng giá, tạo bộ sưu tập' }]},
    roadmap180: { summary: '3-15tr/tháng, workshop dạy làm handmade để tăng thu' },
  },

  // ─────────────────────────────────────────────
  // DỊCH VỤ HÀNG NGÀY (5)
  // ─────────────────────────────────────────────
  {
    name: 'Dịch Vụ Vận Chuyển / Giao Hàng',
    slug: 'van-chuyen-giao-hang',
    tagline: 'Vận chuyển hàng hóa, giao hàng chặng cuối',
    category: 'DAILY' as DirCategory,
    confidence: 'HIGH' as Confidence,
    sortOrder: 1,
    vpPeople: 55, vpExpert: 25, vpBuilder: 45, vpIndependent: 70,
    vrCapital: 40, vrTime: 80, vrTech: 40, vrNetwork: 50, vrRisk: 30, vrEnergy: 75,
    vbIncomeSpeed: 85, vbIncomePot: 45, vbScalability: 50, vbAiLeverage: 40,
    vsExpLeverage: 30, vsRelLeverage: 55, vsLearningDiff: 15, vsHealthReq: 75,
    description: 'Cung cấp dịch vụ vận chuyển, giao hàng cho cá nhân và doanh nghiệp địa phương.',
    whyFit: 'Phù hợp người có phương tiện, muốn thu nhập ngay, thích vận động.',
    barriers: ['Thu nhập giới hạn theo thời gian làm việc', 'Hao mòn phương tiện'],
    roadmap30: { weeks: [{ week: '1-2', task: 'Đăng ký GrabExpress/GHTK, bắt đầu nhận đơn' }]},
    roadmap90: { months: [{ month: 2, task: 'Xây khách hàng cố định, tăng giá dịch vụ' }]},
    roadmap180: { summary: '5-15tr/tháng, có thể thuê thêm tài xế để scale' },
  },
  {
    name: 'Sửa Chữa Nhà / Điện Nước',
    slug: 'sua-chua-nha',
    tagline: 'Dịch vụ sửa chữa nhà, điện nước, nội thất',
    category: 'DAILY' as DirCategory,
    confidence: 'HIGH' as Confidence,
    sortOrder: 2,
    vpPeople: 55, vpExpert: 65, vpBuilder: 65, vpIndependent: 70,
    vrCapital: 25, vrTime: 70, vrTech: 35, vrNetwork: 55, vrRisk: 25, vrEnergy: 75,
    vbIncomeSpeed: 80, vbIncomePot: 55, vbScalability: 45, vbAiLeverage: 30,
    vsExpLeverage: 70, vsRelLeverage: 60, vsLearningDiff: 25, vsHealthReq: 70,
    description: 'Nhận sửa chữa nhà cửa, điện nước, nội thất cho hộ gia đình.',
    whyFit: 'Phù hợp người có tay nghề kỹ thuật, muốn làm chủ thời gian.',
    barriers: ['Nặng nhọc', 'Khó tìm thợ phụ đáng tin'],
    roadmap30: { weeks: [{ week: '1-2', task: 'Quảng cáo trên Zalo, Facebook nhóm địa phương, nhận 5 job đầu' }]},
    roadmap90: { months: [{ month: 2, task: 'Xây khách hàng quen, nhận job qua referral' }]},
    roadmap180: { summary: '10-25tr/tháng, có thể thành lập tổ đội' },
  },
  {
    name: 'Dịch Vụ Vệ Sinh / Dọn Dẹp',
    slug: 'dich-vu-ve-sinh',
    tagline: 'Vệ sinh nhà, văn phòng, công trình',
    category: 'DAILY' as DirCategory,
    confidence: 'MEDIUM' as Confidence,
    sortOrder: 3,
    vpPeople: 50, vpExpert: 25, vpBuilder: 55, vpIndependent: 65,
    vrCapital: 20, vrTime: 75, vrTech: 25, vrNetwork: 50, vrRisk: 20, vrEnergy: 80,
    vbIncomeSpeed: 85, vbIncomePot: 45, vbScalability: 60, vbAiLeverage: 25,
    vsExpLeverage: 25, vsRelLeverage: 50, vsLearningDiff: 10, vsHealthReq: 80,
    description: 'Cung cấp dịch vụ vệ sinh nhà ở, văn phòng, hậu xây dựng.',
    whyFit: 'Entry barrier thấp, thu nhập ngay, có thể mở rộng thành đội.',
    barriers: ['Tuyển dụng và giữ nhân viên khó', 'Thị trường phân tán'],
    roadmap30: { weeks: [{ week: '1-2', task: 'Mua dụng cụ, đăng trên BTaskee/Việc Làm Tốt, nhận job đầu' }]},
    roadmap90: { months: [{ month: 2, task: 'Có 10-15 khách hàng cố định, thuê thêm người' }]},
    roadmap180: { summary: '10-30tr/tháng với đội 3-5 người' },
  },
  {
    name: 'Chăm Sóc Sức Khỏe Tại Nhà',
    slug: 'cham-soc-suc-khoe-tai-nha',
    tagline: 'Điều dưỡng, chăm sóc người cao tuổi tại nhà',
    category: 'DAILY' as DirCategory,
    confidence: 'MEDIUM' as Confidence,
    sortOrder: 4,
    vpPeople: 85, vpExpert: 70, vpBuilder: 30, vpIndependent: 60,
    vrCapital: 15, vrTime: 70, vrTech: 25, vrNetwork: 55, vrRisk: 30, vrEnergy: 70,
    vbIncomeSpeed: 75, vbIncomePot: 55, vbScalability: 45, vbAiLeverage: 30,
    vsExpLeverage: 75, vsRelLeverage: 60, vsLearningDiff: 30, vsHealthReq: 65,
    description: 'Cung cấp dịch vụ chăm sóc sức khỏe, điều dưỡng cho người cao tuổi và bệnh nhân tại nhà.',
    whyFit: 'Phù hợp người có chuyên môn y tế, hoặc kinh nghiệm chăm sóc, giàu empathy.',
    barriers: ['Trách nhiệm cao', 'Nhu cầu thể lực và tinh thần tốt'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Đăng ký trên nền tảng, tiếp cận bệnh viện, phòng khám để referral' }]},
    roadmap90: { months: [{ month: 2, task: 'Có 3-5 gia đình ký hợp đồng tháng' }]},
    roadmap180: { summary: '10-20tr/tháng, có thể mở cơ sở nhỏ' },
  },
  {
    name: 'Dịch Vụ Thú Cưng',
    slug: 'dich-vu-thu-cung',
    tagline: 'Trông giữ, tắm grooming, huấn luyện thú cưng',
    category: 'DAILY' as DirCategory,
    confidence: 'MEDIUM' as Confidence,
    sortOrder: 5,
    vpPeople: 65, vpExpert: 45, vpBuilder: 55, vpIndependent: 70,
    vrCapital: 35, vrTime: 70, vrTech: 30, vrNetwork: 50, vrRisk: 25, vrEnergy: 70,
    vbIncomeSpeed: 70, vbIncomePot: 55, vbScalability: 55, vbAiLeverage: 35,
    vsExpLeverage: 50, vsRelLeverage: 55, vsLearningDiff: 35, vsHealthReq: 60,
    description: 'Cung cấp dịch vụ chăm sóc thú cưng: trông giữ, tắm, cắt tỉa, huấn luyện.',
    whyFit: 'Phù hợp người yêu thú cưng, có không gian nhà phù hợp.',
    barriers: ['Trách nhiệm với thú cưng người khác', 'Cần không gian'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Setup không gian, đăng ký Pet in Town/nhóm pet local, nhận job đầu' }]},
    roadmap90: { months: [{ month: 2, task: 'Có 10+ khách hàng quen, thêm dịch vụ' }]},
    roadmap180: { summary: '5-15tr/tháng, mở rộng thành pet shop nhỏ' },
  },

  // ─────────────────────────────────────────────
  // DỊCH VỤ CHUYÊN BIỆT (4)
  // ─────────────────────────────────────────────
  {
    name: 'Chụp Ảnh / Quay Video Sự Kiện',
    slug: 'chup-anh-quay-video',
    tagline: 'Chụp ảnh sự kiện, cưới hỏi, thương mại',
    category: 'DICH_VU' as DirCategory,
    confidence: 'HIGH' as Confidence,
    sortOrder: 1,
    vpPeople: 60, vpExpert: 80, vpBuilder: 55, vpIndependent: 80,
    vrCapital: 55, vrTime: 60, vrTech: 70, vrNetwork: 60, vrRisk: 25, vrEnergy: 60,
    vbIncomeSpeed: 70, vbIncomePot: 60, vbScalability: 40, vbAiLeverage: 55,
    vsExpLeverage: 80, vsRelLeverage: 65, vsLearningDiff: 40, vsHealthReq: 50,
    description: 'Cung cấp dịch vụ chụp ảnh và quay video cho sự kiện, doanh nghiệp.',
    whyFit: 'Phù hợp người có thiết bị tốt, kỹ năng nhiếp ảnh, thích làm việc event.',
    barriers: ['Thiết bị đắt', 'Mùa vụ không đều', 'Hậu kỳ tốn thời gian'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Update portfolio, đăng ký nhóm cưới hỏi local, nhận 2 job đầu' }]},
    roadmap90: { months: [{ month: 2, task: 'Có review tốt, tăng giá, nhận referral' }]},
    roadmap180: { summary: '10-30tr/tháng, chuyên vào 1 niche (cưới, sản phẩm, sự kiện)' },
  },
  {
    name: 'Marketing / Social Media Agency Nhỏ',
    slug: 'marketing-agency-nho',
    tagline: 'Quản lý mạng xã hội và marketing cho SMEs',
    category: 'DICH_VU' as DirCategory,
    confidence: 'HIGH' as Confidence,
    sortOrder: 2,
    vpPeople: 65, vpExpert: 70, vpBuilder: 70, vpIndependent: 70,
    vrCapital: 20, vrTime: 65, vrTech: 65, vrNetwork: 65, vrRisk: 25, vrEnergy: 65,
    vbIncomeSpeed: 65, vbIncomePot: 75, vbScalability: 65, vbAiLeverage: 80,
    vsExpLeverage: 75, vsRelLeverage: 70, vsLearningDiff: 45, vsHealthReq: 20,
    description: 'Cung cấp dịch vụ marketing tổng thể cho doanh nghiệp nhỏ: social media, content, ads.',
    whyFit: 'Phù hợp người có kinh nghiệm marketing, thích digital, muốn phục vụ nhiều client.',
    barriers: ['Cần team để scale', 'Client yêu cầu cao về kết quả'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Nhận 2-3 client thử nghiệm với giá thấp để build case study' }]},
    roadmap90: { months: [{ month: 2, task: 'Standardize packages, tăng giá, thuê freelancer phụ' }]},
    roadmap180: { summary: '20-50tr/tháng với 5-8 clients retainer' },
  },
  {
    name: 'Tổ Chức Sự Kiện',
    slug: 'to-chuc-su-kien',
    tagline: 'Lên kế hoạch và tổ chức sự kiện công ty, gia đình',
    category: 'DICH_VU' as DirCategory,
    confidence: 'MEDIUM' as Confidence,
    sortOrder: 3,
    vpPeople: 80, vpExpert: 55, vpBuilder: 70, vpIndependent: 60,
    vrCapital: 45, vrTime: 70, vrTech: 40, vrNetwork: 75, vrRisk: 50, vrEnergy: 75,
    vbIncomeSpeed: 65, vbIncomePot: 65, vbScalability: 50, vbAiLeverage: 45,
    vsExpLeverage: 60, vsRelLeverage: 80, vsLearningDiff: 35, vsHealthReq: 65,
    description: 'Lên kế hoạch, điều phối và thực hiện sự kiện: hội nghị, tiệc cưới, team building.',
    whyFit: 'Phù hợp người có khả năng tổ chức, network rộng với vendor.',
    barriers: ['Áp lực ngày sự kiện cao', 'Rủi ro do nhà cung cấp'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Tổ chức 1 event nhỏ cho người quen, build portfolio ảnh' }]},
    roadmap90: { months: [{ month: 2, task: 'Ký được 2-3 hợp đồng, build vendor network' }]},
    roadmap180: { summary: '15-40tr/tháng, team 3-5 người' },
  },
  {
    name: 'Dịch Vụ Kế Toán / Thuế Cho SME',
    slug: 'ke-toan-thue-sme',
    tagline: 'Kế toán thuế outsource cho doanh nghiệp nhỏ',
    category: 'DICH_VU' as DirCategory,
    confidence: 'HIGH' as Confidence,
    sortOrder: 4,
    vpPeople: 40, vpExpert: 90, vpBuilder: 35, vpIndependent: 80,
    vrCapital: 10, vrTime: 55, vrTech: 50, vrNetwork: 60, vrRisk: 15, vrEnergy: 45,
    vbIncomeSpeed: 70, vbIncomePot: 70, vbScalability: 55, vbAiLeverage: 65,
    vsExpLeverage: 95, vsRelLeverage: 65, vsLearningDiff: 20, vsHealthReq: 15,
    description: 'Cung cấp dịch vụ kế toán, quyết toán thuế thuê ngoài cho SME.',
    whyFit: 'Phù hợp kế toán viên muốn làm độc lập, phục vụ nhiều doanh nghiệp nhỏ.',
    barriers: ['Cần chứng chỉ kế toán', 'Trách nhiệm pháp lý'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Tiếp cận 10 doanh nghiệp quen, offer dịch vụ gói tháng' }]},
    roadmap90: { months: [{ month: 2, task: 'Có 5-10 clients tháng, chuẩn hóa quy trình' }]},
    roadmap180: { summary: '10-25tr/tháng với 8-15 clients' },
  },

  // ─────────────────────────────────────────────
  // ĐẦU TƯ & TÀI SẢN (3)
  // ─────────────────────────────────────────────
  {
    name: 'Đầu Tư Bất Động Sản Cho Thuê',
    slug: 'dau-tu-bat-dong-san',
    tagline: 'Mua và cho thuê bất động sản tạo thu nhập thụ động',
    category: 'DAU_TU' as DirCategory,
    confidence: 'HIGH' as Confidence,
    sortOrder: 1,
    vpPeople: 40, vpExpert: 55, vpBuilder: 55, vpIndependent: 75,
    vrCapital: 90, vrTime: 30, vrTech: 25, vrNetwork: 60, vrRisk: 55, vrEnergy: 30,
    vbIncomeSpeed: 25, vbIncomePot: 85, vbScalability: 70, vbAiLeverage: 35,
    vsExpLeverage: 60, vsRelLeverage: 65, vsLearningDiff: 40, vsHealthReq: 20,
    description: 'Đầu tư mua bất động sản cho thuê để tạo dòng tiền thụ động.',
    whyFit: 'Phù hợp người có vốn lớn, muốn thu nhập thụ động ổn định.',
    barriers: ['Yêu cầu vốn rất lớn', 'Rủi ro thị trường', 'Pháp lý phức tạp'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Nghiên cứu thị trường, xác định ngân sách, tìm môi giới đáng tin' }]},
    roadmap90: { months: [{ month: 2, task: 'Tìm được 1-2 tài sản tiềm năng, thẩm định pháp lý' }]},
    roadmap180: { summary: 'Thu nhập cho thuê 5-15tr/tháng/căn sau khi mua' },
  },
  {
    name: 'Cho Thuê Phòng Trọ / Airbnb',
    slug: 'cho-thue-phong-tro-airbnb',
    tagline: 'Tối ưu hóa bất động sản nhàn rỗi để cho thuê',
    category: 'DAU_TU' as DirCategory,
    confidence: 'HIGH' as Confidence,
    sortOrder: 2,
    vpPeople: 50, vpExpert: 40, vpBuilder: 60, vpIndependent: 70,
    vrCapital: 65, vrTime: 45, vrTech: 45, vrNetwork: 45, vrRisk: 40, vrEnergy: 45,
    vbIncomeSpeed: 60, vbIncomePot: 70, vbScalability: 55, vbAiLeverage: 50,
    vsExpLeverage: 45, vsRelLeverage: 50, vsLearningDiff: 30, vsHealthReq: 30,
    description: 'Cho thuê phòng trọ dài hạn hoặc căn hộ ngắn hạn qua Airbnb.',
    whyFit: 'Phù hợp người đã có bất động sản, muốn khai thác hiệu quả hơn.',
    barriers: ['Quản lý tenant', 'Thuế Airbnb', 'Chi phí bảo trì'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Setup phòng, chụp ảnh đẹp, đăng trên Airbnb và nhóm cho thuê' }]},
    roadmap90: { months: [{ month: 2, task: 'Tỷ lệ lấp đầy 70-80%, review tốt' }]},
    roadmap180: { summary: '5-20tr/tháng, có thể quản lý thêm phòng của người khác' },
  },
  {
    name: 'Đầu Tư Tài Chính (Cổ Phiếu / Quỹ ETF)',
    slug: 'dau-tu-tai-chinh',
    tagline: 'Đầu tư dài hạn qua cổ phiếu và quỹ ETF',
    category: 'DAU_TU' as DirCategory,
    confidence: 'MEDIUM' as Confidence,
    sortOrder: 3,
    vpPeople: 20, vpExpert: 60, vpBuilder: 40, vpIndependent: 90,
    vrCapital: 75, vrTime: 25, vrTech: 45, vrNetwork: 30, vrRisk: 65, vrEnergy: 20,
    vbIncomeSpeed: 10, vbIncomePot: 80, vbScalability: 90, vbAiLeverage: 55,
    vsExpLeverage: 55, vsRelLeverage: 30, vsLearningDiff: 55, vsHealthReq: 10,
    description: 'Đầu tư dài hạn vào cổ phiếu, quỹ ETF để tăng trưởng tài sản.',
    whyFit: 'Phù hợp người có vốn nhàn rỗi, kỷ luật tài chính, tầm nhìn dài hạn.',
    barriers: ['Rủi ro thị trường', 'Cần kiến thức tài chính', 'Thu nhập không đều'],
    roadmap30: { weeks: [{ week: '1-4', task: 'Học 3 khóa đầu tư cơ bản, mở tài khoản, đầu tư thử 10-20tr' }]},
    roadmap90: { months: [{ month: 2, task: 'Xây danh mục đầu tư cơ bản, theo dõi và điều chỉnh' }]},
    roadmap180: { summary: 'Thu nhập cổ tức và tăng trưởng danh mục dài hạn' },
  },
];

async function main() {
  console.log('🌱 Seeding database...');

  // Create default SUPER_ADMIN
  const adminPassword = await bcrypt.hash(process.env.ADMIN_SEED_PASSWORD || 'ChangeMe123!', 12);
  await prisma.adminUser.upsert({
    where: { email: 'admin@sol.vn' },
    update: {},
    create: {
      email: 'admin@sol.vn',
      passwordHash: adminPassword,
      displayName: 'Khang Sol',
      role: 'SUPER_ADMIN',
    },
  });
  console.log('✅ Admin user created: admin@sol.vn');

  // Upsert all directions
  let created = 0;
  let updated = 0;

  for (const d of directions) {
    const existing = await prisma.direction.findUnique({ where: { slug: d.slug } });
    if (existing) {
      await prisma.direction.update({
        where: { slug: d.slug },
        data: { ...d, status: 'PUBLISHED', publishedAt: existing.publishedAt ?? new Date() },
      });
      updated++;
    } else {
      await prisma.direction.create({
        data: { ...d, status: 'PUBLISHED', publishedAt: new Date() },
      });
      created++;
    }
  }

  console.log(`✅ Directions: ${created} created, ${updated} updated (total: ${directions.length})`);
  console.log('✅ Seed complete!');
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
