#!/bin/bash
# =================================================================
# Sol Admin SPA Deployment — Day 8 (2026-05-21)
#
# Run on VPS: bash /var/www/sol-widget-old/app/scripts/deploy-admin.sh
#
# Prerequisites:
#   1. Backend live (bothuocla.sol.vn/api OK)
#   2. DNS Cloudflare: admin.sol.vn → 103.72.57.11 (DNS-only xám)
#   3. Sẽ tự cài Certbot SSL nếu chưa có
# =================================================================

set -e

REPO_DIR="/var/www/sol-widget-old"
ADMIN_DIR="$REPO_DIR/admin"
WEB_ROOT="/var/www/admin-sol-vn"
BACKUP_DIR="/var/www/admin-sol-vn-backups"
NGINX_CONF_SRC="$REPO_DIR/app/scripts/nginx-admin-sol-vn.conf"
NGINX_CONF_DST="/etc/nginx/sites-enabled/admin.sol.vn"
DOMAIN="admin.sol.vn"
EMAIL="nguyendinhkhang@gmail.com"

echo ""
echo "================================================="
echo "  SOL ADMIN SPA DEPLOY"
echo "  Source: $ADMIN_DIR"
echo "  Target: $WEB_ROOT  →  https://$DOMAIN"
echo "================================================="
echo ""

# === 1. Sanity checks ===
echo "[1/8] Sanity checks..."

if [ ! -d "$ADMIN_DIR" ]; then
    echo "  ❌ Admin dir không tồn tại: $ADMIN_DIR"
    echo "  Chạy: cd /var/www/sol-widget-old && git pull"
    exit 1
fi

# Backend phải đang chạy
HEALTH=$(curl -s -o /dev/null -w "%{http_code}" https://bothuocla.sol.vn/api/healthz || echo "000")
if [ "$HEALTH" != "200" ]; then
    echo "  ❌ Backend healthz = $HEALTH (expected 200) — fix backend trước"
    exit 1
fi
echo "  ✓ Backend OK"

# DNS verify
DNS_IP=$(dig +short A $DOMAIN @8.8.8.8 2>/dev/null | tail -1)
if [ -z "$DNS_IP" ]; then
    echo "  ❌ DNS chưa có A record cho $DOMAIN"
    echo "  Vào Cloudflare → sol.vn → DNS → Add A admin → 103.72.57.11"
    echo "  ⚠️ TẠM CHUYỂN PROXY SANG DNS-ONLY (xám) khi chạy Certbot"
    exit 1
fi
echo "  ✓ DNS: $DOMAIN → $DNS_IP"
echo ""

# === 2. Cleanup .bak3 files ===
echo "[2/8] Cleanup admin .bak3 files..."
cd "$ADMIN_DIR"
find src -name "*.bak*" -type f -delete 2>/dev/null
echo "  ✓ Cleaned"
echo ""

# === 3. Backup current static (rollback safety) ===
echo "[3/8] Backup current $WEB_ROOT..."
sudo mkdir -p "$BACKUP_DIR"
TS=$(date +%Y%m%d-%H%M%S)
if [ -d "$WEB_ROOT" ] && [ "$(ls -A $WEB_ROOT 2>/dev/null)" ]; then
    sudo cp -r "$WEB_ROOT" "$BACKUP_DIR/snapshot-$TS"
    sudo ls -1t "$BACKUP_DIR" | tail -n +6 | xargs -I {} sudo rm -rf "$BACKUP_DIR/{}" 2>/dev/null || true
    echo "  ✓ Backup → $BACKUP_DIR/snapshot-$TS"
else
    echo "  (no existing files, skip backup)"
fi
echo ""

# === 4. Build admin SPA ===
echo "[4/8] Build admin (vite build)..."
cd "$ADMIN_DIR"

cat > .env.production <<EOF
# Auto-generated by deploy-admin.sh (Day 8 — 2026-05-21)
VITE_API_BASE=https://bothuocla.sol.vn/api
EOF

npm ci --prefer-offline --no-audit --no-fund 2>&1 | tail -5

echo "  → Running vite build..."
VITE_API_BASE=https://bothuocla.sol.vn/api npm run build 2>&1 | tail -10

if [ ! -f "$ADMIN_DIR/dist/index.html" ]; then
    echo "  ❌ Build failed — dist/index.html not found"
    exit 1
fi
echo "  ✓ Built — $(du -sh $ADMIN_DIR/dist | cut -f1)"
echo ""

# === 5. Deploy dist ===
echo "[5/8] Deploy dist → $WEB_ROOT..."
sudo mkdir -p "$WEB_ROOT"
sudo rm -rf "$WEB_ROOT"/*
sudo cp -r "$ADMIN_DIR/dist/"* "$WEB_ROOT/"
sudo chown -R www-data:www-data "$WEB_ROOT"
sudo find "$WEB_ROOT" -type d -exec chmod 755 {} \;
sudo find "$WEB_ROOT" -type f -exec chmod 644 {} \;
echo "  ✓ Deployed"
echo ""

# === 6. Install nginx config + Certbot ===
echo "[6/8] Setup nginx + SSL..."

# Tạo cert tạm bằng config HTTP-only nếu chưa có SSL
SSL_DIR="/etc/letsencrypt/live/$DOMAIN"
if [ ! -d "$SSL_DIR" ]; then
    echo "  → Cert chưa có, dùng HTTP-only config + chạy Certbot"

    # Config HTTP-only tạm
    sudo tee "$NGINX_CONF_DST" > /dev/null <<NGINXTMP
server {
    listen 80;
    server_name $DOMAIN;
    root $WEB_ROOT;
    index index.html;
    location /.well-known/acme-challenge/ { root /var/www/html; }
    location / { try_files \$uri \$uri/ /index.html; }
}
NGINXTMP

    sudo nginx -t
    sudo systemctl reload nginx
    echo "  → HTTP-only config active, chạy Certbot..."

    sudo certbot --nginx -d "$DOMAIN" --email "$EMAIL" --agree-tos --non-interactive --redirect

    echo "  ✓ Certbot xong"
fi

# Install full config (with SSL)
sudo cp "$NGINX_CONF_SRC" "$NGINX_CONF_DST"
sudo nginx -t
sudo systemctl reload nginx
echo "  ✓ Nginx config OK"
echo ""

# === 7. Update CORS_ORIGINS backend ===
echo "[7/8] Update backend CORS_ORIGINS..."
BACKEND_ENV="$REPO_DIR/backend/.env"
if ! grep -q "admin.sol.vn" "$BACKEND_ENV"; then
    # Replace CORS line — backup trước
    sudo cp "$BACKEND_ENV" "$BACKEND_ENV.bak-$TS"
    # Add admin.sol.vn nếu chưa có
    sed -i 's|^CORS_ORIGINS=\(.*\)|CORS_ORIGINS=\1,https://admin.sol.vn|' "$BACKEND_ENV"
    echo "  ✓ CORS_ORIGINS updated"
    pm2 restart sol-api --update-env
    sleep 2
else
    echo "  (admin.sol.vn đã có trong CORS_ORIGINS, skip)"
fi
echo ""

# === 8. Smoke test ===
echo "[8/8] Smoke test..."
sleep 2

echo "  → HTTPS:"
curl -s -o /dev/null -w "    HTTP: %{http_code}\n" https://$DOMAIN/

echo "  → SPA deep link:"
curl -s -o /dev/null -w "    /content returns: %{http_code} (expect 200)\n" https://$DOMAIN/content

echo "  → CORS test (gọi backend từ admin origin):"
curl -s -o /dev/null -w "    Preflight: %{http_code}\n" \
  -X OPTIONS https://bothuocla.sol.vn/api/admin/canned-replies \
  -H "Origin: https://admin.sol.vn" \
  -H "Access-Control-Request-Method: GET"

echo ""
echo "================================================="
echo "  DONE!"
echo "================================================="
echo ""
echo "Bước cuối:"
echo "  1. Vào Cloudflare → BẬT LẠI proxy (cam) cho admin.sol.vn"
echo "  2. SSL/TLS mode → Full (strict)"
echo "  3. Mở https://$DOMAIN → login email magic link với nguyendinhkhang@gmail.com"
echo "  4. Sau đó vào /canned-replies để edit CHIP"
echo ""
echo "Rollback:"
echo "  LATEST=\$(ls -1t $BACKUP_DIR | head -1)"
echo "  sudo rm -rf $WEB_ROOT/* && sudo cp -r $BACKUP_DIR/\$LATEST/* $WEB_ROOT/"
echo "  sudo systemctl reload nginx"
