#!/bin/bash
# =================================================================
# Sol Dashboard SPA Deployment — Vite React build → static deploy
# Day 7 (2026-05-21)
#
# Run on VPS: bash /var/www/sol-widget-old/app/scripts/deploy-dashboard.sh
#
# Prerequisites:
#   1. Backend đã deploy + chạy (PM2 sol-api online)
#   2. Repo pulled mới nhất tại /var/www/sol-widget-old/
#   3. Nginx config bothuocla.sol.vn v3 đã active
# =================================================================

set -e

REPO_DIR="/var/www/sol-widget-old"
DASHBOARD_DIR="$REPO_DIR/dashboard"
WEB_ROOT="/var/www/bothuocla-sol-vn"
BACKUP_DIR="/var/www/bothuocla-sol-vn-backups"

echo ""
echo "================================================="
echo "  SOL DASHBOARD SPA DEPLOY"
echo "  Source: $DASHBOARD_DIR"
echo "  Target: $WEB_ROOT"
echo "================================================="
echo ""

# === 1. Sanity checks ===
echo "[1/6] Sanity checks..."

if [ ! -d "$DASHBOARD_DIR" ]; then
    echo "  ❌ Dashboard dir không tồn tại: $DASHBOARD_DIR"
    echo "  Chạy: cd /var/www/sol-widget-old && git pull"
    exit 1
fi

NODE_VERSION=$(node -v 2>/dev/null || echo "MISSING")
if [[ "$NODE_VERSION" != v20* ]] && [[ "$NODE_VERSION" != v22* ]]; then
    echo "  ⚠️  Node version: $NODE_VERSION (khuyến nghị v20 LTS)"
fi

# Backend phải đang chạy để dashboard gọi /api
HEALTH=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:4000/healthz)
if [ "$HEALTH" != "200" ]; then
    echo "  ⚠️  Backend healthz = $HEALTH (expected 200) — dashboard có thể không hoạt động"
fi

echo "  ✓ Checks done"
echo ""

# === 2. Backup current static (rollback safety) ===
echo "[2/6] Backup current /var/www/bothuocla-sol-vn..."
sudo mkdir -p "$BACKUP_DIR"
TS=$(date +%Y%m%d-%H%M%S)
if [ -d "$WEB_ROOT" ]; then
    sudo cp -r "$WEB_ROOT" "$BACKUP_DIR/snapshot-$TS"
    # Giữ 5 backup gần nhất
    sudo ls -1t "$BACKUP_DIR" | tail -n +6 | xargs -I {} sudo rm -rf "$BACKUP_DIR/{}" 2>/dev/null || true
    echo "  ✓ Backup saved to $BACKUP_DIR/snapshot-$TS"
else
    echo "  (no existing web root, skip backup)"
fi
echo ""

# === 3. Install + build ===
echo "[3/6] npm ci + build dashboard..."
cd "$DASHBOARD_DIR"

# Tạo .env.production với same-origin API path
cat > .env.production <<EOF
# Auto-generated by deploy-dashboard.sh (Day 7 — 2026-05-21)
# Same-origin: dashboard và backend cùng bothuocla.sol.vn
VITE_API_BASE=/api
VITE_BASE=/
EOF

# VITE_BASE=/ rất quan trọng — override default '/app/' trong vite.config.ts
# (mặc định trong vite.config.ts là '/app/' cho mount path Firebase cũ)
echo "  → Building with VITE_BASE=/ VITE_API_BASE=/api"

npm ci --prefer-offline --no-audit --no-fund 2>&1 | tail -5

echo "  → Running vite build (có thể mất 30-60s)..."
VITE_BASE=/ VITE_API_BASE=/api npm run build 2>&1 | tail -10

if [ ! -d "$DASHBOARD_DIR/dist" ]; then
    echo "  ❌ Build failed — dist/ not found"
    exit 1
fi

if [ ! -f "$DASHBOARD_DIR/dist/index.html" ]; then
    echo "  ❌ Build failed — dist/index.html not found"
    exit 1
fi

echo "  ✓ Built — $(du -sh $DASHBOARD_DIR/dist | cut -f1)"
echo ""

# === 4. Deploy dist → /var/www/ ===
echo "[4/6] Deploy dist → $WEB_ROOT..."
sudo rm -rf "$WEB_ROOT"
sudo mkdir -p "$WEB_ROOT"
sudo cp -r "$DASHBOARD_DIR/dist/"* "$WEB_ROOT/"
# Cũng copy dotfiles (vd .vite manifest nếu có)
sudo cp -r "$DASHBOARD_DIR/dist/."[!.]* "$WEB_ROOT/" 2>/dev/null || true

sudo chown -R www-data:www-data "$WEB_ROOT"
sudo find "$WEB_ROOT" -type d -exec chmod 755 {} \;
sudo find "$WEB_ROOT" -type f -exec chmod 644 {} \;
echo "  ✓ Deployed — $(ls $WEB_ROOT | wc -l) files at root"
echo ""

# === 5. Test nginx + reload ===
echo "[5/6] Test nginx + reload..."
sudo nginx -t 2>&1 | tail -3
sudo systemctl reload nginx
echo "  ✓ Nginx reloaded"
echo ""

# === 6. Smoke test ===
echo "[6/6] Smoke test..."
sleep 2

echo ""
echo "  → HTTPS root:"
curl -s -o /dev/null -w "    HTTP: %{http_code}  |  size: %{size_download} bytes\n" https://bothuocla.sol.vn/

echo "  → HTTPS deep link (SPA fallback test):"
curl -s -o /dev/null -w "    HTTP: %{http_code}  |  /journey returns: %{http_code}\n" https://bothuocla.sol.vn/journey

echo "  → API still working:"
curl -s https://bothuocla.sol.vn/api/healthz
echo ""

echo "  → Vite assets cache OK:"
ASSET=$(ls "$WEB_ROOT/assets/" 2>/dev/null | grep -E "\.(js|css)$" | head -1)
if [ -n "$ASSET" ]; then
    curl -s -o /dev/null -w "    /assets/$ASSET → %{http_code} (cache-control: %{header_cache_control})\n" "https://bothuocla.sol.vn/assets/$ASSET"
fi

echo ""
echo "================================================="
echo "  DONE!"
echo "================================================="
echo ""
echo "Test trong browser:"
echo "  https://bothuocla.sol.vn/             → Dashboard SPA (Overview hoặc redirect /test-ftnd nếu user mới)"
echo "  https://bothuocla.sol.vn/test-ftnd    → Test FTND form 6 câu"
echo "  https://bothuocla.sol.vn/pricing      → Trang giá 3 cohort + VietQR"
echo "  https://bothuocla.sol.vn/chat         → Chat với AI Mentor"
echo "  https://bothuocla.sol.vn/journey      → Hành trình 88 ngày"
echo ""
echo "Rollback (nếu cần):"
echo "  LATEST=\$(ls -1t $BACKUP_DIR | head -1)"
echo "  sudo rm -rf $WEB_ROOT && sudo cp -r $BACKUP_DIR/\$LATEST $WEB_ROOT"
echo "  sudo systemctl reload nginx"
echo ""
